TER_DEIMOS = {
    "Ship info": {
        "variables": {"displayedName": '"GTCv Deimos"', "sobDescription": "Corvette"},
        "functions": [],
    },
    "Health and Armour": {
        "variables": {
            "maxhealth": 'getShipNum(NewShipType, "maxhealth", 85000)',
            "regentime": "850",
            "minRegenTime": "850",
            "sideArmourDamage": 'getShipNum(NewShipType, "sideArmourDamage", 1.0)',
            "rearArmourDamage": 'getShipNum(NewShipType, "rearArmourDamage", 1.2)',
        },
        "functions": [],
    },
    "Tactics And Multipliers": {
        "variables": {"defaultROE": '"Defensive"', "defaultStance": '"Neutral"'},
        "functions": [
            {"name": "setTacticsMults", "args": ["ENGINEACCEL", "1.10", "0.90", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["THRUSTERACCEL", "1.10", "0.90", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["ROTATION", "0.95", "1.05", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["ROTATIONACCEL", "1.10", "0.90", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["FIRERATE", "0.98", "1.02", "1.0"]},
        ],
    },
    "Main Ship Data": {"variables": {"isTransferable": "1"}, "functions": []},
    "Movement": {
        "variables": {
            "mass": "115000",
            "thrusterMaxSpeed": "30",
            "mainEngineMaxSpeed": "120",
            "rotationMaxSpeed": "12",
            "thrusterAccelTime": "8",
            "thrusterBrakeTime": "4",
            "mainEngineAccelTime": "8",
            "mainEngineBrakeTime": "4",
            "rotationAccelTime": "4",
            "rotationBrakeTime": "2",
        },
        "functions": [],
    },
    "Damage & Death": {
        "variables": {
            "collisionMultiplier": "1",
            "dustCloudDamageTime": "160",
            "nebulaDamageTime": "300",
            "battleScarCoverage": "3",
            "battleScarBudgetLow": "600",
            "battleScarBudgetNext": "900",
            "sobDieTime": "3.5",
            "sobSpecialDieTime": "1",
            "specialDeathSpeed": "40",
            "chanceOfSpecialDeath": "0",
            "deadSobFadeTime": "0.1",
        },
        "functions": [],
    },
    "Advanced Movement": {
        "variables": {
            "thrusterUsage": "1",
            "accelerationAngle": "60",
            "mirrorAngle": "0",
            "secondaryTurnAngle": "0",
            "maxBankingAmount": "40",
            "descendPitch": "40",
            "goalReachEpsilon": "25",
            "slideMoveRange": "350",
            "controllerType": '"Ship"',
            "relativeMoveFactor": "1",
        },
        "functions": [],
    },
    "Death Tumble": {
        "variables": {
            "tumbleStaticX": "10",
            "tumbleStaticY": "20",
            "tumbleStaticZ": "5",
            "tumbleDynamicX": "2",
            "tumbleDynamicY": "10",
            "tumbleDynamicZ": "5",
            "tumbleSpecialDynamicX": "2",
            "tumbleSpecialDynamicY": "10",
            "tumbleSpecialDynamicZ": "5",
        },
        "functions": [],
    },
    "Layout Boundary": {
        "variables": {
            "useLayoutBounds": "1",
            "layoutBoundX": "60",
            "layoutBoundY": "60",
            "layoutBoundZ": "230",
            "layoutCenterX": "0",
            "layoutCenterY": "0",
            "layoutCenterZ": "20",
        },
        "functions": [],
    },
    "Families": {
        "variables": {
            "MinimalFamilyToFindPathAround": '"MotherShip"',
            "BuildFamily": '"SuperCap_Ter"',
            "AttackFamily": '"SmallCapitalShip"',
            "DockFamily": '"SuperCap"',
            "AvoidanceFamily": '"Capital"',
            "DisplayFamily": '"Capital"',
            "AutoFormationFamily": '"CapShip"',
            "CollisionFamily": '"Big"',
            "ArmourFamily": 'getShipStr(NewShipType, "ArmourFamily", "HeavyArmour")',
        },
        "functions": [],
    },
    "Supply": {
        "variables": {},
        "functions": [
            {"name": "setSupplyValue", "args": ["Capital", "1.0"]},
            {"name": "setSupplyValue", "args": ["Deimos", "1.0"]},
        ],
    },
    "Ship Counter Rating": {
        "variables": {
            "fighterValue": "0",
            "corvetteValue": "0",
            "frigateValue": "40",
            "neutralValue": "10",
            "antiFighterValue": "0",
            "antiCorvetteValue": "0",
            "antiFrigateValue": "30",
            "totalValue": "50",
        },
        "functions": [],
    },
    "Construction": {
        "variables": {
            "buildCost": "3000",
            "buildTime": "110",
            "buildPriorityOrder": "20",
        },
        "functions": [],
    },
    "Sensors": {
        "variables": {
            "retaliationRange": "6000",
            "retaliationDistanceFromGoal": "160",
            "visualRange": "1000",
            "prmSensorRange": "6500",
            "secSensorRange": "7500",
            "detectionStrength": "1",
        },
        "functions": [],
    },
    "Tactical Overlay Icon": {
        "variables": {
            "TOIcon": '"Parallelogram"',
            "TOScale": "1",
            "TODistanceFade0": "11000",
            "TODistanceDisappear0": "9000",
            "TODistanceFade1": "5500",
            "TODistanceDisappear1": "5000",
            "TODistanceFade2": "12000",
            "TODistanceDisappear2": "35000",
            "TOGroupScale": "1",
            "TOGroupMergeSize": "0",
        },
        "functions": [],
    },
    "Overlays": {
        "variables": {
            "mouseOverMinFadeSize": "0.045",
            "mouseOverMaxFadeSize": "0.1",
            "healthBarStyle": "2",
            "SMRepresentation": '"Mesh"',
            "SMHighlightDistMin": "15000",
            "SMHighlightDistMax": "25000",
        },
        "functions": [],
    },
    "Non linear Scaling": {
        "variables": {
            "nlips": "0.00007",
            "nlipsRange": "6000",
            "nlipsFar": "0.000013",
            "nlipsFarRange": "10000",
        },
        "functions": [],
    },
    "Rendering": {
        "variables": {
            "meshRenderLimit": "18000",
            "dotRenderLimit": "10",
            "visibleInSecondary": "1",
            "goblinsStartFade": "2150",
            "goblinsOff": "2150",
            "minimumZoomFactor": "0.5",
        },
        "functions": [],
    },
    "Level of Detail": {
        "variables": {"minLOD": "0.25", "upLOD": "30000", "downLOD": "30015"},
        "functions": [],
    },
    "Selection": {
        "variables": {
            "selectionLimit": "150000",
            "preciseSelectionLimit": "5000",
            "preciseATILimit": "0",
            "selectionPriority": "75",
            "militaryUnit": "1",
        },
        "functions": [],
    },
    "Alternative Hyperspace Gate": {
        "variables": {
            "alternativeHyperspaceV": "subspace_gate_small",
            "alternativeHyperspaceA": "etg/misc/small_subspace",
            "alternativeHyperspaceTime": "7",
        },
        "functions": [],
    },
    "Abilities": {
        "variables": {},
        "functions": [
            {"name": "addAbility", "args": ["MoveCommand", "1", "0"]},
            {"name": "addAbility", "args": ["ParadeCommand", "1"]},
            {"name": "addAbility", "args": ['WaypointMove"']},
            {
                "name": "addAbility",
                "args": ["HyperSpaceCommand", "1", "1", "350", "1050", "0", "3"],
            },
            {
                "name": "addAbility",
                "args": [
                    "CanAttack",
                    "1",
                    "1",
                    "0",
                    "0",
                    "0.35",
                    "1.5",
                    "Munition, BigCapitalShip, SmallCapitalShip, Capturer, Mothership, Frigate, Corvette, Fighter, Utility",
                    "MoveToTargetAndShoot",
                    '{Fighter="MoveToTargetAndShoot"}',
                    '{Fighter_hw1="MoveToTargetAndShoot"}',
                    '{Corvette="MoveToTargetAndShoot"}',
                    '{Corvette_hw1="MoveToTargetAndShoot"}',
                    '{Munition="MoveToTargetAndShoot"}',
                    '{SubSystem="MoveToTargetAndShoot"}',
                ],
            },
            {"name": "addAbility", "args": ["GuardCommand", "1", "3000", "800"]},
            {
                "name": "addAbility",
                "args": ["HyperspaceViaGateCommand", "1", "3", "3.5", "0.3"],
            },
            {"name": "addAbility", "args": ["CanBeCaptured", "90", "0.5", 'CapCap"']},
            {"name": "addAbility", "args": ["CanBeRepaired", 'RepCap"']},
            
        ],
    },
    "Formations": {
        "variables": {"strikeGroupRadius": "200", "canSurround": "1"},
        "functions": [],
    },
    "Load Model": {
        "variables": {},
        "functions": [{"name": "LoadModel", "args": ["1"]}],
    },
    "HardPoints": {
        "variables": {},
        "functions": [
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "TerSlash1",
                    "Weapon_11",
                    "Weapon",
                    "Innate",
                    "Damageable",
                    "ter_deimosbeam",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "TerSlash2",
                    "Weapon_12",
                    "Weapon",
                    "Innate",
                    "Damageable",
                    "ter_deimosbeam",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "TerSlash1",
                    "Weapon_23",
                    "Weapon",
                    "Innate",
                    "Damageable",
                    "ter_deimosbeam",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "TerSlash2",
                    "Weapon_24",
                    "Weapon",
                    "Innate",
                    "Damageable",
                    "ter_deimosbeam",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
        ],
    },
    "Weapons": {
        "variables": {},
        "functions": [
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terbig_turret", "Weapon_01", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terbig_turret", "Weapon_02", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terbig_turret", "Weapon_03", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terbig_turret", "Weapon_04", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_flak_turret", "Weapon_05", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_flak_turret", "Weapon_06", ""],
            },
            {"name": "StartShipWeaponConfig", "args": ["beam_AABlue", "Weapon_07", ""]},
            {"name": "StartShipWeaponConfig", "args": ["Beam_AABlue", "Weapon_08", ""]},
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_flak_turret", "Weapon_09", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_flak_turret", "Weapon_10", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_flak_turret", "Weapon_13", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terlaser_gimble", "Weapon_14", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terlaser_gimble", "Weapon_15", ""],
            },
            {"name": "StartShipWeaponConfig", "args": ["beam_AABlue", "Weapon_16", ""]},
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_flak_turret", "Weapon_17", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terlaser_gimble", "Weapon_18", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terlaser_gimble", "Weapon_19", ""],
            },
            {"name": "StartShipWeaponConfig", "args": ["beam_AABlue", "Weapon_20", ""]},
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terlaser_gimble", "Weapon_21", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terlaser_gimble", "Weapon_22", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["miss_pihrana", "Weapon_25", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["miss_pihrana", "Weapon_26", ""],
            },
        ],
    },
    "Shields": {
        "variables": {},
        "functions": [{"name": "addShield", "args": ["EMP", "1000", "20"]}],
    },
    "Engines": {
        "variables": {"trailLinger": "3"},
        "functions": [
            {
                "name": "setEngineBurn",
                "args": ["7", "0.5", "3", "80", "0", "0.7", "0.1", "280"],
            },
        ],
    },
    "Addendum": {
        "variables": {},
        "functions": [
            {
                "name": "loadShipPatchList",
                "args": [
                    "data:sound/sfx/ship/",
                    "0",
                    "",
                    "",
                    "1",
                    "TerranCapital",
                    "",
                    "3",
                    "",
                    "Root",
                ],
            }
        ],
    },
    "Latch Points": {
        "variables": {},
        "functions": [
            {
                "name": "loadLatchPointList",
                "args": [
                    "CapCap",
                    "CapturePoint0",
                    "CapturePoint1",
                    "CapturePoint2",
                    "CapturePoint3",
                ],
            },
            {
                "name": "loadLatchPointList",
                "args": [
                    "RepCap",
                    "RepairPoint0",
                    "RepairPoint1",
                    "RepairPoint2",
                    'RepairPoint3"',
                ],
            },
        ],
    },
    "Scuttle": {
        "variables": {
            "minFalloffDamageDist": "250",
            "maxFalloffDamageDist": "250*1.5",
            "maxFalloffScuttleDamageDist": "250*3",
            "explosiveScuttleDamageOnDeath": "2688",
            "maxFalloffForce": "500*10",
            "explosiveDamageOnDeath": "538",
            "radiusDamageEvadeMod": "1.1",
        },
        "functions": [],
    },
}
VAS_SOBEK = {
    "Ship info": {
        "variables": {"displayedName": '"GVCv Sobek"', "sobDescription": "Corvette"},
        "functions": [],
    },
    "Health and Armour": {
        "variables": {
            "maxhealth": 'getShipNum(NewShipType, "maxhealth", 85000)',
            "regentime": "850",
            "minRegenTime": "850",
            "sideArmourDamage": 'getShipNum(NewShipType, "sideArmourDamage", 1.0)',
            "rearArmourDamage": 'getShipNum(NewShipType, "rearArmourDamage", 1.2)',
        },
        "functions": [],
    },
    "Tactics And Multipliers": {
        "variables": {"defaultROE": '"Defensive"', "defaultStance": '"Neutral"'},
        "functions": [
            {"name": "setTacticsMults", "args": ["ENGINEACCEL", "1.10", "0.90", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["THRUSTERACCEL", "1.10", "0.90", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["ROTATION", "0.95", "1.05", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["ROTATIONACCEL", "1.10", "0.90", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["FIRERATE", "0.98", "1.02", "1.0"]},
        ],
    },
    "Main Ship Data": {"variables": {"isTransferable": "1"}, "functions": []},
    "Movement": {
        "variables": {
            "mass": "115000",
            "thrusterMaxSpeed": "30",
            "mainEngineMaxSpeed": "120",
            "rotationMaxSpeed": "12",
            "thrusterAccelTime": "8",
            "thrusterBrakeTime": "4",
            "mainEngineAccelTime": "8",
            "mainEngineBrakeTime": "4",
            "rotationAccelTime": "4",
            "rotationBrakeTime": "2",
        },
        "functions": [],
    },
    "Damage & Death": {
        "variables": {
            "collisionMultiplier": "1",
            "dustCloudDamageTime": "160",
            "nebulaDamageTime": "300",
            "battleScarCoverage": "3",
            "battleScarBudgetLow": "600",
            "battleScarBudgetNext": "900",
            "sobDieTime": "3.5",
            "sobSpecialDieTime": "1",
            "specialDeathSpeed": "40",
            "chanceOfSpecialDeath": "0",
            "deadSobFadeTime": "0.1",
        },
        "functions": [],
    },
    "Advanced Movement": {
        "variables": {
            "thrusterUsage": "1",
            "accelerationAngle": "60",
            "mirrorAngle": "0",
            "secondaryTurnAngle": "0",
            "maxBankingAmount": "40",
            "descendPitch": "40",
            "goalReachEpsilon": "25",
            "slideMoveRange": "350",
            "controllerType": '"Ship"',
            "relativeMoveFactor": "1",
        },
        "functions": [],
    },
    "Death Tumble": {
        "variables": {
            "tumbleStaticX": "10",
            "tumbleStaticY": "20",
            "tumbleStaticZ": "5",
            "tumbleDynamicX": "2",
            "tumbleDynamicY": "10",
            "tumbleDynamicZ": "5",
            "tumbleSpecialDynamicX": "2",
            "tumbleSpecialDynamicY": "10",
            "tumbleSpecialDynamicZ": "5",
        },
        "functions": [],
    },
    "Layout Boundary": {
        "variables": {
            "useLayoutBounds": "1",
            "layoutBoundX": "60",
            "layoutBoundY": "60",
            "layoutBoundZ": "230",
            "layoutCenterX": "0",
            "layoutCenterY": "0",
            "layoutCenterZ": "20",
        },
        "functions": [],
    },
    "Families": {
        "variables": {
            "MinimalFamilyToFindPathAround": '"MotherShip"',
            "BuildFamily": '"SuperCap_Vas"',
            "AttackFamily": '"SmallCapitalShip"',
            "DockFamily": '"SuperCap"',
            "AvoidanceFamily": '"Capital"',
            "DisplayFamily": '"Capital"',
            "AutoFormationFamily": '"CapShip"',
            "CollisionFamily": '"Big"',
            "ArmourFamily": 'getShipStr(NewShipType, "ArmourFamily", "HeavyArmour")',
        },
        "functions": [],
    },
    "Supply": {
        "variables": {},
        "functions": [
            {"name": "setSupplyValue", "args": ["Capital", "1.0"]},
            {"name": "setSupplyValue", "args": ["Sobek", "1.0"]},
        ],
    },
    "Ship Counter Rating": {
        "variables": {
            "fighterValue": "0",
            "corvetteValue": "0",
            "frigateValue": "40",
            "neutralValue": "10",
            "antiFighterValue": "0",
            "antiCorvetteValue": "0",
            "antiFrigateValue": "30",
            "totalValue": "50",
        },
        "functions": [],
    },
    "Construction": {
        "variables": {
            "buildCost": "3000",
            "buildTime": "110",
            "buildPriorityOrder": "20",
        },
        "functions": [],
    },
    "Sensors": {
        "variables": {
            "retaliationRange": "6000",
            "retaliationDistanceFromGoal": "160",
            "visualRange": "1000",
            "prmSensorRange": "6500",
            "secSensorRange": "7500",
            "detectionStrength": "1",
        },
        "functions": [],
    },
    "Tactical Overlay Icon": {
        "variables": {
            "TOIcon": '"Parallelogram"',
            "TOScale": "1",
            "TODistanceFade0": "11000",
            "TODistanceDisappear0": "9000",
            "TODistanceFade1": "5500",
            "TODistanceDisappear1": "5000",
            "TODistanceFade2": "12000",
            "TODistanceDisappear2": "35000",
            "TOGroupScale": "1",
            "TOGroupMergeSize": "0",
        },
        "functions": [],
    },
    "Overlays": {
        "variables": {
            "mouseOverMinFadeSize": "0.045",
            "mouseOverMaxFadeSize": "0.1",
            "healthBarStyle": "2",
            "SMRepresentation": '"Mesh"',
            "SMHighlightDistMin": "15000",
            "SMHighlightDistMax": "25000",
        },
        "functions": [],
    },
    "Non linear Scaling": {
        "variables": {
            "nlips": "0.00007",
            "nlipsRange": "6000",
            "nlipsFar": "0.000013",
            "nlipsFarRange": "10000",
        },
        "functions": [],
    },
    "Rendering": {
        "variables": {
            "meshRenderLimit": "18000",
            "dotRenderLimit": "10",
            "visibleInSecondary": "1",
            "goblinsStartFade": "2150",
            "goblinsOff": "2150",
            "minimumZoomFactor": "0.5",
        },
        "functions": [],
    },
    "Level of Detail": {
        "variables": {"minLOD": "0.25", "upLOD": "6000", "downLOD": "6015"},
        "functions": [],
    },
    "Selection": {
        "variables": {
            "selectionLimit": "150000",
            "preciseSelectionLimit": "5000",
            "preciseATILimit": "0",
            "selectionPriority": "75",
            "militaryUnit": "1",
        },
        "functions": [],
    },
    "Alternative Hyperspace Gate": {
        "variables": {
            "alternativeHyperspaceV": "subspace_gate_small",
            "alternativeHyperspaceA": "etg/misc/small_subspace",
            "alternativeHyperspaceTime": "7",
        },
        "functions": [],
    },
    "Abilities": {
        "variables": {},
        "functions": [
            {"name": "addAbility", "args": ["MoveCommand", "1", "0"]},
            {"name": "addAbility", "args": ["ParadeCommand", "1"]},
            {"name": "addAbility", "args": ['WaypointMove"']},
            {
                "name": "addAbility",
                "args": ["HyperSpaceCommand", "1", "1", "350", "1050", "0", "3"],
            },
            {
                "name": "addAbility",
                "args": [
                    "CanAttack",
                    "1",
                    "1",
                    "0",
                    "0",
                    "0.35",
                    "1.5",
                    "Munition, BigCapitalShip, SmallCapitalShip, Capturer, Mothership, Frigate, Corvette, Fighter, Utility",
                    "MoveToTargetAndShoot",
                    '{Fighter="MoveToTargetAndShoot"}',
                    '{Fighter_hw1="MoveToTargetAndShoot"}',
                    '{Corvette="MoveToTargetAndShoot"}',
                    '{Corvette_hw1="MoveToTargetAndShoot"}',
                    '{Munition="MoveToTargetAndShoot"}',
                    '{SubSystem="MoveToTargetAndShoot"}',
                ],
            },
            {"name": "addAbility", "args": ["GuardCommand", "1", "3000", "800"]},
            {
                "name": "addAbility",
                "args": ["HyperspaceViaGateCommand", "1", "3", "3.5", "0.3"],
            },
            {"name": "addAbility", "args": ["CanBeCaptured", "90", "0.5", 'CapCap"']},
            {"name": "addAbility", "args": ["CanBeRepaired", 'RepCap"']},
            
        ],
    },
    "Formations": {
        "variables": {"strikeGroupRadius": "200", "canSurround": "1"},
        "functions": [],
    },
    "Load Model": {
        "variables": {},
        "functions": [{"name": "LoadModel", "args": ["1"]}],
    },
    "HardPoints": {
        "variables": {},
        "functions": [
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Vslash1",
                    "Weapon_B1",
                    "Weapon",
                    "Innate",
                    "Damageable",
                    "vas_sobekbeam",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Vslash2",
                    "Weapon_B2",
                    "Weapon",
                    "Innate",
                    "Damageable",
                    "vas_sobekbeam",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
        ],
    },
    "Weapons": {
        "variables": {},
        "functions": [
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_vaslaser_gimble", "Weapon_Laser1", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_vaslaser_gimble", "Weapon_Laser2", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_vaslaser_gimble", "Weapon_Laser3", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_vaslaser_gimble", "Weapon_Laser4", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_vaslaser_gimble", "Weapon_Laser5", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_vaslaser_gimble", "Weapon_Laser6", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_vaslaser_gimble", "Weapon_Laser7", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_vaslaser_gimble", "Weapon_Laser8", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_flak_turret", "Weapon_Flak1", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_flak_turret", "Weapon_Flak2", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_flak_turret", "Weapon_Flak3", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_flak_turret", "Weapon_Flak4", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["beam_AABlue", "Weapon_AFB1", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["beam_AABlue", "Weapon_AFB2", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["beam_AABlue", "Weapon_AFB3", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["beam_AABlue", "Weapon_AFB4", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_vashuge_turret", "Weapon_TurretLaser1", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_vashuge_turret", "Weapon_TurretLaser2", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_vashuge_turret", "Weapon_TurretLaser3", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_vashuge_turret", "Weapon_TurretLaser4", ""],
            },
        ],
    },
    "Shields": {
        "variables": {},
        "functions": [{"name": "addShield", "args": ["EMP", "1000", "20"]}],
    },
    "Engines": {
        "variables": {"trailLinger": "3"},
        "functions": [
            {
                "name": "setEngineBurn",
                "args": ["7", "0.5", "3", "80", "0", "0.7", "0.1", "280"],
            }
        ],
    },
    "Addendum": {
        "variables": {},
        "functions": [
            {
                "name": "loadShipPatchList",
                "args": [
                    "data:sound/sfx/ship/",
                    "0",
                    "",
                    "",
                    "1",
                    "VasudanCapital",
                    "",
                    "3",
                    "",
                    "Root",
                ],
            }
        ],
    },
    "Latch Points": {
        "variables": {},
        "functions": [
            {
                "name": "loadLatchPointList",
                "args": [
                    "CapCap",
                    "CapturePoint0",
                    "CapturePoint1",
                    "CapturePoint2",
                    "CapturePoint3",
                ],
            },
            {
                "name": "loadLatchPointList",
                "args": [
                    "RepCap",
                    "RepairPoint0",
                    "RepairPoint1",
                    "RepairPoint2",
                    'RepairPoint3"',
                ],
            },
        ],
    },
    "Scuttle": {
        "variables": {
            "minFalloffDamageDist": "250",
            "maxFalloffDamageDist": "250*1.5",
            "maxFalloffScuttleDamageDist": "250*3",
            "explosiveScuttleDamageOnDeath": "2688",
            "maxFalloffForce": "500*10",
            "explosiveDamageOnDeath": "538",
            "radiusDamageEvadeMod": "1.1",
        },
        "functions": [],
    },
}
SHI_MOLOCH = {
    "Ship info": {
        "variables": {"displayedName": '"SCv Moloch"', "sobDescription": "Corvette"},
        "functions": [],
    },
    "Health and Armour": {
        "variables": {
            "maxhealth": 'getShipNum(NewShipType, "maxhealth", 85000)',
            "regentime": "850",
            "minRegenTime": "850",
            "sideArmourDamage": 'getShipNum(NewShipType, "sideArmourDamage", 1.0)',
            "rearArmourDamage": 'getShipNum(NewShipType, "rearArmourDamage", 1.2)',
        },
        "functions": [],
    },
    "Tactics And Multipliers": {
        "variables": {"defaultROE": '"Defensive"', "defaultStance": '"Neutral"'},
        "functions": [
            {"name": "setTacticsMults", "args": ["ENGINEACCEL", "1.10", "0.90", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["THRUSTERACCEL", "1.10", "0.90", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["ROTATION", "0.95", "1.05", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["ROTATIONACCEL", "1.10", "0.90", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["FIRERATE", "0.98", "1.02", "1.0"]},
        ],
    },
    "Main Ship Data": {"variables": {"isTransferable": "1"}, "functions": []},
    "Movement": {
        "variables": {
            "mass": "115000",
            "thrusterMaxSpeed": "30",
            "mainEngineMaxSpeed": "120",
            "rotationMaxSpeed": "11",
            "thrusterAccelTime": "8",
            "thrusterBrakeTime": "4",
            "mainEngineAccelTime": "8",
            "mainEngineBrakeTime": "4",
            "rotationAccelTime": "4",
            "rotationBrakeTime": "2",
        },
        "functions": [],
    },
    "Damage & Death": {
        "variables": {
            "collisionMultiplier": "1",
            "dustCloudDamageTime": "280",
            "nebulaDamageTime": "300",
            "battleScarCoverage": "3",
            "battleScarBudgetLow": "600",
            "battleScarBudgetNext": "900",
            "sobDieTime": "3.5",
            "sobSpecialDieTime": "1",
            "specialDeathSpeed": "40",
            "chanceOfSpecialDeath": "0",
            "deadSobFadeTime": "0.1",
        },
        "functions": [],
    },
    "Advanced Movement": {
        "variables": {
            "thrusterUsage": "1",
            "accelerationAngle": "30",
            "mirrorAngle": "0",
            "secondaryTurnAngle": "0",
            "maxBankingAmount": "10",
            "descendPitch": "10",
            "goalReachEpsilon": "25",
            "slideMoveRange": "350",
            "controllerType": '"Ship"',
            "relativeMoveFactor": "1",
        },
        "functions": [],
    },
    "Death Tumble": {
        "variables": {
            "tumbleStaticX": "10",
            "tumbleStaticY": "20",
            "tumbleStaticZ": "5",
            "tumbleDynamicX": "2",
            "tumbleDynamicY": "10",
            "tumbleDynamicZ": "5",
            "tumbleSpecialDynamicX": "2",
            "tumbleSpecialDynamicY": "10",
            "tumbleSpecialDynamicZ": "5",
        },
        "functions": [],
    },
    "Layout Boundary": {
        "variables": {
            "useLayoutBounds": "1",
            "layoutBoundX": "60",
            "layoutBoundY": "60",
            "layoutBoundZ": "230",
            "layoutCenterX": "0",
            "layoutCenterY": "0",
            "layoutCenterZ": "20",
        },
        "functions": [],
    },
    "Families": {
        "variables": {
            "MinimalFamilyToFindPathAround": '"MotherShip"',
            "BuildFamily": '"SuperCap_Shi"',
            "AttackFamily": '"SmallCapitalShip"',
            "DockFamily": '"SuperCap"',
            "AvoidanceFamily": '"Capital"',
            "DisplayFamily": '"Capital"',
            "AutoFormationFamily": '"CapShip"',
            "CollisionFamily": '"Big"',
            "ArmourFamily": 'getShipStr(NewShipType, "ArmourFamily", "HeavyArmour")',
        },
        "functions": [],
    },
    "Supply": {
        "variables": {},
        "functions": [
            {"name": "setSupplyValue", "args": ["Capital", "1.0"]},
            {"name": "setSupplyValue", "args": ["Moloch", "1.0"]},
        ],
    },
    "Ship Counter Rating": {
        "variables": {
            "fighterValue": "0",
            "corvetteValue": "0",
            "frigateValue": "40",
            "neutralValue": "10",
            "antiFighterValue": "0",
            "antiCorvetteValue": "0",
            "antiFrigateValue": "30",
            "totalValue": "50",
        },
        "functions": [],
    },
    "Construction": {
        "variables": {
            "buildCost": "3000",
            "buildTime": "110",
            "buildPriorityOrder": "40",
        },
        "functions": [],
    },
    "Sensors": {
        "variables": {
            "retaliationRange": "6000",
            "retaliationDistanceFromGoal": "160",
            "visualRange": "1000",
            "prmSensorRange": "6500",
            "secSensorRange": "7500",
            "detectionStrength": "1",
        },
        "functions": [],
    },
    "Tactical Overlay Icon": {
        "variables": {
            "TOIcon": '"Parallelogram"',
            "TOScale": "1",
            "TODistanceFade0": "11000",
            "TODistanceDisappear0": "9000",
            "TODistanceFade1": "5500",
            "TODistanceDisappear1": "5000",
            "TODistanceFade2": "12000",
            "TODistanceDisappear2": "35000",
            "TOGroupScale": "1",
            "TOGroupMergeSize": "0",
        },
        "functions": [],
    },
    "Overlays": {
        "variables": {
            "mouseOverMinFadeSize": "0.045",
            "mouseOverMaxFadeSize": "0.1",
            "healthBarStyle": "2",
            "SMRepresentation": '"Mesh"',
            "SMHighlightDistMin": "15000",
            "SMHighlightDistMax": "25000",
        },
        "functions": [],
    },
    "Non linear Scaling": {
        "variables": {
            "nlips": "0.00007",
            "nlipsRange": "6000",
            "nlipsFar": "0.000013",
            "nlipsFarRange": "10000",
        },
        "functions": [],
    },
    "Rendering": {
        "variables": {
            "meshRenderLimit": "18000",
            "dotRenderLimit": "10",
            "visibleInSecondary": "1",
            "goblinsStartFade": "2150",
            "goblinsOff": "2150",
            "minimumZoomFactor": "0.5",
        },
        "functions": [],
    },
    "Level of Detail": {
        "variables": {"minLOD": "0.25", "upLOD": "12500", "downLOD": "12515"},
        "functions": [],
    },
    "Selection": {
        "variables": {
            "selectionLimit": "150000",
            "preciseSelectionLimit": "5000",
            "preciseATILimit": "0",
            "selectionPriority": "75",
            "militaryUnit": "1",
        },
        "functions": [],
    },
    "Alternative Hyperspace Gate": {
        "variables": {
            "alternativeHyperspaceV": "subspace_gate_small",
            "alternativeHyperspaceA": "etg/misc/small_subspace",
            "alternativeHyperspaceTime": "7",
        },
        "functions": [],
    },
    "Abilities": {
        "variables": {},
        "functions": [
            {"name": "addAbility", "args": ["MoveCommand", "1", "0"]},
            {"name": "addAbility", "args": ["ParadeCommand", "1"]},
            {"name": "addAbility", "args": ['WaypointMove"']},
            {
                "name": "addAbility",
                "args": ["HyperSpaceCommand", "1", "1", "70", "350", "0", "3"],
            },
            {
                "name": "addAbility",
                "args": [
                    "CanAttack",
                    "1",
                    "1",
                    "0",
                    "1",
                    "0.35",
                    "1.5",
                    "Munition, BigCapitalShip, SmallCapitalShip, Capturer, Mothership, Frigate, Corvette, Fighter, Utility",
                    "MoveToTargetAndShoot",
                    '{Fighter="MoveToTargetAndShoot"}',
                    '{Fighter_hw1="MoveToTargetAndShoot"}',
                    '{Corvette="MoveToTargetAndShoot"}',
                    '{Corvette_hw1="MoveToTargetAndShoot"}',
                    '{Munition="MoveToTargetAndShoot"}',
                    '{SubSystem="MoveToTargetAndShoot"}',
                ],
            },
            {"name": "addAbility", "args": ["GuardCommand", "1", "3000", "800"]},
            {
                "name": "addAbility",
                "args": ["HyperspaceViaGateCommand", "1", "3", "0.7", "0.3"],
            },
            {"name": "addAbility", "args": ["CanBeCaptured", "90", "0.5", 'CapCap"']},
            {"name": "addAbility", "args": ["CanBeRepaired", 'RepCap"']},
            
        ],
    },
    "Formations": {
        "variables": {"strikeGroupRadius": "200", "canSurround": "1"},
        "functions": [],
    },
    "Load Model": {
        "variables": {},
        "functions": [{"name": "LoadModel", "args": ["1"]}],
    },
    "HardPoints": {
        "variables": {},
        "functions": [
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "SRED1",
                    "Weapon_01",
                    "Weapon",
                    "Innate",
                    "Damageable",
                    "shi_molochsred",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "SRED1",
                    "Weapon_05",
                    "Weapon",
                    "Innate",
                    "Damageable",
                    "shi_molochsred",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "SRED1",
                    "Weapon_06",
                    "Weapon",
                    "Innate",
                    "Damageable",
                    "shi_molochsred",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
        ],
    },
    "Weapons": {
        "variables": {},
        "functions": [
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_shivsuperlaser_turret", "Weapon_02", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_shivsuperlaser_turret", "Weapon_03", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["miss_fighterkiller_turret", "Weapon_04", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_flak_turret", "Weapon_07", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_flak_turret", "Weapon_08", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_flak_turret", "Weapon_09", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_shivsuperlaser_turret", "Weapon_10", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["miss_pihrana", "Weapon_11", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_shivsuperlaser_turret", "Weapon_12", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["miss_pihrana", "Weapon_13", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_shivsuperlaser_turret", "Weapon_14", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_flak_turret", "Weapon_15", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["miss_fighterkiller_turret", "Weapon_16", ""],
            },
        ],
    },
    "Shields": {
        "variables": {},
        "functions": [{"name": "addShield", "args": ["EMP", "1000", "20"]}],
    },
    "Engines": {
        "variables": {"trailLinger": "3"},
        "functions": [
            {
                "name": "setEngineBurn",
                "args": ["7", "0.5", "1", "80", "0", "0.7", "0.1", "280"],
            }
        ],
    },
    "Addendum": {
        "variables": {},
        "functions": [
            {
                "name": "loadShipPatchList",
                "args": [
                    "data:sound/sfx/ship/",
                    "0",
                    "",
                    "",
                    "1",
                    "ShivanCapital",
                    "",
                    "3",
                    "",
                    "Root",
                ],
            }
        ],
    },
    "Latch Points": {
        "variables": {},
        "functions": [
            {
                "name": "loadLatchPointList",
                "args": [
                    "CapCap",
                    "CapturePoint0",
                    "CapturePoint1",
                    "CapturePoint2",
                    "CapturePoint3",
                ],
            },
            {
                "name": "loadLatchPointList",
                "args": [
                    "RepCap",
                    "RepairPoint0",
                    "RepairPoint1",
                    "RepairPoint2",
                    'RepairPoint3"',
                ],
            },
        ],
    },
    "Scuttle": {
        "variables": {
            "minFalloffDamageDist": "250",
            "maxFalloffDamageDist": "250*1.5",
            "maxFalloffScuttleDamageDist": "250*3",
            "explosiveScuttleDamageOnDeath": "2688",
            "maxFalloffForce": "500*10",
            "explosiveDamageOnDeath": "538",
            "radiusDamageEvadeMod": "1.1",
        },
        "functions": [],
    },
}
TER_ICENI = {
    "Ship info": {
        "variables": {
            "displayedName": '"NTF Iceni"',
            "sobDescription": "Command Corvette",
        },
        "functions": [],
    },
    "Health and Armour": {
        "variables": {
            "maxhealth": 'getShipNum(NewShipType, "maxhealth", 150000)',
            "regentime": "1000",
            "minRegenTime": "1000",
            "sideArmourDamage": 'getShipNum(NewShipType, "sideArmourDamage", 1.0)',
            "rearArmourDamage": 'getShipNum(NewShipType, "rearArmourDamage", 1.2)',
        },
        "functions": [],
    },
    "Tactics And Multipliers": {
        "variables": {"defaultROE": '"Defensive"', "defaultStance": '"Neutral"'},
        "functions": [
            {"name": "setTacticsMults", "args": ["ENGINEACCEL", "1.10", "0.90", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["THRUSTERACCEL", "1.10", "0.90", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["ROTATION", "0.95", "1.05", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["ROTATIONACCEL", "1.10", "0.90", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["FIRERATE", "0.98", "1.02", "1.0"]},
        ],
    },
    "Main Ship Data": {"variables": {"isTransferable": "1"}, "functions": []},
    "Movement": {
        "variables": {
            "mass": "200000",
            "thrusterMaxSpeed": "190",
            "mainEngineMaxSpeed": "190",
            "rotationMaxSpeed": "8",
            "thrusterAccelTime": "8",
            "thrusterBrakeTime": "4",
            "mainEngineAccelTime": "8",
            "mainEngineBrakeTime": "4",
            "rotationAccelTime": "4",
            "rotationBrakeTime": "2",
        },
        "functions": [],
    },
    "Damage & Death": {
        "variables": {
            "collisionMultiplier": "1",
            "dustCloudDamageTime": "160",
            "nebulaDamageTime": "300",
            "battleScarCoverage": "4",
            "battleScarBudgetLow": "1200",
            "battleScarBudgetNext": "1800",
            "sobDieTime": "3.5",
            "sobSpecialDieTime": "1",
            "specialDeathSpeed": "40",
            "chanceOfSpecialDeath": "0",
            "deadSobFadeTime": "0.1",
        },
        "functions": [],
    },
    "Advanced Movement": {
        "variables": {
            "thrusterUsage": "1",
            "accelerationAngle": "60",
            "mirrorAngle": "0",
            "secondaryTurnAngle": "0",
            "maxBankingAmount": "40",
            "descendPitch": "40",
            "goalReachEpsilon": "25",
            "slideMoveRange": "350",
            "controllerType": '"Ship"',
            "relativeMoveFactor": "1",
        },
        "functions": [],
    },
    "Death Tumble": {
        "variables": {
            "tumbleStaticX": "10",
            "tumbleStaticY": "20",
            "tumbleStaticZ": "5",
            "tumbleDynamicX": "2",
            "tumbleDynamicY": "10",
            "tumbleDynamicZ": "5",
            "tumbleSpecialDynamicX": "2",
            "tumbleSpecialDynamicY": "10",
            "tumbleSpecialDynamicZ": "5",
        },
        "functions": [],
    },
    "Layout Boundary": {
        "variables": {
            "useLayoutBounds": "1",
            "layoutBoundX": "60",
            "layoutBoundY": "60",
            "layoutBoundZ": "230",
            "layoutCenterX": "0",
            "layoutCenterY": "0",
            "layoutCenterZ": "20",
        },
        "functions": [],
    },
    "Families": {
        "variables": {
            "MinimalFamilyToFindPathAround": '"MotherShip"',
            "BuildFamily": '"SuperCap_Ter"',
            "AttackFamily": '"SmallCapitalShip"',
            "DockFamily": '"SuperCap"',
            "AvoidanceFamily": '"Capital"',
            "DisplayFamily": '"Capital"',
            "AutoFormationFamily": '"CapShip"',
            "CollisionFamily": '"Big"',
            "ArmourFamily": 'getShipStr(NewShipType, "ArmourFamily", "HeavyArmour")',
        },
        "functions": [],
    },
    "Supply": {
        "variables": {},
        "functions": [
            {"name": "setSupplyValue", "args": ["Capital", "1.0"]},
            {"name": "setSupplyValue", "args": ["Iceni", "1.0"]},
        ],
    },
    "Ship Counter Rating": {
        "variables": {
            "fighterValue": "0",
            "corvetteValue": "0",
            "frigateValue": "40",
            "neutralValue": "10",
            "antiFighterValue": "0",
            "antiCorvetteValue": "0",
            "antiFrigateValue": "30",
            "totalValue": "50",
        },
        "functions": [],
    },
    "Construction": {
        "variables": {
            "buildCost": "9000",
            "buildTime": "210",
            "buildPriorityOrder": "20",
        },
        "functions": [],
    },
    "Sensors": {
        "variables": {
            "retaliationRange": "6000",
            "retaliationDistanceFromGoal": "160",
            "visualRange": "1000",
            "prmSensorRange": "6500",
            "secSensorRange": "7500",
            "detectionStrength": "1",
        },
        "functions": [],
    },
    "Tactical Overlay Icon": {
        "variables": {
            "TOIcon": '"Parallelogram"',
            "TOScale": "1",
            "TODistanceFade0": "11000",
            "TODistanceDisappear0": "9000",
            "TODistanceFade1": "5500",
            "TODistanceDisappear1": "5000",
            "TODistanceFade2": "12000",
            "TODistanceDisappear2": "35000",
            "TOGroupScale": "1",
            "TOGroupMergeSize": "0",
        },
        "functions": [],
    },
    "Overlays": {
        "variables": {
            "mouseOverMinFadeSize": "0.045",
            "mouseOverMaxFadeSize": "0.1",
            "healthBarStyle": "2",
            "SMRepresentation": '"Mesh"',
            "SMHighlightDistMin": "15000",
            "SMHighlightDistMax": "25000",
        },
        "functions": [],
    },
    "Non linear Scaling": {
        "variables": {
            "nlips": "0.00007",
            "nlipsRange": "6000",
            "nlipsFar": "0.000013",
            "nlipsFarRange": "10000",
        },
        "functions": [],
    },
    "Rendering": {
        "variables": {
            "meshRenderLimit": "18000",
            "dotRenderLimit": "10",
            "visibleInSecondary": "1",
            "goblinsStartFade": "2150",
            "goblinsOff": "2150",
            "minimumZoomFactor": "0.5",
        },
        "functions": [],
    },
    "Level of Detail": {
        "variables": {"minLOD": "0.25", "upLOD": "23000", "downLOD": "23015"},
        "functions": [],
    },
    "Selection": {
        "variables": {
            "selectionLimit": "150000",
            "preciseSelectionLimit": "5000",
            "preciseATILimit": "0",
            "selectionPriority": "75",
            "militaryUnit": "1",
        },
        "functions": [],
    },
    "Alternative Hyperspace Gate": {
        "variables": {
            "alternativeHyperspaceV": "subspace_gate_small",
            "alternativeHyperspaceA": "etg/misc/small_subspace",
            "alternativeHyperspaceTime": "7",
        },
        "functions": [],
    },
    "Abilities": {
        "variables": {},
        "functions": [
            {"name": "addAbility", "args": ["MoveCommand", "1", "0"]},
            {"name": "addAbility", "args": ["ParadeCommand", "1"]},
            {"name": "addAbility", "args": ['WaypointMove"']},
            {
                "name": "addAbility",
                "args": ["HyperSpaceCommand", "1", "1", "350", "1050", "0", "3"],
            },
            {
                "name": "addAbility",
                "args": [
                    "CanAttack",
                    "1",
                    "1",
                    "0",
                    "0",
                    "0.35",
                    "1.5",
                    "Munition, BigCapitalShip, SmallCapitalShip, Capturer, Mothership, Frigate, Corvette, Fighter, Utility",
                    "MoveToTargetAndShoot",
                    '{Fighter="MoveToTargetAndShoot"}',
                    '{Fighter_hw1="MoveToTargetAndShoot"}',
                    '{Corvette="MoveToTargetAndShoot"}',
                    '{Corvette_hw1="MoveToTargetAndShoot"}',
                    '{Munition="MoveToTargetAndShoot"}',
                    '{SubSystem="MoveToTargetAndShoot"}',
                ],
            },
            {"name": "addAbility", "args": ["GuardCommand", "1", "3000", "800"]},
            {
                "name": "addAbility",
                "args": ["HyperspaceViaGateCommand", "1", "3", "3.5", "0.3"],
            },
            {"name": "addAbility", "args": ["CanBeCaptured", "90", "0.5", 'CapCap"']},
            {"name": "addAbility", "args": ["CanBeRepaired", 'RepCap"']},
            
        ],
    },
    "Formations": {
        "variables": {"strikeGroupRadius": "200", "canSurround": "1"},
        "functions": [],
    },
    "Load Model": {
        "variables": {},
        "functions": [{"name": "LoadModel", "args": ["1"]}],
    },
    "HardPoints": {
        "variables": {},
        "functions": [
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Icenibeam1",
                    "Weapon_06",
                    "Weapon",
                    "Innate",
                    "Damageable",
                    "ter_icenibeam",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    ")",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Icenibeam2",
                    "Weapon_07",
                    "Weapon",
                    "Innate",
                    "Damageable",
                    "ter_icenibeam",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    ")",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Icenibeam3",
                    "Weapon_09",
                    "Weapon",
                    "Innate",
                    "Damageable",
                    "ter_icenibeam",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    ")",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Icenibeam4",
                    "Weapon_14",
                    "Weapon",
                    "Innate",
                    "Damageable",
                    "ter_icenibeam",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    ")",
                ],
            },
        ],
    },
    "Weapons": {
        "variables": {},
        "functions": [
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terlaser_turret", "Weapon_01", ""],
            },
            {"name": "StartShipWeaponConfig", "args": ["beam_AABlue", "Weapon_02", ""]},
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_flak_turret", "Weapon_03", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["miss_pihrana", "Weapon_04", ""],
            },
            {"name": "StartShipWeaponConfig", "args": ["beam_AABlue", "Weapon_05", ""]},
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terhugeturretlaser_gimble", "Weapon_08", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["miss_fighterkiller", "Weapon_10", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terlaser_turret", "Weapon_11", ""],
            },
            {"name": "StartShipWeaponConfig", "args": ["beam_AABlue", "Weapon_12", ""]},
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_flak_turret", "Weapon_13", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terhugeturretlaser_gimble", "Weapon_15", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terhugeturretlaser_gimble", "Weapon_16", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terhugeturretlaser_gimble", "Weapon_17", ""],
            },
            {"name": "StartShipWeaponConfig", "args": ["beam_AABlue", "Weapon_18", ""]},
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terlaser_turret", "Weapon_19", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["miss_fighterkiller", "Weapon_20", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terhuge_turret2", "Weapon_21", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terhuge_turret2", "Weapon_22", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terlaser_turret", "Weapon_23", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terlaser_turret", "Weapon_24", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terlaser_turret", "Weapon_25", ""],
            },
        ],
    },
    "Shields": {
        "variables": {},
        "functions": [{"name": "addShield", "args": ["EMP", "1000", "20"]}],
    },
    "Engines": {
        "variables": {"trailLinger": "3"},
        "functions": [
            {
                "name": "setEngineBurn",
                "args": ["7", "0.5", "3", "80", "0", "0.7", "0.1", "280"],
            }
        ],
    },
    "Addendum": {
        "variables": {},
        "functions": [
            {
                "name": "loadShipPatchList",
                "args": [
                    "data:sound/sfx/ship/",
                    "0",
                    "",
                    "",
                    "1",
                    "TerranCapital",
                    "",
                    "3",
                    "",
                    "Root",
                ],
            }
        ],
    },
    "Latch Points": {
        "variables": {},
        "functions": [
            {
                "name": "loadLatchPointList",
                "args": [
                    "CapCap",
                    "CapturePoint0",
                    "CapturePoint1",
                    "CapturePoint2",
                    "CapturePoint3",
                ],
            },
            {
                "name": "loadLatchPointList",
                "args": [
                    "RepCap",
                    "RepairPoint0",
                    "RepairPoint1",
                    "RepairPoint2",
                    'RepairPoint3"',
                ],
            },
        ],
    },
    "Scuttle": {
        "variables": {
            "minFalloffDamageDist": "250",
            "maxFalloffDamageDist": "250*1.5",
            "maxFalloffScuttleDamageDist": "250*3",
            "explosiveScuttleDamageOnDeath": "2688",
            "maxFalloffForce": "500*10",
            "explosiveDamageOnDeath": "538",
            "radiusDamageEvadeMod": "1.1",
        },
        "functions": [],
    },
}
