TER_ORION = {
    "Ship info": {
        "variables": {"displayedName": '"GTD Orion"', "sobDescription": '"Destroyer"'},
        "functions": [],
    },
    "Health and Armour": {
        "variables": {
            "maxhealth": 'getShipNum(NewShipType, "maxhealth", 80000)',
            "regentime": "1265",
            "minRegenTime": "1265",
            "sideArmourDamage": 'getShipNum(NewShipType, "sideArmourDamage", 1.0)',
            "rearArmourDamage": 'getShipNum(NewShipType, "rearArmourDamage", 1.0)',
        },
        "functions": [],
    },
    "Tactics And Multipliers": {
        "variables": {"defaultROE": '"Defensive"', "defaultStance": '"Neutral"'},
        "functions": [
            {"name": "setTacticsMults", "args": ["ENGINEACCEL", "1.10", "0.90", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["THRUSTERACCEL", "1.10", "0.90", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["ROTATION", "0.95", "1.05", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["ROTATIONACCEL", "1.10", "0.90", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["FIRERATE", "0.98", "1.02", "1.0"]},
        ],
    },
    "Main Ship Data": {"variables": {"isTransferable": "0"}, "functions": []},
    "Deprecated": {"variables": {"addedUnitCaps": "101"}, "functions": []},
    "Formations": {
        "variables": {
            "paradeData": '"terran_parade"',
            "strikeGroupRadius": "150",
            "noCombatGrouping": "1",
            "canSurround": "1",
        },
        "functions": [],
    },
    "Movement": {
        "variables": {
            "mass": "1600000",
            "thrusterMaxSpeed": "20",
            "mainEngineMaxSpeed": "60",
            "rotationMaxSpeed": "4.5",
            "thrusterAccelTime": "20",
            "thrusterBrakeTime": "10",
            "mainEngineAccelTime": "20",
            "mainEngineBrakeTime": "10",
            "rotationAccelTime": "10",
            "rotationBrakeTime": "5",
        },
        "functions": [],
    },
    "Damage & Death": {
        "variables": {
            "collisionMultiplier": "1600000",
            "dustCloudDamageTime": "280",
            "nebulaDamageTime": "800",
            "battleScarCoverage": "4",
            "battleScarBudgetLow": "1200",
            "battleScarBudgetNext": "1800",
            "sobDieTime": "8",
            "sobSpecialDieTime": "1",
            "specialDeathSpeed": "40",
            "chanceOfSpecialDeath": "0",
            "deadSobFadeTime": "0.1",
        },
        "functions": [],
    },
    "Advanced Movement": {
        "variables": {
            "thrusterUsage": "1",
            "accelerationAngle": "60",
            "mirrorAngle": "0",
            "secondaryTurnAngle": "0",
            "maxBankingAmount": "10",
            "descendPitch": "40",
            "goalReachEpsilon": "50",
            "slideMoveRange": "350",
            "controllerType": '"Ship"',
            "relativeMoveFactor": "1",
        },
        "functions": [],
    },
    "Death Tumble": {
        "variables": {
            "tumbleStaticX": "2",
            "tumbleStaticY": "4",
            "tumbleStaticZ": "3",
            "tumbleDynamicX": "1",
            "tumbleDynamicY": "2",
            "tumbleDynamicZ": "2",
            "tumbleSpecialDynamicX": "1",
            "tumbleSpecialDynamicY": "2",
            "tumbleSpecialDynamicZ": "2",
        },
        "functions": [],
    },
    "Swaying": {
        "variables": {
            "swayUpdateTime": "10",
            "swayOffsetRandomX": "10",
            "swayOffsetRandomY": "10",
            "swayOffsetRandomZ": "10",
            "swayBobbingFactor": "0",
            "swayRotateFactor": "0",
        },
        "functions": [],
    },
    "Layout Boundary": {
        "variables": {
            "useLayoutBounds": "1",
            "layoutBoundX": "130",
            "layoutBoundY": "60",
            "layoutBoundZ": "350",
            "layoutCenterX": "-20",
            "layoutCenterY": "0",
            "layoutCenterZ": "50",
        },
        "functions": [],
    },
    "Families": {
        "variables": {
            "MinimalFamilyToFindPathAround": '"MotherShip"',
            "BuildFamily": '"SuperCap_Ter"',
            "AttackFamily": '"BigCapitalShip"',
            "DockFamily": '"Shipyard"',
            "AvoidanceFamily": '"SuperCap"',
            "DisplayFamily": '"Capital"',
            "AutoFormationFamily": '"CapShip"',
            "CollisionFamily": '"Big"',
            "ArmourFamily": 'getShipStr(NewShipType, "ArmourFamily", "HeavyArmour")',
        },
        "functions": [],
    },
    "Supply": {
        "variables": {},
        "functions": [
            {"name": "setSupplyValue", "args": ["Capital", "1.0"]},
            {"name": "setSupplyValue", "args": ["Destroyer", "1.0"]},
        ],
    },
    "Ship Counter Rating": {
        "variables": {
            "AttackPriorityMultiplier": "0.96",
            "fighterValue": "0",
            "corvetteValue": "0",
            "frigateValue": "10",
            "neutralValue": "5",
            "antiFighterValue": "5",
            "antiCorvetteValue": "0",
            "antiFrigateValue": "0",
            "totalValue": "15",
        },
        "functions": [],
    },
    "Construction": {
        "variables": {
            "buildCost": "12500",
            "buildTime": "215",
            "buildPriorityOrder": "40",
        },
        "functions": [],
    },
    "Sensors": {
        "variables": {
            "retaliationRange": "6500",
            "retaliationDistanceFromGoal": "160",
            "visualRange": "1000",
            "prmSensorRange": "5000",
            "secSensorRange": "6000",
            "detectionStrength": "1",
        },
        "functions": [],
    },
    "Tactical Overlay Icon": {
        "variables": {
            "TOIcon": '"Rectangle"',
            "TOScale": "1",
            "TODistanceFade0": "14000",
            "TODistanceDisappear0": "12000",
            "TODistanceFade1": "5500",
            "TODistanceDisappear1": "5000",
            "TODistanceFade2": "12000",
            "TODistanceDisappear2": "35000",
            "TOGroupScale": "1",
            "TOGroupMergeSize": "0",
        },
        "functions": [],
    },
    "Overlays": {
        "variables": {
            "mouseOverMinFadeSize": "0.085",
            "mouseOverMaxFadeSize": "0.15",
            "healthBarStyle": "2",
            "SMRepresentation": '"Mesh"',
            "SMHighlightDistMin": "20000",
            "SMHighlightDistMax": "25000",
            "hideNormalAttackUICooldown": "1",
        },
        "functions": [],
    },
    "Non linear Scaling": {
        "variables": {
            "nlips": "0",
            "nlipsRange": "10000",
            "nlipsFar": "0",
            "nlipsFarRange": "0",
        },
        "functions": [],
    },
    "Rendering": {
        "variables": {
            "meshRenderLimit": "21000",
            "dotRenderLimit": "10",
            "visibleInSecondary": "1",
            "goblinsStartFade": "3200",
            "goblinsOff": "3200",
            "minimumZoomFactor": "0.5",
        },
        "functions": [],
    },
    "Level of Detail": {
        "variables": {"upLOD": "32500", "downLOD": "32515"},
        "functions": [],
    },
    "Selection": {
        "variables": {
            "selectionLimit": "150000",
            "preciseSelectionLimit": "7500",
            "preciseATILimit": "0",
            "selectionPriority": "75",
            "militaryUnit": "0",
        },
        "functions": [],
    },
    "Abilities": {
        "variables": {},
        "functions": [
            {"name": "addAbility", "args": ["MoveCommand", "1", "0"]},
            {"name": "addAbility", "args": ["CanDock", "1", "0"]},
            {"name": "addAbility", "args": ['CanLaunch"']},
            {
                "name": "addAbility",
                "args": [
                    "ShipHold",
                    "1",
                    "1000",
                    "20",
                    "rallypoint",
                    "Fighter, Bomber, Utility",
                    "200",
                ],
            },
            {"name": "addAbility", "args": ["ParadeCommand", "1"]},
            {"name": "addAbility", "args": ['WaypointMove"']},
            {
                "name": "addAbility",
                "args": ["HyperSpaceCommand", "1", "1", "875", "1750", "0", "3"],
            },
            {
                "name": "addAbility",
                "args": [
                    "CanAttack",
                    "1",
                    "1",
                    "0",
                    "1",
                    "0.35",
                    "1.5",
                    "Capturer,Frigate,SmallCapitalShip,BigCapitalShip,Mothership,Utility,,,,,Corvette, Corvette_hw1,Fighter, Fighter_hw1",
                    "Broadside",
                    '{ Fighter = "MoveToTargetAndShoot" }',
                    '{ Fighter_hw1 = "MoveToTargetAndShoot" }',
                    '{ Corvette = "MoveToTargetAndShoot" }',
                    '{ Corvette_hw1 = "MoveToTargetAndShoot" }',
                    '{ Munition = "MoveToTargetAndShoot" }',
                    '{ Subsystem = "Frontal" }',
                ],
            },
            {"name": "addAbility", "args": ["GuardCommand", "1", "3000", "1000"]},
            {
                "name": "addAbility",
                "args": [
                    "CanBuildShips",
                    "1",
                    "Fighter_Ter, Bomber_Ter, Cruiser_Ter, SuperCap_Ter, Utility_Ter, Platform_Ter, Battlecruiser_Ter, Shipyard_Ter, Probe_Ter",
                    "Utility, Fighter, Bomber, Cruiser, Capital, Platform",
                ],
            },
            {"name": "addAbility", "args": ["CanBeCaptured", "180", "0.5", 'CapCap"']},
            {"name": "addAbility", "args": ["CanBeRepaired", 'RepCap"']},
            {"name": "addAbility", "args": ["RetireAbility", "1", "1"]},
        ],
    },
    "Docking": {
        "variables": {
            "dockTimeBetweenTwoFormations": "1",
            "dockTimeBeforeStart": "2",
            "dockNrOfShipsInDockFormation": "1",
            "dockFormation": '"delta"',
            "queueFormation": '"dockline"',
            "dontDockWithOtherRaceShips": "1",
            "ignoreRaceWhenDocking": "0",
        },
        "functions": [],
    },
    "Launching": {
        "variables": {
            "launchTimeBetweenTwoFormations": "1",
            "launchTimeBeforeStart": "2",
            "launchNrOfShipsInDockFormation": "1",
            "launchFormation": '"delta"',
        },
        "functions": [],
    },
    "Custom Code": {
        "variables": {},
        "functions": [
            {
                "name": "addCustomCode",
                "args": [
                    "data:scripts/custom_scripts/add_nameplate.lua",
                    "onLoad",
                    "onCreate",
                    "updateNameplate",
                    "onDestroy",
                    "gta_orion",
                    "1",
                ],
            }
        ],
    },
    "Load Model": {
        "variables": {},
        "functions": [{"name": "LoadModel", "args": ["1"]}],
    },
    "Weapons": {
        "variables": {},
        "functions": [
            {
                "name": "StartShipWeaponConfig",
                "args": ["beam_AABlue", "Weapon_AAAf1", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["beam_AABlue", "Weapon_AAAf2", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["beam_AABlue", "Weapon_AAAf3", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terlaser_gimble", "Weapon_AAAf4", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terlaser_gimble", "Weapon_Laser1", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terlaser_gimble", "Weapon_Laser3", ""],
            },
        ],
    },
    "Shields": {
        "variables": {},
        "functions": [{"name": "addShield", "args": ["EMP", "10000", "20"]}],
    },
    "HardPoints": {
        "variables": {},
        "functions": [
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Ter_slash1",
                    "Weapon_B1",
                    "Weapon",
                    "Innate",
                    "Damageable",
                    "ter_slashorion",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Ter_slash2",
                    "Weapon_B3",
                    "Weapon",
                    "Innate",
                    "Damageable",
                    "ter_slashorion",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Ter_slash3",
                    "Weapon_B4",
                    "Weapon",
                    "Innate",
                    "Damageable",
                    "ter_slashorion",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Ter_bgreensa",
                    "Weapon_B2",
                    "Weapon",
                    "Innate",
                    "Damageable",
                    "ter_bgreenorion_gimble",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Ter_bgreensa1",
                    "Weapon_Laser2",
                    "Weapon",
                    "Innate",
                    "Damageable",
                    "ter_bgreenorion_gimble",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Ter_bgreenturret",
                    "Weapon_BGreen",
                    "Weapon",
                    "Innate",
                    "Damageable",
                    "ter_bgreenorion_turret",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Ter_OrionTurret1",
                    "Weapon_LaserTurret1",
                    "Weapon",
                    "Innate",
                    "Destroyable",
                    "Ter_orionhugeturret",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Ter_OrionTurret2",
                    "Weapon_LaserTurret2",
                    "Weapon",
                    "Innate",
                    "Destroyable",
                    "Ter_orionhugeturret",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Ter_OrionTurret3",
                    "Weapon_LaserTurret3",
                    "Weapon",
                    "Innate",
                    "Destroyable",
                    "Ter_orionhugeturret",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Ter_OrionTurret4",
                    "Weapon_LaserTurret4",
                    "Weapon",
                    "Innate",
                    "Destroyable",
                    "Ter_orionhugeturret",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Ter_OrionFlak1",
                    "Weapon_LaserTurret1",
                    "Weapon",
                    "Innate",
                    "Destroyable",
                    "",
                    "ter_orionhugeflak",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Ter_OrionFlak2",
                    "Weapon_LaserTurret2",
                    "Weapon",
                    "Innate",
                    "Destroyable",
                    "",
                    "ter_orionhugeflak",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Ter_OrionFlak3",
                    "Weapon_LaserTurret3",
                    "Weapon",
                    "Innate",
                    "Destroyable",
                    "",
                    "ter_orionhugeflak",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Ter_OrionFlak4",
                    "Weapon_LaserTurret4",
                    "Weapon",
                    "Innate",
                    "Destroyable",
                    "",
                    "ter_orionhugeflak",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Nameplate",
                    "Hardpoint_Nameplate",
                    "System",
                    "Innate",
                    "Indestructible",
                    "",
                    "ter_orion_nameplate_bastion",
                    "ter_orion_nameplate_carthage",
                    "ter_orion_nameplate_delacroix",
                    "ter_orion_nameplate_intrepid",
                    "ter_orion_nameplate_messana",
                    "ter_orion_nameplate_minnow",
                    "ter_orion_nameplate_nereid",
                    "ter_orion_nameplate_soyakaze",
                ],
            },
        ],
    },
    "Debris": {"variables": {}, "functions": []},
    "Engines": {
        "variables": {"trailLinger": "2"},
        "functions": [
            {
                "name": "setEngineBurn",
                "args": ["7", "1", "1", "200", "20", "1", "0.1", "800"],
            },
        ],
    },
    "Addendum": {
        "variables": {},
        "functions": [
            {
                "name": "loadShipPatchList",
                "args": ["data:sound/sfx/ship/", "0", "", "", "1", "TerranCapital", ""],
            }
        ],
    },
    "Latch Points": {
        "variables": {},
        "functions": [
            {
                "name": "loadLatchPointList",
                "args": [
                    "CapCap",
                    "CapturePoint1",
                    "CapturePoint2",
                    "CapturePoint3",
                    'CapturePoint4"',
                    'CapturePoint5"',
                ],
            },
            {
                "name": "loadLatchPointList",
                "args": [
                    "RepCap",
                    "RepairPoint0",
                    "RepairPoint1",
                    "RepairPoint2",
                    "RepairPoint3",
                    'RepairPoint4"',
                    'RepairPoint5"',
                ],
            },
        ],
    },
    "Scuttle": {
        "variables": {
            "minFalloffDamageDist": "450",
            "maxFalloffDamageDist": "450*1.5",
            "maxFalloffScuttleDamageDist": "450*3",
            "explosiveScuttleDamageOnDeath": "1960",
            "maxFalloffForce": "500*10",
            "explosiveDamageOnDeath": "275",
            "radiusDamageEvadeMod": "1.1",
        },
        "functions": [],
    },
}
TER_HECATE = {
    "Ship info": {
        "variables": {"displayedName": '"GTD Hecate"', "sobDescription": '"Destroyer"'},
        "functions": [],
    },
    "Health and Armour": {
        "variables": {
            "maxhealth": 'getShipNum(NewShipType, "maxhealth", 80000)',
            "regentime": "1265",
            "minRegenTime": "1265",
            "sideArmourDamage": 'getShipNum(NewShipType, "sideArmourDamage", 1.0)',
            "rearArmourDamage": 'getShipNum(NewShipType, "rearArmourDamage", 1.0)',
        },
        "functions": [],
    },
    "Tactics And Multipliers": {
        "variables": {"defaultROE": '"Defensive"', "defaultStance": '"Neutral"'},
        "functions": [
            {"name": "setTacticsMults", "args": ["ENGINEACCEL", "1.10", "0.90", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["THRUSTERACCEL", "1.10", "0.90", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["ROTATION", "0.95", "1.05", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["ROTATIONACCEL", "1.10", "0.90", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["FIRERATE", "0.98", "1.02", "1.0"]},
        ],
    },
    "Main Ship Data": {"variables": {"isTransferable": "0"}, "functions": []},
    "Deprecated": {"variables": {"addedUnitCaps": "101"}, "functions": []},
    "Formations": {
        "variables": {
            "paradeData": '"terran_parade"',
            "strikeGroupRadius": "150",
            "noCombatGrouping": "1",
            "canSurround": "1",
        },
        "functions": [],
    },
    "Movement": {
        "variables": {
            "mass": "1600000",
            "thrusterMaxSpeed": "20",
            "mainEngineMaxSpeed": "60",
            "rotationMaxSpeed": "4.5",
            "thrusterAccelTime": "20",
            "thrusterBrakeTime": "10",
            "mainEngineAccelTime": "20",
            "mainEngineBrakeTime": "10",
            "rotationAccelTime": "10",
            "rotationBrakeTime": "5",
        },
        "functions": [],
    },
    "Damage & Death": {
        "variables": {
            "collisionMultiplier": "1",
            "dustCloudDamageTime": "280",
            "nebulaDamageTime": "800",
            "battleScarCoverage": "4",
            "battleScarBudgetLow": "1200",
            "battleScarBudgetNext": "1800",
            "sobDieTime": "8",
            "sobSpecialDieTime": "1",
            "specialDeathSpeed": "40",
            "chanceOfSpecialDeath": "0",
            "deadSobFadeTime": "0.1",
        },
        "functions": [],
    },
    "Advanced Movement": {
        "variables": {
            "thrusterUsage": "1",
            "accelerationAngle": "60",
            "mirrorAngle": "0",
            "secondaryTurnAngle": "0",
            "maxBankingAmount": "10",
            "descendPitch": "40",
            "goalReachEpsilon": "25",
            "slideMoveRange": "350",
            "controllerType": '"Ship"',
            "relativeMoveFactor": "1",
        },
        "functions": [],
    },
    "Death Tumble": {
        "variables": {
            "tumbleStaticX": "2",
            "tumbleStaticY": "4",
            "tumbleStaticZ": "3",
            "tumbleDynamicX": "1",
            "tumbleDynamicY": "2",
            "tumbleDynamicZ": "2",
            "tumbleSpecialDynamicX": "1",
            "tumbleSpecialDynamicY": "2",
            "tumbleSpecialDynamicZ": "2",
        },
        "functions": [],
    },
    "Swaying": {
        "variables": {
            "swayUpdateTime": "10",
            "swayOffsetRandomX": "10",
            "swayOffsetRandomY": "10",
            "swayOffsetRandomZ": "10",
            "swayBobbingFactor": "0",
            "swayRotateFactor": "0",
        },
        "functions": [],
    },
    "Layout Boundary": {
        "variables": {
            "useLayoutBounds": "1",
            "layoutBoundX": "130",
            "layoutBoundY": "60",
            "layoutBoundZ": "350",
            "layoutCenterX": "-20",
            "layoutCenterY": "0",
            "layoutCenterZ": "50",
        },
        "functions": [],
    },
    "Families": {
        "variables": {
            "MinimalFamilyToFindPathAround": '"MotherShip"',
            "BuildFamily": '"SuperCap_Ter"',
            "AttackFamily": '"BigCapitalShip"',
            "DockFamily": '"Shipyard"',
            "AvoidanceFamily": '"SuperCap"',
            "DisplayFamily": '"Capital"',
            "AutoFormationFamily": '"CapShip"',
            "CollisionFamily": '"Big"',
            "ArmourFamily": 'getShipStr(NewShipType, "ArmourFamily", "HeavyArmour")',
        },
        "functions": [],
    },
    "Supply": {
        "variables": {},
        "functions": [
            {"name": "setSupplyValue", "args": ["Capital", "1.0"]},
            {"name": "setSupplyValue", "args": ["Destroyer", "1.0"]},
        ],
    },
    "Ship Counter Rating": {
        "variables": {
            "AttackPriorityMultiplier": "0.96",
            "fighterValue": "0",
            "corvetteValue": "0",
            "frigateValue": "10",
            "neutralValue": "5",
            "antiFighterValue": "5",
            "antiCorvetteValue": "0",
            "antiFrigateValue": "0",
            "totalValue": "15",
        },
        "functions": [],
    },
    "Construction": {
        "variables": {
            "buildCost": "11000",
            "buildTime": "200",
            "buildPriorityOrder": "40",
        },
        "functions": [],
    },
    "Sensors": {
        "variables": {
            "retaliationRange": "6500",
            "retaliationDistanceFromGoal": "160",
            "visualRange": "1000",
            "prmSensorRange": "5000",
            "secSensorRange": "6000",
            "detectionStrength": "1",
        },
        "functions": [],
    },
    "Tactical Overlay Icon": {
        "variables": {
            "TOIcon": '"Rectangle"',
            "TOScale": "1",
            "TODistanceFade0": "14000",
            "TODistanceDisappear0": "12000",
            "TODistanceFade1": "5500",
            "TODistanceDisappear1": "5000",
            "TODistanceFade2": "12000",
            "TODistanceDisappear2": "35000",
            "TOGroupScale": "1",
            "TOGroupMergeSize": "0",
        },
        "functions": [],
    },
    "Overlays": {
        "variables": {
            "mouseOverMinFadeSize": "0.085",
            "mouseOverMaxFadeSize": "0.15",
            "healthBarStyle": "2",
            "SMRepresentation": '"Mesh"',
            "SMHighlightDistMin": "20000",
            "SMHighlightDistMax": "25000",
            "hideNormalAttackUICooldown": "1",
        },
        "functions": [],
    },
    "Non linear Scaling": {
        "variables": {
            "nlips": "0",
            "nlipsRange": "10000",
            "nlipsFar": "0",
            "nlipsFarRange": "0",
        },
        "functions": [],
    },
    "Rendering": {
        "variables": {
            "meshRenderLimit": "21000",
            "dotRenderLimit": "10",
            "visibleInSecondary": "1",
            "goblinsStartFade": "3200",
            "goblinsOff": "3200",
            "minimumZoomFactor": "0.5",
        },
        "functions": [],
    },
    "Level of Detail": {
        "variables": {"upLOD": "6150", "downLOD": "6165"},
        "functions": [],
    },
    "Selection": {
        "variables": {
            "selectionLimit": "150000",
            "preciseSelectionLimit": "7500",
            "preciseATILimit": "0",
            "selectionPriority": "75",
            "militaryUnit": "0",
        },
        "functions": [],
    },
    "Abilities": {
        "variables": {},
        "functions": [
            {"name": "addAbility", "args": ["MoveCommand", "1", "0"]},
            {"name": "addAbility", "args": ["CanDock", "1", "0"]},
            {"name": "addAbility", "args": ['CanLaunch"']},
            {
                "name": "addAbility",
                "args": [
                    "ShipHold",
                    "1",
                    "1000",
                    "20",
                    "rallypoint",
                    "Fighter, Bomber, Utility",
                    "200",
                ],
            },
            {"name": "addAbility", "args": ["ParadeCommand", "1"]},
            {"name": "addAbility", "args": ['WaypointMove"']},
            {
                "name": "addAbility",
                "args": ["HyperSpaceCommand", "1", "1", "875", "1750", "0", "3"],
            },
            {
                "name": "addAbility",
                "args": [
                    "CanAttack",
                    "1",
                    "1",
                    "0",
                    "1",
                    "0.35",
                    "1.5",
                    "Capturer,Frigate,SmallCapitalShip,BigCapitalShip,Mothership,Utility,,,,,Corvette, Corvette_hw1,Fighter, Fighter_hw1",
                    "Frontal",
                    '{ Fighter = "MoveToTargetAndShoot" }',
                    '{ Fighter_hw1 = "MoveToTargetAndShoot" }',
                    '{ Corvette = "MoveToTargetAndShoot" }',
                    '{ Corvette_hw1 = "MoveToTargetAndShoot" }',
                    '{ Munition = "MoveToTargetAndShoot" }',
                    '{ Subsystem = "Frontal" }',
                ],
            },
            {"name": "addAbility", "args": ["GuardCommand", "1", "3000", "1000"]},
            {
                "name": "addAbility",
                "args": [
                    "CanBuildShips",
                    "1",
                    "Fighter_Ter, Bomber_Ter, Cruiser_Ter, SuperCap_Ter, Utility_Ter, Platform_Ter, Battlecruiser_Ter, Shipyard_Ter, Probe_Ter",
                    "Utility, Fighter, Bomber, Cruiser, Capital, Platform",
                ],
            },
            {"name": "addAbility", "args": ["CanBeCaptured", "180", "0.5", 'CapCap"']},
            {"name": "addAbility", "args": ["CanBeRepaired", 'RepCap"']},
            {"name": "addAbility", "args": ["RetireAbility", "1", "1"]},
        ],
    },
    "Docking": {
        "variables": {
            "dockTimeBetweenTwoFormations": "1",
            "dockTimeBeforeStart": "2",
            "dockNrOfShipsInDockFormation": "1",
            "dockFormation": '"delta"',
            "queueFormation": '"dockline"',
            "dontDockWithOtherRaceShips": "1",
            "ignoreRaceWhenDocking": "0",
        },
        "functions": [],
    },
    "Launching": {
        "variables": {
            "launchTimeBetweenTwoFormations": "1",
            "launchTimeBeforeStart": "2",
            "launchNrOfShipsInDockFormation": "1",
            "launchFormation": '"delta"',
        },
        "functions": [],
    },
    "Custom Code": {
        "variables": {},
        "functions": [
            {
                "name": "addCustomCode",
                "args": [
                    "data:scripts/custom_scripts/add_nameplate.lua",
                    "onLoad",
                    "onCreate",
                    "updateNameplate",
                    "onDestroy",
                    "gta_hecate",
                    "1",
                ],
            }
        ],
    },
    "Load Model": {
        "variables": {},
        "functions": [{"name": "LoadModel", "args": ["1"]}],
    },
    "Weapons": {
        "variables": {},
        "functions": [
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_longrangeflak_turret", "Weapon_Turret01", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["beam_AABlue", "Weapon_Turret02", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terlaser_gimble", "Weapon_Turret03", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_longrangeflak_turret", "Weapon_Turret04", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_longrangeflak_turret", "Weapon_Turret05", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_longrangeflak_turret", "Weapon_Turret06", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_longrangeflak_turret", "Weapon_Turret07", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_longrangeflak_turret", "Weapon_Turret08", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["beam_AABlue", "Weapon_Turret09", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terlaser_gimble", "Weapon_Turret10", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terlaser_gimble", "Weapon_Turret11", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["beam_AABlue", "Weapon_Turret12", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["beam_AABlue", "Weapon_Turret13", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terlaser_gimble", "Weapon_Turret14", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terlaser_gimble", "Weapon_Turret15", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_terlaser_gimble", "Weapon_Turret16", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_flak_turret", "Weapon_Turret17", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_flak_turret", "Weapon_Turret18", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["beam_AABlue", "Weapon_Turret19", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["beam_AABlue", "Weapon_Turret21", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_flak_turret", "Weapon_Turret23", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_flak_turret", "Weapon_Turret25", ""],
            },
        ],
    },
    "Shields": {
        "variables": {},
        "functions": [{"name": "addShield", "args": ["EMP", "10000", "20"]}],
    },
    "HardPoints": {
        "variables": {},
        "functions": [
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Bgreen1",
                    "Weapon_Turret20",
                    "Weapon",
                    "Innate",
                    "Damageable",
                    "ter_hecatebgreen",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Sgreen1",
                    "Weapon_Turret22",
                    "Weapon",
                    "Innate",
                    "Damageable",
                    "ter_hecateslash",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Sgreen2",
                    "Weapon_Turret24",
                    "Weapon",
                    "Innate",
                    "Damageable",
                    "ter_hecateslash",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Sgreen3",
                    "Weapon_Turret26",
                    "Weapon",
                    "Innate",
                    "Damageable",
                    "ter_hecateslash",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Sgreen4",
                    "Weapon_Turret27",
                    "Weapon",
                    "Innate",
                    "Damageable",
                    "ter_hecateslash",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Nameplate",
                    "Hardpoint_Nameplate",
                    "System",
                    "Innate",
                    "Indestructible",
                    "",
                    "ter_hecate_nameplate_aquitaine",
                    "ter_hecate_nameplate_hood",
                    "ter_hecate_nameplate_meridian",
                    "ter_hecate_nameplate_morgain",
                    "ter_hecate_nameplate_phonecia",
                    "ter_hecate_nameplate_requiem",
                    "ter_hecate_nameplate_tempest",
                    "ter_hecate_nameplate_warlock",
                ],
            },
        ],
    },
    "Debris": {"variables": {}, "functions": []},
    "Engines": {
        "variables": {"trailLinger": "2"},
        "functions": [
            {
                "name": "setEngineBurn",
                "args": ["7", "0.5", "4", "90", "0", "0.7", "0.1", "800"],
            },
        ],
    },
    "Addendum": {
        "variables": {},
        "functions": [
            {
                "name": "loadShipPatchList",
                "args": ["data:sound/sfx/ship/", "0", "", "", "1", "TerranCapital", ""],
            }
        ],
    },
    "Latch Points": {
        "variables": {},
        "functions": [
            {
                "name": "loadLatchPointList",
                "args": [
                    "CapCap",
                    "CapturePoint1",
                    "CapturePoint2",
                    "CapturePoint3",
                    'CapturePoint4"',
                    'CapturePoint5"',
                ],
            },
            {
                "name": "loadLatchPointList",
                "args": [
                    "RepCap",
                    "RepairPoint0",
                    "RepairPoint1",
                    "RepairPoint2",
                    "RepairPoint3",
                    'RepairPoint4"',
                    'RepairPoint5"',
                ],
            },
        ],
    },
    "Scuttle": {
        "variables": {
            "minFalloffDamageDist": "450",
            "maxFalloffDamageDist": "450*1.5",
            "maxFalloffScuttleDamageDist": "450*3",
            "explosiveScuttleDamageOnDeath": "1960",
            "maxFalloffForce": "500*10",
            "explosiveDamageOnDeath": "275",
            "radiusDamageEvadeMod": "1.1",
        },
        "functions": [],
    },
}
