TER_ATHENA = {
    "Ship info": {
        "variables": {
            "displayedName": '"GTB Athena"',
            "sobDescription": '"Light Bomber"',
        },
        "functions": [],
    },
    "Health and Armour": {
        "variables": {
            "maxhealth": "250",
            "regentime": "0",
            "minRegenTime": "0",
            "sideArmourDamage": 'getShipNum(NewShipType, "sideArmourDamage", 1.0)',
            "rearArmourDamage": 'getShipNum(NewShipType, "rearArmourDamage", 1.0)',
        },
        "functions": [],
    },
    "Supply": {
        "variables": {},
        "functions": [
            {"name": "setSupplyValue", "args": ["Bomber", "3.0"]},
        ],
    },
    "Tactics And Multipliers": {
        "variables": {"defaultROE": '"Defensive"', "defaultStance": '"Aggressive"'},
        "functions": [
            {"name": "setTacticsMults", "args": ["MAXSPEED", "0.90", "1.10", "1.0"]},
            {"name": "setTacticsMults", "args": ["ENGINEACCEL", "1.20", "0.80", "1.0"]},
            {"name": "setTacticsMults", "args": ["ENGINEBRAKE", "1.0", "1.0", "1.0"]},
            {"name": "setTacticsMults", "args": ["THRUSTER", "1.0", "1.0", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["THRUSTERACCEL", "1.20", "0.80", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["THRUSTERBRAKE", "1.0", "1.0", "1.0"]},
            {"name": "setTacticsMults", "args": ["ROTATION", "1.0", "1.10", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["ROTATIONACCEL", "1.0", "1.10", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["ROTATIONBRAKE", "1.0", "1.0", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["WEAPONACCURACY", "1.0", "1.0", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["WEAPONDAMAGE", "1.20", "1.0", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["DAMAGEAPPLIED", "1.10", "0.90", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["FIRERATE", "1.0", "1.25", "1.0"]},
        ],
    },
    "Main Ship Data": {"variables": {"isTransferable": "1"}, "functions": []},
    "Advanced Movement": {
        "variables": {
            "useEngagementRanges": "0",
            "thrusterUsage": "0.25",
            "accelerationAngle": "170",
            "mirrorAngle": "30",
            "secondaryTurnAngle": "90",
            "maxBankingAmount": "85",
            "descendPitch": "0",
            "goalReachEpsilon": "5",
            "slideMoveRange": "0",
            "controllerType": '"Ship"',
            "relativeMoveFactor": "6",
        },
        "functions": [],
    },
    "Formations": {
        "variables": {
            "SquadronSize": "3",
            "formationSpacing": "60",
            "batchFormation": '"Batch_delta"',
            "strikeGroupRadius": "25",
        },
        "functions": [],
    },
    "Movement": {
        "variables": {
            "mass": "340",
            "thrusterMaxSpeed": "270",
            "mainEngineMaxSpeed": "270",
            "rotationMaxSpeed": "80",
            "thrusterAccelTime": "4",
            "thrusterBrakeTime": "2",
            "mainEngineAccelTime": "4",
            "mainEngineBrakeTime": "2",
            "rotationAccelTime": "0.6",
            "rotationBrakeTime": "0.3",
        },
        "functions": [],
    },
    "Damage & Death": {
        "variables": {
            "collisionMultiplier": "3",
            "dustCloudDamageTime": "160",
            "nebulaDamageTime": "100",
            "battleScarCoverage": "1",
            "sobDieTime": "1",
            "sobSpecialDieTime": "1",
            "specialDeathSpeed": "40",
            "chanceOfSpecialDeath": "0",
            "deadSobFadeTime": "1",
        },
        "functions": [],
    },
    "Death Tumble": {
        "variables": {
            "tumbleStaticX": "10",
            "tumbleStaticY": "20",
            "tumbleStaticZ": "5",
            "tumbleDynamicX": "2",
            "tumbleDynamicY": "10",
            "tumbleDynamicZ": "5",
            "tumbleSpecialDynamicX": "800",
            "tumbleSpecialDynamicY": "1000",
            "tumbleSpecialDynamicZ": "700",
        },
        "functions": [],
    },
    "Swaying": {
        "variables": {
            "swayUpdateTime": "2",
            "swayOffsetRandomX": "10",
            "swayOffsetRandomY": "10",
            "swayOffsetRandomZ": "10",
            "swayBobbingFactor": "0.05",
            "swayRotateFactor": "0.1",
        },
        "functions": [],
    },
    "Families": {
        "variables": {
            "MinimalFamilyToFindPathAround": '"SuperCap"',
            "BuildFamily": '"Bomber_Ter"',
            "AttackFamily": '"Fighter"',
            "DockFamily": '"Fighter"',
            "AvoidanceFamily": '"Strikecraft"',
            "DisplayFamily": '"Bomber"',
            "AutoFormationFamily": '"Fighter"',
            "CollisionFamily": '"Small"',
            "ArmourFamily": 'getShipStr(NewShipType, "ArmourFamily", "LightArmour")',
            "CombatFamily": '"Fighter_Bomber"',
        },
        "functions": [],
    },
    "Special Flight Maneuvers": {
        "variables": {
            "mirrorAboveManeuver": '"ImmelMann_speedy, OneEightyDegRightTurn, OneEightyDegLeftTurn, ImmelMann_speedy, ImmelMann_speedy, ImmelMann_speedy"',
            "mirrorBelowManeuver": '"Split_S_speedy, OneEightyDegRightTurn, OneEightyDegLeftTurn, Split_S_speedy, Split_S_speedy, Split_S_speedy"',
            "specialTurnLeftManeuver": '"NinetyDegLeftTurn, None, None"',
            "specialTurnRightManeuver": '"NinetyDegRightTurn, None, None"',
        },
        "functions": [],
    },
    "Ship Counter Rating": {
        "variables": {
            "fighterValue": "0",
            "corvetteValue": "8",
            "frigateValue": "0",
            "neutralValue": "0",
            "antiFighterValue": "0",
            "antiCorvetteValue": "0",
            "antiFrigateValue": "8",
            "totalValue": "8",
        },
        "functions": [],
    },
    "Construction": {
        "variables": {
            "buildBatch": "3",
            "buildCost": "490",
            "buildTime": "31",
            "buildPriorityOrder": "20",
        },
        "functions": [],
    },
    "Sensors": {
        "variables": {
            "retaliationRange": "5500",
            "retaliationDistanceFromGoal": "160",
            "visualRange": "2000",
            "prmSensorRange": "4000",
            "secSensorRange": "10000",
            "detectionStrength": "1",
        },
        "functions": [],
    },
    "Tactical Overlay Icon": {
        "variables": {
            "TOIcon": '"Square"',
            "TOScale": "1",
            "TODistanceFade0": "7000",
            "TODistanceDisappear0": "5000",
            "TODistanceFade1": "2500",
            "TODistanceDisappear1": "2000",
            "TODistanceFade2": "12000",
            "TODistanceDisappear2": "35000",
            "TOGroupScale": "1.5",
            "TOGroupMergeSize": "0",
        },
        "functions": [],
    },
    "Overlays": {
        "variables": {
            "mouseOverMinFadeSize": "0.045",
            "mouseOverMaxFadeSize": "0.1",
            "healthBarStyle": "0",
            "SMRepresentation": '"HardDot"',
        },
        "functions": [],
    },
    "Non linear Scaling": {
        "variables": {
            "nlips": "0.0008",
            "nlipsRange": "6000",
            "nlipsFar": "0.0003",
            "nlipsFarRange": "10000",
        },
        "functions": [],
    },
    "Rendering": {
        "variables": {
            "meshRenderLimit": "11000",
            "dotRenderLimit": "10",
            "visibleInSecondary": "0",
            "goblinsStartFade": "210",
            "goblinsOff": "210",
            "minimumZoomFactor": "0.68",
        },
        "functions": [],
    },
    "Level of Detail": {"variables": {"minLOD": "0.25"}, "functions": []},
    "Selection": {
        "variables": {
            "selectionLimit": "150000",
            "preciseATILimit": "0",
            "selectionPriority": "75",
            "militaryUnit": "1",
        },
        "functions": [],
    },
    "Abilities": {
        "variables": {},
        "functions": [
            {"name": "addAbility", "args": ["MoveCommand", "1", "0"]},
            {"name": "addAbility", "args": ["CanDock", "1", "1"]},
            {"name": "addAbility", "args": ["CanLaunch"]},
            {
                "name": "addAbility",
                "args": ["HyperSpaceCommand", "0", "1", "30", "120", "0", "3"],
            },
            {"name": "addAbility", "args": ["ParadeCommand", "1"]},
            {"name": "addAbility", "args": ["WaypointMove"]},
            {
                "name": "addAbility",
                "args": [
                    "CanAttack",
                    "1",
                    "1",
                    "1",
                    "0",
                    "0.35",
                    "1.5",
                    "Fighter, Fighter_hw1, Corvette, Corvette_hw1,,,,, Frigate, SmallCapitalShip, BigCapitalShip, Mothership",
                    "FlyBy_Bomber_vs_Frigate",
                    '{Fighter="Bomber_vs_Fighter"}',
                    '{Fighter_hw1="Bomber_vs_Fighter"}',
                    '{Mothership="Bomber_vs_Mothership"}',
                    '{Frigate="Bomber_vs_Frigate"}',
                    '{SmallCapitalShip="Bomber_vs_Corvette"}',
                    '{BigCapitalShip="Bomber_vs_CapShip"}',
                    '{SubSystem="TopAttack_Bomber_vs_Subsystem"}',
                    '{Corvette="Bomber_vs_Corvette"}',
                    '{Corvette_hw1="Bomber_vs_Corvette"}',
                    '{ResourceLarge="Flyby_Bomber_vs_ResourceLarge"}',
                ],
            },
            {"name": "addAbility", "args": ["GuardCommand", "1", "3000", "500"]},
            {"name": "addAbility", "args": ["CanBeRepaired"]},
            {
                "name": "addAbility",
                "args": ["HyperspaceViaGateCommand", "0", "3", ".25", "0"],
            },
            {"name": "addAbility", "args": ["RetireAbility", "1", "0"]},
            {
                "name": "addAbility",
                "args": [
                    "CustomCommand",
                    "1",
                    "Speed Burst",
                    "1",
                    "0",
                    "80",
                    "0",
                    "1",
                    "0.25",
                    "0",
                    "data:scripts/custom_scripts/Afterburner.lua",
                    "Start_Afterburner",
                    "Do_Afterburner",
                    "Finish_Afterburner",
                    "ter_athena",
                    "0.5",
                    "3",
                    "1",
                ],
            },
        ],
    },
    "Docking": {
        "variables": {
            "holdSlots": "3",
            "dockTimeBetweenTwoFormations": "0.5",
            "dockTimeBeforeStart": "0.5",
            "dockNrOfShipsInDockFormation": "1",
            "dockFormation": '"dockline"',
            "queueFormation": '"n_delta"',
            "ignoreRaceWhenDocking": "0",
        },
        "functions": [],
    },
    "Launching": {
        "variables": {
            "launchTimeBetweenTwoFormations": "0.5",
            "launchTimeBeforeStart": "0.5",
            "launchNrOfShipsInDockFormation": "1",
            "launchFormation": '"n_delta"',
        },
        "functions": [],
    },
    "Custom Code": {
        "variables": {},
        "functions": [
            {
                "name": "addCustomCode",
                "args": [
                    "data:scripts/custom_scripts/abfix.lua",
                    "",
                    "",
                    "AfterburnerFix",
                    "",
                    "AfterburnerFix",
                    "10",
                ],
            }
        ],
    },
    "Load Model": {
        "variables": {},
        "functions": [{"name": "LoadModel", "args": ["1"]}],
    },
    "HardPoints": {"variables": {}, "functions": []},
    "Weapons": {
        "variables": {},
        "functions": [
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_avenger", "Weapon_FrontGun", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_disruptorfs1", "Weapon_FrontGun2", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["miss_phoenixv", "Weapon_Bomb1", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["miss_stiletto", "Weapon_Bomb2", ""],
            },
        ],
    },
    "Shields": {
        "variables": {},
        "functions": [{"name": "addShield", "args": ["EMP", "100", "10"]}],
    },
    "Engines": {
        "variables": {},
        "functions": [
            {
                "name": "setEngineBurn",
                "args": ["7", "0.5", "1", "15", "0", "0.7", "0.1", "30"],
            }
        ],
    },
    "Latch Points": {
        "variables": {},
        "functions": [
            {
                "name": "loadLatchPointList",
                "args": [
                    "RepCap",
                    "RepairPoint0",
                ],
            },
        ],
    },
    "Addendum": {
        "variables": {},
        "functions": [
            {
                "name": "loadShipPatchList",
                "args": [
                    "data:sound/sfx/ship/",
                    "0",
                    "",
                    "",
                    "1",
                    "gtb_old",
                    "",
                    "3",
                    "",
                    "Root",
                ],
            }
        ],
    },
}
SHI_NAHEMA = {
    "Ship info": {
        "variables": {
            "displayedName": '"SB Nahema"',
            "sobDescription": '"Light Bomber"',
        },
        "functions": [],
    },
    "Health and Armour": {
        "variables": {
            "maxhealth": "300",
            "regentime": "0",
            "minRegenTime": "0",
            "sideArmourDamage": 'getShipNum(NewShipType, "sideArmourDamage", 1.0)',
            "rearArmourDamage": 'getShipNum(NewShipType, "rearArmourDamage", 1.0)',
        },
        "functions": [],
    },
    "Supply": {
        "variables": {},
        "functions": [
            {"name": "setSupplyValue", "args": ["Bomber", "3.0"]},
        ],
    },
    "Tactics And Multipliers": {
        "variables": {"defaultROE": '"Defensive"', "defaultStance": '"Aggressive"'},
        "functions": [
            {"name": "setTacticsMults", "args": ["MAXSPEED", "0.90", "1.10", "1.0"]},
            {"name": "setTacticsMults", "args": ["ENGINEACCEL", "1.20", "0.80", "1.0"]},
            {"name": "setTacticsMults", "args": ["ENGINEBRAKE", "1.0", "1.0", "1.0"]},
            {"name": "setTacticsMults", "args": ["THRUSTER", "1.0", "1.0", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["THRUSTERACCEL", "1.20", "0.80", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["THRUSTERBRAKE", "1.0", "1.0", "1.0"]},
            {"name": "setTacticsMults", "args": ["ROTATION", "1.0", "1.10", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["ROTATIONACCEL", "1.0", "1.10", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["ROTATIONBRAKE", "1.0", "1.0", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["WEAPONACCURACY", "1.0", "1.0", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["WEAPONDAMAGE", "1.20", "1.0", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["DAMAGEAPPLIED", "1.10", "0.90", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["FIRERATE", "1.0", "1.25", "1.0"]},
        ],
    },
    "Main Ship Data": {"variables": {"isTransferable": "1"}, "functions": []},
    "Advanced Movement": {
        "variables": {
            "useEngagementRanges": "0",
            "thrusterUsage": "0.25",
            "accelerationAngle": "170",
            "mirrorAngle": "30",
            "secondaryTurnAngle": "90",
            "maxBankingAmount": "85",
            "descendPitch": "0",
            "goalReachEpsilon": "5",
            "slideMoveRange": "0",
            "controllerType": '"Ship"',
            "relativeMoveFactor": "6",
        },
        "functions": [],
    },
    "Formations": {
        "variables": {
            "SquadronSize": "3",
            "formationSpacing": "60",
            "batchFormation": '"Batch_delta"',
            "strikeGroupRadius": "25",
        },
        "functions": [],
    },
    "Movement": {
        "variables": {
            "mass": "600",
            "thrusterMaxSpeed": "324",
            "mainEngineMaxSpeed": "324",
            "rotationMaxSpeed": "60",
            "thrusterAccelTime": "2.5",
            "thrusterBrakeTime": "2",
            "mainEngineAccelTime": "2.5",
            "mainEngineBrakeTime": "2",
            "rotationAccelTime": "0.9",
            "rotationBrakeTime": "0.45",
        },
        "functions": [],
    },
    "Damage & Death": {
        "variables": {
            "collisionMultiplier": "3",
            "dustCloudDamageTime": "160",
            "nebulaDamageTime": "100",
            "battleScarCoverage": "1",
            "sobDieTime": "1",
            "sobSpecialDieTime": "1",
            "specialDeathSpeed": "40",
            "chanceOfSpecialDeath": "0",
            "deadSobFadeTime": "1",
        },
        "functions": [],
    },
    "Death Tumble": {
        "variables": {
            "tumbleStaticX": "10",
            "tumbleStaticY": "20",
            "tumbleStaticZ": "5",
            "tumbleDynamicX": "2",
            "tumbleDynamicY": "10",
            "tumbleDynamicZ": "5",
            "tumbleSpecialDynamicX": "800",
            "tumbleSpecialDynamicY": "1000",
            "tumbleSpecialDynamicZ": "700",
        },
        "functions": [],
    },
    "Swaying": {
        "variables": {
            "swayUpdateTime": "2",
            "swayOffsetRandomX": "10",
            "swayOffsetRandomY": "10",
            "swayOffsetRandomZ": "10",
            "swayBobbingFactor": "0.05",
            "swayRotateFactor": "0.1",
        },
        "functions": [],
    },
    "Families": {
        "variables": {
            "MinimalFamilyToFindPathAround": '"SuperCap"',
            "BuildFamily": '"Bomber_Shi"',
            "AttackFamily": '"Fighter"',
            "DockFamily": '"Fighter"',
            "AvoidanceFamily": '"Strikecraft"',
            "DisplayFamily": '"Bomber"',
            "AutoFormationFamily": '"Fighter"',
            "CollisionFamily": '"Small"',
            "ArmourFamily": 'getShipStr(NewShipType, "ArmourFamily", "LightArmour")',
            "CombatFamily": '"Fighter_Bomber"',
        },
        "functions": [],
    },
    "Special Flight Maneuvers": {
        "variables": {
            "mirrorAboveManeuver": '"ImmelMann_speedy, OneEightyDegRightTurn, OneEightyDegLeftTurn, ImmelMann_speedy, ImmelMann_speedy, ImmelMann_speedy"',
            "mirrorBelowManeuver": '"Split_S_speedy, OneEightyDegRightTurn, OneEightyDegLeftTurn, Split_S_speedy, Split_S_speedy, Split_S_speedy"',
            "specialTurnLeftManeuver": '"NinetyDegLeftTurn, None, None"',
            "specialTurnRightManeuver": '"NinetyDegRightTurn, None, None"',
        },
        "functions": [],
    },
    "Ship Counter Rating": {
        "variables": {
            "fighterValue": "0",
            "corvetteValue": "8",
            "frigateValue": "0",
            "neutralValue": "0",
            "antiFighterValue": "0",
            "antiCorvetteValue": "0",
            "antiFrigateValue": "8",
            "totalValue": "8",
        },
        "functions": [],
    },
    "Construction": {
        "variables": {
            "buildBatch": "3",
            "buildCost": "550",
            "buildTime": "34",
            "buildPriorityOrder": "20",
        },
        "functions": [],
    },
    "Sensors": {
        "variables": {
            "retaliationRange": "5500",
            "retaliationDistanceFromGoal": "160",
            "visualRange": "2000",
            "prmSensorRange": "4000",
            "secSensorRange": "10000",
            "detectionStrength": "1",
        },
        "functions": [],
    },
    "Tactical Overlay Icon": {
        "variables": {
            "TOIcon": '"Square"',
            "TOScale": "1",
            "TODistanceFade0": "7000",
            "TODistanceDisappear0": "5000",
            "TODistanceFade1": "2500",
            "TODistanceDisappear1": "2000",
            "TODistanceFade2": "12000",
            "TODistanceDisappear2": "35000",
            "TOGroupScale": "1.5",
            "TOGroupMergeSize": "0",
        },
        "functions": [],
    },
    "Overlays": {
        "variables": {
            "mouseOverMinFadeSize": "0.045",
            "mouseOverMaxFadeSize": "0.1",
            "healthBarStyle": "0",
            "SMRepresentation": '"HardDot"',
        },
        "functions": [],
    },
    "Non linear Scaling": {
        "variables": {
            "nlips": "0.0008",
            "nlipsRange": "6000",
            "nlipsFar": "0.0003",
            "nlipsFarRange": "10000",
        },
        "functions": [],
    },
    "Rendering": {
        "variables": {
            "meshRenderLimit": "11000",
            "dotRenderLimit": "10",
            "visibleInSecondary": "0",
            "goblinsStartFade": "210",
            "goblinsOff": "210",
            "minimumZoomFactor": "0.68",
        },
        "functions": [],
    },
    "Level of Detail": {"variables": {"minLOD": "0.25"}, "functions": []},
    "Selection": {
        "variables": {
            "selectionLimit": "150000",
            "preciseATILimit": "0",
            "selectionPriority": "75",
            "militaryUnit": "1",
        },
        "functions": [],
    },
    "Abilities": {
        "variables": {},
        "functions": [
            {"name": "addAbility", "args": ["MoveCommand", "1", "0"]},
            {"name": "addAbility", "args": ["CanDock", "1", "1"]},
            {"name": "addAbility", "args": ["CanLaunch"]},
            {
                "name": "addAbility",
                "args": ["HyperSpaceCommand", "0", "1", "30", "120", "0", "3"],
            },
            {"name": "addAbility", "args": ["ParadeCommand", "1"]},
            {"name": "addAbility", "args": ["WaypointMove"]},
            {
                "name": "addAbility",
                "args": [
                    "CanAttack",
                    "1",
                    "1",
                    "1",
                    "0",
                    "0.35",
                    "1.5",
                    "Fighter, Fighter_hw1, Corvette, Corvette_hw1,,,,, Frigate, SmallCapitalShip, BigCapitalShip, Mothership",
                    "FlyBy_Bomber_vs_Frigate",
                    '{Fighter="Bomber_vs_Fighter"}',
                    '{Fighter_hw1="Bomber_vs_Fighter"}',
                    '{Mothership="Bomber_vs_Mothership"}',
                    '{Frigate="Bomber_vs_Frigate"}',
                    '{SmallCapitalShip="Bomber_vs_Corvette"}',
                    '{BigCapitalShip="Bomber_vs_CapShip"}',
                    '{SubSystem="TopAttack_Bomber_vs_Subsystem"}',
                    '{Corvette="Bomber_vs_Corvette"}',
                    '{Corvette_hw1="Bomber_vs_Corvette"}',
                    '{ResourceLarge="Flyby_Bomber_vs_ResourceLarge"}',
                ],
            },
            {"name": "addAbility", "args": ["GuardCommand", "1", "3000", "500"]},
            {
                "name": "addAbility",
                "args": ["HyperspaceViaGateCommand", "0", "3", ".25", "0"],
            },
            {"name": "addAbility", "args": ["RetireAbility", "1", "0"]},
            {
                "name": "addAbility",
                "args": [
                    "CustomCommand",
                    "1",
                    "Speed Burst",
                    "1",
                    "0",
                    "80",
                    "0",
                    "1",
                    "0.25",
                    "0",
                    "data:scripts/custom_scripts/Afterburner.lua",
                    "Start_Afterburner",
                    "Do_Afterburner",
                    "Finish_Afterburner",
                    "shi_nahema",
                    "0.5",
                    "3",
                    "1",
                ],
            },
        ],
    },
    "Docking": {
        "variables": {
            "holdSlots": "3",
            "dockTimeBetweenTwoFormations": "0.5",
            "dockTimeBeforeStart": "0.5",
            "dockNrOfShipsInDockFormation": "1",
            "dockFormation": '"dockline"',
            "queueFormation": '"n_delta"',
            "ignoreRaceWhenDocking": "0",
        },
        "functions": [],
    },
    "Launching": {
        "variables": {
            "launchTimeBetweenTwoFormations": "0.5",
            "launchTimeBeforeStart": "0.5",
            "launchNrOfShipsInDockFormation": "1",
            "launchFormation": '"n_delta"',
        },
        "functions": [],
    },
    "Custom Code": {
        "variables": {},
        "functions": [
            {
                "name": "addCustomCode",
                "args": [
                    "data:scripts/custom_scripts/abfix.lua",
                    "",
                    "",
                    "AfterburnerFix",
                    "",
                    "AfterburnerFix",
                    "10",
                ],
            }
        ],
    },
    "Load Model": {
        "variables": {},
        "functions": [{"name": "LoadModel", "args": ["1"]}],
    },
    "HardPoints": {"variables": {}, "functions": []},
    "Weapons": {
        "variables": {},
        "functions": [
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_shivmegalaser", "Weapon_Gun1", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["miss_infyrno", "Weapon_Bomb1", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["miss_hornet", "Weapon_Bomb2", ""],
            },
        ],
    },
    "Shields": {
        "variables": {},
        "functions": [{"name": "addShield", "args": ["EMP", "100", "10"]}],
    },
    "Engines": {
        "variables": {},
        "functions": [
            {
                "name": "setEngineBurn",
                "args": ["7", "0.5", "1", "15", "0", "0.7", "0.1", "30"],
            }
        ],
    },
    "Addendum": {
        "variables": {},
        "functions": [
            {
                "name": "loadShipPatchList",
                "args": [
                    "data:sound/sfx/ship/",
                    "0",
                    "",
                    "",
                    "1",
                    "ShivanBomber",
                    "",
                    "3",
                    "",
                    "Root",
                ],
            }
        ],
    },
}
SHI_SHAITAN = {
    "Ship info": {
        "variables": {
            "displayedName": '"SB Shaitan"',
            "sobDescription": '"Light Bomber"',
        },
        "functions": [],
    },
    "Health and Armour": {
        "variables": {
            "maxhealth": "400",
            "regentime": "0",
            "minRegenTime": "0",
            "sideArmourDamage": 'getShipNum(NewShipType, "sideArmourDamage", 1.0)',
            "rearArmourDamage": 'getShipNum(NewShipType, "rearArmourDamage", 1.0)',
        },
        "functions": [],
    },
    "Supply": {
        "variables": {},
        "functions": [
            {"name": "setSupplyValue", "args": ["Bomber", "3.0"]},
        ],
    },
    "Tactics And Multipliers": {
        "variables": {"defaultROE": '"Defensive"', "defaultStance": '"Aggressive"'},
        "functions": [
            {"name": "setTacticsMults", "args": ["MAXSPEED", "0.90", "1.10", "1.0"]},
            {"name": "setTacticsMults", "args": ["ENGINEACCEL", "1.20", "0.80", "1.0"]},
            {"name": "setTacticsMults", "args": ["ENGINEBRAKE", "1.0", "1.0", "1.0"]},
            {"name": "setTacticsMults", "args": ["THRUSTER", "1.0", "1.0", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["THRUSTERACCEL", "1.20", "0.80", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["THRUSTERBRAKE", "1.0", "1.0", "1.0"]},
            {"name": "setTacticsMults", "args": ["ROTATION", "1.0", "1.10", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["ROTATIONACCEL", "1.0", "1.10", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["ROTATIONBRAKE", "1.0", "1.0", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["WEAPONACCURACY", "1.0", "1.0", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["WEAPONDAMAGE", "1.20", "1.0", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["DAMAGEAPPLIED", "1.10", "0.90", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["FIRERATE", "1.0", "1.25", "1.0"]},
        ],
    },
    "Main Ship Data": {"variables": {"isTransferable": "1"}, "functions": []},
    "Advanced Movement": {
        "variables": {
            "useEngagementRanges": "0",
            "thrusterUsage": "0.5",
            "accelerationAngle": "170",
            "mirrorAngle": "30",
            "secondaryTurnAngle": "90",
            "maxBankingAmount": "85",
            "descendPitch": "0",
            "goalReachEpsilon": "5",
            "slideMoveRange": "0",
            "controllerType": '"Ship"',
            "relativeMoveFactor": "6",
        },
        "functions": [],
    },
    "Formations": {
        "variables": {
            "SquadronSize": "3",
            "formationSpacing": "60",
            "batchFormation": '"Batch_delta"',
            "strikeGroupRadius": "25",
        },
        "functions": [],
    },
    "Movement": {
        "variables": {
            "mass": "500",
            "thrusterMaxSpeed": "264",
            "mainEngineMaxSpeed": "264",
            "rotationMaxSpeed": "90",
            "thrusterAccelTime": "4",
            "thrusterBrakeTime": "2",
            "mainEngineAccelTime": "4",
            "mainEngineBrakeTime": "2",
            "rotationAccelTime": "0.6",
            "rotationBrakeTime": "0.3",
        },
        "functions": [],
    },
    "Damage & Death": {
        "variables": {
            "collisionMultiplier": "3",
            "dustCloudDamageTime": "160",
            "nebulaDamageTime": "100",
            "battleScarCoverage": "1",
            "sobDieTime": "1",
            "sobSpecialDieTime": "1",
            "specialDeathSpeed": "40",
            "chanceOfSpecialDeath": "0",
            "deadSobFadeTime": "1",
        },
        "functions": [],
    },
    "Death Tumble": {
        "variables": {
            "tumbleStaticX": "10",
            "tumbleStaticY": "20",
            "tumbleStaticZ": "5",
            "tumbleDynamicX": "2",
            "tumbleDynamicY": "10",
            "tumbleDynamicZ": "5",
            "tumbleSpecialDynamicX": "800",
            "tumbleSpecialDynamicY": "1000",
            "tumbleSpecialDynamicZ": "700",
        },
        "functions": [],
    },
    "Swaying": {
        "variables": {
            "swayUpdateTime": "2",
            "swayOffsetRandomX": "10",
            "swayOffsetRandomY": "10",
            "swayOffsetRandomZ": "10",
            "swayBobbingFactor": "0.05",
            "swayRotateFactor": "0.1",
        },
        "functions": [],
    },
    "Families": {
        "variables": {
            "MinimalFamilyToFindPathAround": '"SuperCap"',
            "BuildFamily": '"Bomber_Shi"',
            "AttackFamily": '"Fighter"',
            "DockFamily": '"Fighter"',
            "AvoidanceFamily": '"Strikecraft"',
            "DisplayFamily": '"Bomber"',
            "AutoFormationFamily": '"Fighter"',
            "CollisionFamily": '"Small"',
            "ArmourFamily": 'getShipStr(NewShipType, "ArmourFamily", "LightArmour")',
            "CombatFamily": '"Fighter_Bomber"',
        },
        "functions": [],
    },
    "Special Flight Maneuvers": {
        "variables": {
            "mirrorAboveManeuver": '"ImmelMann_speedy, OneEightyDegRightTurn, OneEightyDegLeftTurn, ImmelMann_speedy, ImmelMann_speedy, ImmelMann_speedy"',
            "mirrorBelowManeuver": '"Split_S_speedy, OneEightyDegRightTurn, OneEightyDegLeftTurn, Split_S_speedy, Split_S_speedy, Split_S_speedy"',
            "specialTurnLeftManeuver": '"NinetyDegLeftTurn, None, None"',
            "specialTurnRightManeuver": '"NinetyDegRightTurn, None, None"',
        },
        "functions": [],
    },
    "Ship Counter Rating": {
        "variables": {
            "fighterValue": "0",
            "corvetteValue": "8",
            "frigateValue": "0",
            "neutralValue": "0",
            "antiFighterValue": "0",
            "antiCorvetteValue": "0",
            "antiFrigateValue": "8",
            "totalValue": "8",
        },
        "functions": [],
    },
    "Construction": {
        "variables": {
            "buildBatch": "3",
            "buildCost": "830",
            "buildTime": "48",
            "buildPriorityOrder": "20",
        },
        "functions": [],
    },
    "Sensors": {
        "variables": {
            "retaliationRange": "5500",
            "retaliationDistanceFromGoal": "160",
            "visualRange": "2000",
            "prmSensorRange": "4000",
            "secSensorRange": "10000",
            "detectionStrength": "1",
        },
        "functions": [],
    },
    "Tactical Overlay Icon": {
        "variables": {
            "TOIcon": '"Square"',
            "TOScale": "1",
            "TODistanceFade0": "7000",
            "TODistanceDisappear0": "5000",
            "TODistanceFade1": "2500",
            "TODistanceDisappear1": "2000",
            "TODistanceFade2": "12000",
            "TODistanceDisappear2": "35000",
            "TOGroupScale": "1.5",
            "TOGroupMergeSize": "0",
        },
        "functions": [],
    },
    "Overlays": {
        "variables": {
            "mouseOverMinFadeSize": "0.045",
            "mouseOverMaxFadeSize": "0.1",
            "healthBarStyle": "0",
            "SMRepresentation": '"HardDot"',
        },
        "functions": [],
    },
    "Non linear Scaling": {
        "variables": {
            "nlips": "0.0008",
            "nlipsRange": "6000",
            "nlipsFar": "0.0003",
            "nlipsFarRange": "10000",
        },
        "functions": [],
    },
    "Rendering": {
        "variables": {
            "meshRenderLimit": "11000",
            "dotRenderLimit": "10",
            "visibleInSecondary": "0",
            "goblinsStartFade": "210",
            "goblinsOff": "210",
            "minimumZoomFactor": "0.68",
        },
        "functions": [],
    },
    "Level of Detail": {"variables": {"minLOD": "0.25"}, "functions": []},
    "Selection": {
        "variables": {
            "selectionLimit": "150000",
            "preciseATILimit": "0",
            "selectionPriority": "75",
            "militaryUnit": "1",
        },
        "functions": [],
    },
    "Abilities": {
        "variables": {},
        "functions": [
            {"name": "addAbility", "args": ["MoveCommand", "1", "0"]},
            {"name": "addAbility", "args": ["CanDock", "1", "1"]},
            {"name": "addAbility", "args": ["CanLaunch"]},
            {
                "name": "addAbility",
                "args": ["HyperSpaceCommand", "0", "1", "30", "120", "0", "3"],
            },
            {"name": "addAbility", "args": ["ParadeCommand", "1"]},
            {"name": "addAbility", "args": ["WaypointMove"]},
            {
                "name": "addAbility",
                "args": [
                    "CanAttack",
                    "1",
                    "1",
                    "1",
                    "0",
                    "0.35",
                    "1.5",
                    "Fighter, Fighter_hw1, Corvette, Corvette_hw1,,,,, Frigate, SmallCapitalShip, BigCapitalShip, Mothership",
                    "FlyBy_Bomber_vs_Frigate",
                    '{Fighter="Bomber_vs_Fighter"}',
                    '{Fighter_hw1="Bomber_vs_Fighter"}',
                    '{Mothership="Bomber_vs_Mothership"}',
                    '{Frigate="Bomber_vs_Frigate"}',
                    '{SmallCapitalShip="Bomber_vs_Corvette"}',
                    '{BigCapitalShip="Bomber_vs_CapShip"}',
                    '{SubSystem="TopAttack_Bomber_vs_Subsystem"}',
                    '{Corvette="Bomber_vs_Corvette"}',
                    '{Corvette_hw1="Bomber_vs_Corvette"}',
                    '{ResourceLarge="Flyby_Bomber_vs_ResourceLarge"}',
                ],
            },
            {"name": "addAbility", "args": ["GuardCommand", "1", "3000", "500"]},
            {
                "name": "addAbility",
                "args": ["HyperspaceViaGateCommand", "0", "3", ".25", "0"],
            },
            {"name": "addAbility", "args": ["RetireAbility", "1", "0"]},
            {
                "name": "addAbility",
                "args": [
                    "CustomCommand",
                    "1",
                    "Speed Burst",
                    "1",
                    "0",
                    "80",
                    "0",
                    "1",
                    "0.25",
                    "0",
                    "data:scripts/custom_scripts/Afterburner.lua",
                    "Start_Afterburner",
                    "Do_Afterburner",
                    "Finish_Afterburner",
                    "shi_shaitan",
                    "0.5",
                    "3",
                    "1",
                ],
            },
        ],
    },
    "Docking": {
        "variables": {
            "holdSlots": "3",
            "dockTimeBetweenTwoFormations": "0.5",
            "dockTimeBeforeStart": "0.5",
            "dockNrOfShipsInDockFormation": "1",
            "dockFormation": '"dockline"',
            "queueFormation": '"n_delta"',
            "ignoreRaceWhenDocking": "0",
        },
        "functions": [],
    },
    "Launching": {
        "variables": {
            "launchTimeBetweenTwoFormations": "0.5",
            "launchTimeBeforeStart": "0.5",
            "launchNrOfShipsInDockFormation": "1",
            "launchFormation": '"n_delta"',
        },
        "functions": [],
    },
    "Custom Code": {
        "variables": {},
        "functions": [
            {
                "name": "addCustomCode",
                "args": [
                    "data:scripts/custom_scripts/abfix.lua",
                    "",
                    "",
                    "AfterburnerFix",
                    "",
                    "AfterburnerFix",
                    "10",
                ],
            }
        ],
    },
    "Load Model": {
        "variables": {},
        "functions": [{"name": "LoadModel", "args": ["1"]}],
    },
    "HardPoints": {"variables": {}, "functions": []},
    "Weapons": {
        "variables": {},
        "functions": [
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_shivheavylaser", "Weapon_Gun1", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["gun_disruptorfs1", "Weapon_Gun2", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["miss_shivbomb", "Weapon_Bomb1", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["miss_stiletto", "Weapon_Bomb2", ""],
            },
        ],
    },
    "Shields": {
        "variables": {},
        "functions": [{"name": "addShield", "args": ["EMP", "100", "10"]}],
    },
    "Engines": {
        "variables": {},
        "functions": [
            {
                "name": "setEngineBurn",
                "args": ["7", "0.5", "1", "15", "0", "0.7", "0.1", "30"],
            }
        ],
    },
    "Addendum": {
        "variables": {},
        "functions": [
            {
                "name": "loadShipPatchList",
                "args": [
                    "data:sound/sfx/ship/",
                    "0",
                    "",
                    "",
                    "1",
                    "sb_old",
                    "",
                    "3",
                    "",
                    "Root",
                ],
            }
        ],
    },
}
