SHI_SCORPION = {
    "Ship info": {
        "variables": {"displayedName": '"SF Scorpion"', "sobDescription": '"$1640"'},
        "functions": [],
    },
    "Health and Armour": {
        "variables": {
            "maxhealth": "180",
            "regentime": "0",
            "minRegenTime": "0",
            "sideArmourDamage": "1",
            "rearArmourDamage": "1",
        },
        "functions": [],
    },
    "Main Ship Data": {"variables": {"isTransferable": "1"}, "functions": []},
    "Advanced Movement": {
        "variables": {
            "useEngagementRanges": "0",
            "thrusterUsage": "0.5",
            "accelerationAngle": "170",
            "mirrorAngle": "30",
            "secondaryTurnAngle": "90",
            "maxBankingAmount": "85",
            "descendPitch": "0",
            "goalReachEpsilon": "5",
            "slideMoveRange": "0",
            "controllerType": '"Ship"',
            "relativeMoveFactor": "6",
        },
        "functions": [],
    },
    "Deprecated": {
        "variables": {
            "unitCapsNumber": "3",
            "passiveFormation": '"Broad"',
            "defensiveFormation": '"Claw"',
            "aggressiveFormation": '"Delta"',
            "testManeuver1": '"RollCW"',
            "testManeuver2": '"RollCCW"',
            "testManeuver3": '"Loop"',
            "UnitCapsFamily": '"Fighter"',
        },
        "functions": [],
    },
    "Formations": {
        "variables": {"SquadronSize": "4", "formationSpacing": "30"},
        "functions": [],
    },
    "Movement": {
        "variables": {
            "mass": "200",
            "thrusterMaxSpeed": "284",
            "mainEngineMaxSpeed": "284",
            "rotationMaxSpeed": "180",
            "thrusterAccelTime": "3",
            "thrusterBrakeTime": "1.5",
            "mainEngineAccelTime": "3",
            "mainEngineBrakeTime": "1.5",
            "rotationAccelTime": "0.6",
            "rotationBrakeTime": "0.3",
        },
        "functions": [],
    },
    "Damage & Death": {
        "variables": {
            "collisionMultiplier": "3",
            "dustCloudDamageTime": "160",
            "nebulaDamageTime": "80",
            "battleScarCoverage": "0",
            "sobDieTime": "0.1",
            "sobSpecialDieTime": "2",
            "specialDeathSpeed": "40",
            "chanceOfSpecialDeath": "0.25",
            "deadSobFadeTime": "0",
        },
        "functions": [],
    },
    "Death Tumble": {
        "variables": {
            "tumbleStaticX": "10",
            "tumbleStaticY": "20",
            "tumbleStaticZ": "5",
            "tumbleDynamicX": "2",
            "tumbleDynamicY": "10",
            "tumbleDynamicZ": "5",
            "tumbleSpecialDynamicX": "800",
            "tumbleSpecialDynamicY": "1000",
            "tumbleSpecialDynamicZ": "700",
        },
        "functions": [],
    },
    "Swaying": {
        "variables": {
            "swayUpdateTime": "2",
            "swayOffsetRandomX": "10",
            "swayOffsetRandomY": "10",
            "swayOffsetRandomZ": "10",
            "swayBobbingFactor": "0.05",
            "swayRotateFactor": "0.1",
        },
        "functions": [],
    },
    "Families": {
        "variables": {
            "MinimalFamilyToFindPathAround": '"SuperCap"',
            "BuildFamily": '"Fighter_Vgr"',
            "AttackFamily": '"Fighter"',
            "DockFamily": '"Fighter"',
            "AvoidanceFamily": '"Strikecraft"',
            "DisplayFamily": '"Fighter"',
            "AutoFormationFamily": '"Fighter"',
            "CollisionFamily": '"Small"',
            "ArmourFamily": '"Unarmoured"',
        },
        "functions": [],
    },
    "Special Flight Maneuvers": {
        "variables": {
            "mirrorAboveManeuver": '"ImmelMann_speedy, OneEightyDegRightTurn, OneEightyDegLeftTurn, ImmelMann_speedy, ImmelMann_speedy, ImmelMann_speedy"',
            "mirrorBelowManeuver": '"Split_S_speedy, OneEightyDegRightTurn, OneEightyDegLeftTurn, Split_S_speedy, Split_S_speedy, Split_S_speedy"',
            "specialTurnLeftManeuver": '"NinetyDegLeftTurn, None, None"',
            "specialTurnRightManeuver": '"NinetyDegRightTurn, None, None"',
        },
        "functions": [],
    },
    "Ship Counter Rating": {
        "variables": {
            "fighterValue": "8",
            "corvetteValue": "0",
            "frigateValue": "0",
            "neutralValue": "0",
            "antiFighterValue": "0",
            "antiCorvetteValue": "0",
            "antiFrigateValue": "8",
            "totalValue": "8",
        },
        "functions": [],
    },
    "Construction": {
        "variables": {
            "buildCost": "430",
            "buildTime": "28",
            "buildPriorityOrder": "20",
        },
        "functions": [],
    },
    "Sensors": {
        "variables": {
            "retaliationRange": "5500",
            "retaliationDistanceFromGoal": "160",
            "visualRange": "3000",
            "prmSensorRange": "8000",
            "secSensorRange": "10000",
            "detectionStrength": "4",
        },
        "functions": [],
    },
    "Tactical Overlay Icon": {
        "variables": {
            "TOIcon": '"Triangle"',
            "TOScale": "1",
            "TODistanceFade0": "7000",
            "TODistanceDisappear0": "5000",
            "TODistanceFade1": "2500",
            "TODistanceDisappear1": "2000",
            "TODistanceFade2": "12000",
            "TODistanceDisappear2": "35000",
            "TOGroupScale": "1.5",
            "TOGroupMergeSize": "0",
        },
        "functions": [],
    },
    "Overlays": {
        "variables": {
            "mouseOverMinFadeSize": "0.045",
            "mouseOverMaxFadeSize": "0.1",
            "healthBarStyle": "0",
            "SMRepresentation": '"HardDot"',
        },
        "functions": [],
    },
    "Non linear Scaling": {
        "variables": {
            "nlips": "0",
            "nlipsRange": "10000",
            "nlipsFar": "0",
            "nlipsFarRange": "0",
        },
        "functions": [],
    },
    "Rendering": {
        "variables": {
            "meshRenderLimit": "10400000",
            "dotRenderLimit": "10",
            "visibleInSecondary": "0",
            "goblinsStartFade": "200",
            "goblinsOff": "200",
            "minimumZoomFactor": "0.75",
        },
        "functions": [],
    },
    "Level of Detail": {"variables": {"minLOD": "0.25"}, "functions": []},
    "Selection": {
        "variables": {
            "selectionLimit": "150000",
            "preciseATILimit": "0",
            "selectionPriority": "75",
            "militaryUnit": "1",
        },
        "functions": [],
    },
    "Abilities": {
        "variables": {},
        "functions": [
            {"name": "addAbility", "args": ["MoveCommand", "1", "0"]},
            {"name": "addAbility", "args": ["CanDock", "1", "1"]},
            {"name": "addAbility", "args": ["CanLaunch"]},
            {
                "name": "addAbility",
                "args": ["HyperSpaceCommand", "1", "1", "20", "80", "0", "3"],
            },
            {"name": "addAbility", "args": ["ParadeCommand", "1"]},
            {"name": "addAbility", "args": ["WaypointMove"]},
            {
                "name": "addAbility",
                "args": [
                    "CanAttack",
                    "1",
                    "1",
                    "0",
                    "0",
                    "0.35",
                    "1",
                    "Fighter, Emplacement, Corvette, Utility, Frigate, SmallCapitalShip, BigCapitalShip, Mothership",
                    "FlyBy_Interceptor_vs_Frigate",
                    '{Fighter = "Dogfight"}',
                    '{SubSystem = "TopAttack_Interceptor_vs_Subsystem"}',
                    '{Corvette = "Dogfight"}',
                    '{SmallCapitalShip = "Flyby_Interceptor_vs_CapShip"}',
                    '{BigCapitalShip = "Flyby_Interceptor_vs_CapShip"}',
                    '{Mothership = "Flyby_Interceptor_vs_Mothership"}',
                    '{ResourceLarge = "Flyby_Interceptor_vs_ResourceLarge"}',
                ],
            },
            {"name": "addAbility", "args": ["GuardCommand", "1", "3000", "500"]},
            {
                "name": "addAbility",
                "args": ["HyperspaceViaGateCommand", "0", "3", "0.2", "0.3"],
            },
            {"name": "addAbility", "args": ["RetireAbility", "1", "0"]},
            {
                "name": "addAbility",
                "args": [
                    "CustomCommand",
                    "1",
                    "Speed Burst",
                    "1",
                    "0",
                    "60",
                    "0",
                    "1",
                    "0.25",
                    "0",
                    "data:Ship/Afterburner.lua",
                    "Start_Afterburner",
                    "Do_Afterburner",
                    "Finish_Afterburner",
                    "shi_scorpion",
                    "0.5",
                    "3",
                    "1",
                ],
            },
        ],
    },
    "Docking": {
        "variables": {
            "dockTimeBetweenTwoFormations": "0.5",
            "dockTimeBeforeStart": "0.5",
            "dockNrOfShipsInDockFormation": "1",
            "dockFormation": '"dockline"',
            "queueFormation": '"n_delta"',
            "ignoreRaceWhenDocking": "0",
        },
        "functions": [],
    },
    "Launching": {
        "variables": {
            "launchTimeBetweenTwoFormations": "0.5",
            "launchTimeBeforeStart": "0.5",
            "launchNrOfShipsInDockFormation": "1",
            "launchFormation": '"n_delta"',
        },
        "functions": [],
    },
    "Alternative Hyperspace Gate": {
        "variables": {
            "alternativeHyperspaceV": '"hyperspace_gate_small"',
            "alternativeHyperspaceA": '"etg/misc/small_warp"',
            "alternativeHyperspaceTime": "7",
        },
        "functions": [],
    },
    "Custom Code": {
        "variables": {},
        "functions": [
            {
                "name": "addCustomCode",
                "args": [
                    "data:ship/ABFix.lua",
                    "",
                    "",
                    "AfterburnerFix",
                    "",
                    "AfterburnerFix",
                    "10",
                ],
            }
        ],
    },
    "Load Model": {
        "variables": {},
        "functions": [{"name": "LoadModel", "args": ["1"]}],
    },
    "HardPoints": {
        "variables": {},
        "functions": [
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Shield",
                    "Hardpoint_Shield",
                    "System",
                    "Innate",
                    "Damageable",
                    "shield_scorpion",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Gun_1",
                    "Weapon_Gun1",
                    "Weapon",
                    "Production",
                    "Destroyable",
                    "wep_shimegalaser",
                    "wep_prometheusfs1",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Gun_2",
                    "Weapon_Gun2",
                    "Weapon",
                    "Production",
                    "Destroyable",
                    "wep_shimegalaser",
                    "wep_prometheusfs1",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Missile1",
                    "Weapon_Missile",
                    "Weapon",
                    "Sensors",
                    "Destroyable",
                    "wep_shirockeye",
                    "wep_rockeye",
                    "wep_empadv",
                    "wep_tempest",
                    "wep_hornet",
                    "wep_tornadonormal",
                    "wep_harpoon",
                    "wep_trebuchet",
                    "",
                ],
            },
        ],
    },
    "Weapons": {
        "variables": {},
        "functions": [
            {
                "name": "StartShipWeaponConfig",
                "args": ["Shi_MegaLaser", "Weapon_Gun1", "Weapon_Gun1"],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["Shi_MegaLaser", "Weapon_Gun2", "Weapon_Gun2"],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["fs1_mx50", "Weapon_Missile", ""],
            },
        ],
    },
    "Shields": {
        "variables": {},
        "functions": [{"name": "addShield", "args": ["EMP", "75", "9"]}],
    },
    "Engines": {
        "variables": {},
        "functions": [
            {
                "name": "setEngineBurn",
                "args": ["7", "0.5", "1", "15", "0", "0.7", "0.1", "25"],
            }
        ],
    },
    "Addendum": {
        "variables": {},
        "functions": [
            {
                "name": "loadShipPatchList",
                "args": [
                    "data:sound/sfx/ship/",
                    "0",
                    "",
                    "",
                    "1",
                    "sf_old",
                    "",
                    "3",
                    "",
                    "Root",
                ],
            }
        ],
    },
}
TER_LOKI = {
    "Ship info": {
        "variables": {"displayedName": '"GTF Loki"', "sobDescription": '"$1640"'},
        "functions": [],
    },
    "Health and Armour": {
        "variables": {
            "maxhealth": "250",
            "regentime": "0",
            "minRegenTime": "0",
            "sideArmourDamage": "1",
            "rearArmourDamage": "1",
        },
        "functions": [],
    },
    "Main Ship Data": {"variables": {"isTransferable": "1"}, "functions": []},
    "Advanced Movement": {
        "variables": {
            "useEngagementRanges": "0",
            "thrusterUsage": "0.25",
            "accelerationAngle": "170",
            "mirrorAngle": "30",
            "secondaryTurnAngle": "90",
            "maxBankingAmount": "85",
            "descendPitch": "0",
            "goalReachEpsilon": "5",
            "slideMoveRange": "0",
            "controllerType": '"Ship"',
            "relativeMoveFactor": "6",
        },
        "functions": [],
    },
    "Deprecated": {
        "variables": {
            "unitCapsNumber": "3",
            "passiveFormation": '"Delta"',
            "defensiveFormation": '"Broad"',
            "aggressiveFormation": '"Claw"',
            "testManeuver1": '"RollCW"',
            "testManeuver2": '"RollCCW"',
            "testManeuver3": '"Loop"',
            "UnitCapsFamily": '"Fighter"',
        },
        "functions": [],
    },
    "Formations": {
        "variables": {"SquadronSize": "4", "formationSpacing": "40"},
        "functions": [],
    },
    "Movement": {
        "variables": {
            "mass": "200",
            "thrusterMaxSpeed": "340",
            "mainEngineMaxSpeed": "340",
            "rotationMaxSpeed": "130",
            "thrusterAccelTime": "2",
            "thrusterBrakeTime": "1",
            "mainEngineAccelTime": "2",
            "mainEngineBrakeTime": "1.5",
            "rotationAccelTime": "0.6",
            "rotationBrakeTime": "0.3",
        },
        "functions": [],
    },
    "Damage & Death": {
        "variables": {
            "collisionMultiplier": "3",
            "dustCloudDamageTime": "160",
            "nebulaDamageTime": "80",
            "battleScarCoverage": "0",
            "sobDieTime": "0.1",
            "sobSpecialDieTime": "2",
            "specialDeathSpeed": "40",
            "chanceOfSpecialDeath": "0.25",
            "deadSobFadeTime": "0",
        },
        "functions": [],
    },
    "Death Tumble": {
        "variables": {
            "tumbleStaticX": "10",
            "tumbleStaticY": "20",
            "tumbleStaticZ": "5",
            "tumbleDynamicX": "2",
            "tumbleDynamicY": "10",
            "tumbleDynamicZ": "5",
            "tumbleSpecialDynamicX": "800",
            "tumbleSpecialDynamicY": "1000",
            "tumbleSpecialDynamicZ": "700",
        },
        "functions": [],
    },
    "Swaying": {
        "variables": {
            "swayUpdateTime": "2",
            "swayOffsetRandomX": "10",
            "swayOffsetRandomY": "10",
            "swayOffsetRandomZ": "10",
            "swayBobbingFactor": "0.05",
            "swayRotateFactor": "0.1",
        },
        "functions": [],
    },
    "Families": {
        "variables": {
            "MinimalFamilyToFindPathAround": '"SuperCap"',
            "BuildFamily": '"Fighter_Vgr"',
            "AttackFamily": '"Fighter"',
            "DockFamily": '"Fighter"',
            "AvoidanceFamily": '"Strikecraft"',
            "DisplayFamily": '"Fighter"',
            "AutoFormationFamily": '"Fighter"',
            "CollisionFamily": '"Small"',
            "ArmourFamily": '"Unarmoured"',
        },
        "functions": [],
    },
    "Special Flight Maneuvers": {
        "variables": {
            "mirrorAboveManeuver": '"ImmelMann_speedy, OneEightyDegRightTurn, OneEightyDegLeftTurn, ImmelMann_speedy, ImmelMann_speedy, ImmelMann_speedy"',
            "mirrorBelowManeuver": '"Split_S_speedy, OneEightyDegRightTurn, OneEightyDegLeftTurn, Split_S_speedy, Split_S_speedy, Split_S_speedy"',
            "specialTurnLeftManeuver": '"NinetyDegLeftTurn, None, None"',
            "specialTurnRightManeuver": '"NinetyDegRightTurn, None, None"',
        },
        "functions": [],
    },
    "Ship Counter Rating": {
        "variables": {
            "fighterValue": "8",
            "corvetteValue": "0",
            "frigateValue": "0",
            "neutralValue": "0",
            "antiFighterValue": "8",
            "antiCorvetteValue": "0",
            "antiFrigateValue": "0",
            "totalValue": "8",
        },
        "functions": [],
    },
    "Construction": {
        "variables": {
            "buildCost": "460",
            "buildTime": "29",
            "buildPriorityOrder": "20",
        },
        "functions": [],
    },
    "Sensors": {
        "variables": {
            "retaliationRange": "5500",
            "retaliationDistanceFromGoal": "160",
            "visualRange": "3000",
            "prmSensorRange": "8000",
            "secSensorRange": "10000",
            "detectionStrength": "1",
        },
        "functions": [],
    },
    "Tactical Overlay Icon": {
        "variables": {
            "TOIcon": '"Triangle"',
            "TOScale": "1",
            "TODistanceFade0": "7000",
            "TODistanceDisappear0": "5000",
            "TODistanceFade1": "2500",
            "TODistanceDisappear1": "2000",
            "TODistanceFade2": "12000",
            "TODistanceDisappear2": "35000",
            "TOGroupScale": "1.5",
            "TOGroupMergeSize": "0",
        },
        "functions": [],
    },
    "Overlays": {
        "variables": {
            "mouseOverMinFadeSize": "0.045",
            "mouseOverMaxFadeSize": "0.1",
            "healthBarStyle": "0",
            "SMRepresentation": '"HardDot"',
        },
        "functions": [],
    },
    "Non linear Scaling": {
        "variables": {
            "nlips": "0.0002",
            "nlipsRange": "6000",
            "nlipsFar": "0.0001",
            "nlipsFarRange": "10000",
        },
        "functions": [],
    },
    "Rendering": {
        "variables": {
            "meshRenderLimit": "104000",
            "dotRenderLimit": "10",
            "visibleInSecondary": "0",
            "goblinsStartFade": "200",
            "goblinsOff": "200",
            "minimumZoomFactor": "0.75",
        },
        "functions": [],
    },
    "Level of Detail": {"variables": {"minLOD": "0.25"}, "functions": []},
    "Selection": {
        "variables": {
            "selectionLimit": "150000",
            "preciseATILimit": "0",
            "selectionPriority": "75",
            "militaryUnit": "1",
        },
        "functions": [],
    },
    "Abilities": {
        "variables": {},
        "functions": [
            {"name": "addAbility", "args": ["MoveCommand", "1", "0"]},
            {"name": "addAbility", "args": ["CanDock", "1", "1"]},
            {"name": "addAbility", "args": ["CanLaunch"]},
            {
                "name": "addAbility",
                "args": ["HyperSpaceCommand", "1", "1", "25", "100", "0", "3"],
            },
            {"name": "addAbility", "args": ["ParadeCommand", "1"]},
            {"name": "addAbility", "args": ["WaypointMove"]},
            {
                "name": "addAbility",
                "args": [
                    "CanAttack",
                    "1",
                    "1",
                    "0",
                    "0",
                    "0.35",
                    "1",
                    "Fighter, Emplacement, Corvette, Frigate, Utility, SmallCapitalShip, BigCapitalShip, Mothership",
                    "FlyBy_Interceptor_vs_Frigate",
                    '{Fighter = "Dogfight"}',
                    '{Corvette = "Dogfight"}',
                    '{SubSystem = "TopAttack_Interceptor_vs_Subsystem"}',
                    '{SmallCapitalShip = "Flyby_Interceptor_vs_CapShip"}',
                    '{BigCapitalShip = "Flyby_Interceptor_vs_CapShip"}',
                    '{Mothership = "Flyby_Interceptor_vs_Mothership"}',
                    '{ResourceLarge = "Flyby_Interceptor_vs_ResourceLarge"}',
                ],
            },
            {"name": "addAbility", "args": ["GuardCommand", "1", "3000", "500"]},
            {"name": "addAbility", "args": ["CanBeRepaired"]},
            {
                "name": "addAbility",
                "args": ["HyperspaceViaGateCommand", "1", "3", "0.25", "0"],
            },
            {"name": "addAbility", "args": ["RetireAbility", "1", "0"]},
            {
                "name": "addAbility",
                "args": [
                    "CustomCommand",
                    "1",
                    "Speed Burst",
                    "1",
                    "0",
                    "60",
                    "0",
                    "1",
                    "0.25",
                    "0",
                    "data:Ship/Afterburner.lua",
                    "Start_Afterburner",
                    "Do_Afterburner",
                    "Finish_Afterburner",
                    "ter_loki",
                    "0.5",
                    "3",
                    "1",
                ],
            },
        ],
    },
    "Docking": {
        "variables": {
            "dockTimeBetweenTwoFormations": "0.5",
            "dockTimeBeforeStart": "0.5",
            "dockNrOfShipsInDockFormation": "1",
            "dockFormation": '"dockline"',
            "queueFormation": '"n_delta"',
            "ignoreRaceWhenDocking": "0",
        },
        "functions": [],
    },
    "Launching": {
        "variables": {
            "launchTimeBetweenTwoFormations": "0.5",
            "launchTimeBeforeStart": "0.5",
            "launchNrOfShipsInDockFormation": "1",
            "launchFormation": '"n_delta"',
        },
        "functions": [],
    },
    "Alternative Hyperspace Gate": {
        "variables": {
            "alternativeHyperspaceV": '"hyperspace_gate_small"',
            "alternativeHyperspaceA": '"etg/misc/small_warp"',
            "alternativeHyperspaceTime": "7",
        },
        "functions": [],
    },
    "Custom Code": {
        "variables": {},
        "functions": [
            {
                "name": "addCustomCode",
                "args": [
                    "data:ship/ABFix.lua",
                    "",
                    "",
                    "AfterburnerFix",
                    "",
                    "AfterburnerFix",
                    "10",
                ],
            }
        ],
    },
    "Load Model": {
        "variables": {},
        "functions": [{"name": "LoadModel", "args": ["1"]}],
    },
    "HardPoints": {
        "variables": {},
        "functions": [
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Shield",
                    "Hardpoint_Shield",
                    "System",
                    "Innate",
                    "Damageable",
                    "shield_loki",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Gun_1",
                    "Weapon_FrontGun",
                    "Weapon",
                    "Production",
                    "Destroyable",
                    "wep_lamprey",
                    "wep_subach",
                    "wep_SDG",
                    "wep_prometheusr",
                    "wep_prometheus",
                    "wep_morningstar",
                    "wep_circe",
                    "wep_lamprey",
                    "wep_maxim",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Gun_2",
                    "Weapon_FrontGun2",
                    "Weapon",
                    "Production",
                    "Destroyable",
                    "wep_subach",
                    "wep_subach_2",
                    "wep_SDG_2",
                    "wep_prometheusr_2",
                    "wep_prometheus_2",
                    "wep_morningstar_2",
                    "wep_circe_2",
                    "wep_lamprey_2",
                    "wep_maxim_2",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Missile_1",
                    "Weapon_Missile",
                    "Weapon",
                    "Sensors",
                    "Destroyable",
                    "wep_harpoon",
                    "wep_rockeye",
                    "wep_empadv",
                    "wep_tempest",
                    "wep_hornet",
                    "wep_tornadonormal",
                    "wep_harpoon",
                    "wep_trebuchet",
                    "",
                ],
            },
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Missile_2",
                    "Weapon_Missile",
                    "Weapon",
                    "Sensors",
                    "Destroyable",
                    "wep_empadv",
                    "wep_rockeye",
                    "wep_empadv",
                    "wep_tempest",
                    "wep_hornet",
                    "wep_tornadonormal",
                    "wep_harpoon",
                    "wep_trebuchet",
                    "",
                ],
            },
        ],
    },
    "Weapons": {
        "variables": {},
        "functions": [
            {
                "name": "StartShipWeaponConfig",
                "args": ["ter_subach", "Weapon_FrontGun", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["vas_lamprey", "Weapon_FrontGun2", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["vas_harpoon", "Weapon_Missile", ""],
            },
            {
                "name": "StartShipWeaponConfig",
                "args": ["vas_empadv", "Weapon_Missile", ""],
            },
        ],
    },
    "Shields": {
        "variables": {},
        "functions": [{"name": "addShield", "args": ["EMP", "175", "20"]}],
    },
    "Engines": {
        "variables": {},
        "functions": [
            {
                "name": "setEngineBurn",
                "args": ["7", "0.5", "1", "15", "0", "0.7", "0.1", "20"],
            }
        ],
    },
    "Addendum": {
        "variables": {},
        "functions": [
            {
                "name": "loadShipPatchList",
                "args": ["data:sound/sfx/ship/", "0", "", "", "1", "terranfighter", ""],
            }
        ],
    },
}