Icon_Speed = "data:ui/newui/research/icons/speed.mres"
Icon_Health = "data:ui/newui/research/icons/health.mres"
Icon_Tech = "data:ui/newui/research/icons/tech.mres"
Icon_Ability = "data:ui/newui/research/icons/ability.mres"
Icon_Build = "data:ui/newui/research/icons/build.mres"

Modifier = 0
Ability = 1
AllShips = 0
Family = 1
Ship = 2

research = {
	{
		Name = "FS1",
		RequiredResearch = "",
		RequiredSubSystems = "",
		DoNotGrant = 1,
		Cost = 10,
		Time = 1,
		DisplayedName = "FreeSpace 1 Era",
		DisplayPriority = 0,
		Description = "Activates FreeSpace 1 ships and technology.",
		Icon = Icon_Tech,
		ShortDisplayedName = "FS1 Era",
		TargetType = Ship,
		TargetName = "vas_seth",
	},
	{
		Name = "FS2",
		RequiredResearch = "",
		RequiredSubSystems = "",
		DoNotGrant = 1,
		Cost = 10,
		Time = 1,
		DisplayedName = "FreeSpace 2 Era",
		DisplayPriority = 0,
		Description = "Activates FreeSpace 2 ships and technology.",
		Icon = Icon_Tech,
		ShortDisplayedName = "FS2 Era",
		TargetType = Ship,
		TargetName = "vas_ptah",
	},

	-- Fighters --------------
	{
		Name = "FighterDesign",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1200,
		Time = 40,
		DisplayedName = "Fighter Design <c=0e0160>(40s)</c>",
		DisplayPriority = 1,
		Description = "Fighter chassis and drives. Required for all Vasudan Fighter class research.",
		TargetType = Ship,
		TargetName = "vas_horus",
		Icon = Icon_Build,
		ShortDisplayedName = "Fighter Design",
	},
	{
		Name = "Seth",
		RequiredResearch = "FighterDesign & FS1",
		RequiredSubSystems = "",
		Cost = 850,
		Time = 40,
		DisplayedName = "GVF Seth <c=0e0160>(40s)</c>",
		DisplayPriority = 19,
		Description = "Unlocks the GVF Seth Assault Fighter.",
		TargetType = Ship,
		TargetName = "vas_seth",
		Icon = Icon_Build,
		ShortDisplayedName = "Seth",
	},
	{
		Name = "Horus",
		RequiredResearch = "FighterDesign & FS1",
		RequiredSubSystems = "",
		Cost = 800,
		Time = 35,
		DisplayedName = "GVF Horus <c=0e0160>(35s)</c>",
		DisplayPriority = 11,
		Description = "Unlocks the GVF Horus Interceptor.",
		TargetType = Ship,
		TargetName = "vas_horus",
		Icon = Icon_Build,
		ShortDisplayedName = "Horus",
	},
	{
		Name = "Thoth",
		RequiredResearch = "FighterDesign",
		RequiredSubSystems = "",
		Cost = 900,
		Time = 45,
		DisplayedName = "GVF Thoth <c=0e0160>(45s)</c>",
		DisplayPriority = 22,
		Description = "Unlocks the GVF Thoth Superiority Fighter.",
		TargetType = Ship,
		TargetName = "vas_thoth",
		Icon = Icon_Build,
		ShortDisplayedName = "Thoth",
	},
	{
		Name = "Ptah",
		RequiredResearch = "FighterDesign & FS2",
		RequiredSubSystems = "",
		Cost = 1200,
		Time = 50,
		DisplayedName = "GVF Ptah <c=0e0160>(50s)</c>",
		DisplayPriority = 22,
		Description = "Unlocks the GVF Ptah Stealth Recon Fighter.",
		TargetType = Ship,
		TargetName = "vas_ptah",
		Icon = Icon_Build,
		ShortDisplayedName = "Ptah",
	},
	{
		Name = "Serapis",
		RequiredResearch = "FighterDesign & FS2",
		RequiredSubSystems = "",
		Cost = 1200,
		Time = 50,
		DisplayedName = "GVF Serapis <c=0e0160>(50s)</c>",
		DisplayPriority = 19,
		Description = "Unlocks the GVF Serapis Advanced Interceptor.",
		TargetType = Ship,
		TargetName = "vas_serapis",
		Icon = Icon_Build,
		ShortDisplayedName = "Serapis",
	},
	{
		Name = "Tauret",
		RequiredResearch = "FighterDesign & FS2",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 60,
		DisplayedName = "GVF Tauret <c=0e0160>(60s)</c>",
		DisplayPriority = 12,
		Description = "Unlocks the GVF Tauret Heavy Assault Fighter.",
		TargetType = Ship,
		TargetName = "vas_tauret",
		Icon = Icon_Build,
		ShortDisplayedName = "Tauret",
	},

	-- Bombers ---------------
	{
		Name = "BomberDesign",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Bomber Design <c=0e0160>(50s)</c>",
		DisplayPriority = 2,
		Description = "Bomber chassis and drives. Required for all Vasudan Bomber class research.",
		TargetType = Ship,
		TargetName = "vas_osiris",
		Icon = Icon_Build,
		ShortDisplayedName = "Bomber Design",
	},
	{
		Name = "Osiris",
		RequiredResearch = "BomberDesign",
		RequiredSubSystems = "",
		Cost = 1000,
		Time = 40,
		DisplayedName = "GVB Osiris <c=0e0160>(40s)</c>",
		DisplayPriority = 15,
		Description = "Unlocks the GVB Osiris Reserve Bomber.",
		TargetType = Ship,
		TargetName = "vas_osiris",
		Icon = Icon_Build,
		ShortDisplayedName = "Osiris",
	},
	{
		Name = "Bakha",
		RequiredResearch = "BomberDesign & FS2",
		RequiredSubSystems = "",
		Cost = 1200,
		Time = 50,
		DisplayedName = "GVB Bakha <c=0e0160>(50s)</c>",
		DisplayPriority = 15,
		Description = "Unlocks the GVB Bakha Strike Bomber.",
		TargetType = Ship,
		TargetName = "vas_bakha",
		Icon = Icon_Build,
		ShortDisplayedName = "Bakha",
	},
	{
		Name = "Sehkmet",
		RequiredResearch = "BomberDesign & FS2",
		RequiredSubSystems = "",
		Cost = 1800,
		Time = 60,
		DisplayedName = "GVB Sehkmet <c=0e0160>(60s)</c>",
		DisplayPriority = 26,
		Description = "Unlocks the GVB Sehkmet Heavy Bomber.",
		TargetType = Ship,
		TargetName = "vas_sehkmet",
		Icon = Icon_Build,
		ShortDisplayedName = "Sehkmet",
	},

	-- Cruisers --------------
	{
		Name = "CruiserDesign",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 2500,
		Time = 50,
		DisplayedName = "Cruiser Design <c=0e0160>(50s)</c>",
		DisplayPriority = 3,
		Description = "Cruiser chassis and drives. Required for all Vasudan Cruiser class research.",
		TargetType = Ship,
		TargetName = "vas_aten",
		Icon = Icon_Build,
		ShortDisplayedName = "Cruiser Design",
	},
	{
		Name = "Aten",
		RequiredResearch = "CruiserDesign",
		RequiredSubSystems = "",
		Cost = 1000,
		Time = 50,
		DisplayedName = "GVC Aten <c=0e0160>(50s)</c>",
		DisplayPriority = 18,
		Description = "Unlocks the GVC Aten Reserve Cruiser.",
		TargetType = Ship,
		TargetName = "vas_aten",
		Icon = Icon_Build,
		ShortDisplayedName = "Aten",
	},
	{
		Name = "Mentu",
		RequiredResearch = "CruiserDesign & FS2",
		RequiredSubSystems = "",
		Cost = 2000,
		Time = 60,
		DisplayedName = "GVC Mentu <c=0e0160>(60s)</c>",
		DisplayPriority = 21,
		Description = "Unlocks the GVC Mentu Advanced Cruiser.",
		TargetType = Ship,
		TargetName = "vas_mentu",
		Icon = Icon_Build,
		ShortDisplayedName = "Mentu",
	},
	{
		Name = "ScienceVessel",
		RequiredResearch = "CruiserDesign",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Science Vessel <c=0e0160>(50s)</c>",
		DisplayPriority = 25,
		Description = "Unlocks Science Vessels: Imhotep.",
		TargetType = Ship,
		TargetName = "vas_imhotep",
		Icon = Icon_Build,
		ShortDisplayedName = "Science Vessel",
	},

	-- Capital Ships ---------
	{
		Name = "CapitalShipDesign",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 3000,
		Time = 75,
		DisplayedName = "Capital Ship Design <c=0e0160>(75s)</c>",
		DisplayPriority = 4,
		Description = "Capital ship chassis and drives. Required for all Vasudan Capital class research.",
		TargetType = Ship,
		TargetName = "vas_typhon",
		Icon = Icon_Build,
		ShortDisplayedName = "Capital Ship Design",
	},
	{
		Name = "Typhon",
		RequiredResearch = "CapitalShipDesign",
		RequiredSubSystems = "",
		Cost = 4000,
		Time = 90,
		DisplayedName = "GVD Typhon <c=0e0160>(90s)</c>",
		DisplayPriority = 13,
		Description = "Unlocks the GVD Typhon Destroyer.",
		TargetType = Ship,
		TargetName = "vas_typhon",
		Icon = Icon_Build,
		ShortDisplayedName = "Typhon",
	},
	{
		Name = "Sobek",
		RequiredResearch = "CapitalShipDesign & FS2",
		RequiredSubSystems = "",
		Cost = 2000,
		Time = 60,
		DisplayedName = "GVCv Sobek <c=0e0160>(60s)</c>",
		DisplayPriority = 15,
		Description = "Unlocks the GVCv Sobek Corvette.",
		TargetType = Ship,
		TargetName = "vas_sobek",
		Icon = Icon_Build,
		ShortDisplayedName = "Sobek",
	},
	{
		Name = "SobekArmor",
		RequiredResearch = "Sobek",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Sobek Armor <c=0e0160>(50s)</c>",
		DisplayPriority = 16,
		Description = "Increases health of GVCv Sobek by 12.5%.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "vas_sobek",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.125,
		Icon = Icon_Health,
		ShortDisplayedName = "Sobek Armor Upgrade",
	},
	{
		Name = "SobekSprint",
		RequiredResearch = "Sobek",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Sobek Sprint Drive <c=0e0160>(50s)</c>",
		DisplayPriority = 17,
		Description = "Improves the top speed of GVCv Sobek by 25%.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "vas_sobek",
		UpgradeName = "MaxSpeed",
		UpgradeValue = 1.25,
		Icon = Icon_Speed,
		ShortDisplayedName = "Sobek Sprint Drive",
	},
	{
		Name = "Hatshepsut",
		RequiredResearch = "CapitalShipDesign & FS2",
		RequiredSubSystems = "",
		Cost = 4500,
		Time = 100,
		DisplayedName = "GVD Hatshepsut <c=0e0160>(100s)</c>",
		DisplayPriority = 36,
		Description = "Unlocks the GVD Hatshepsut Destroyer.",
		TargetType = Ship,
		TargetName = "vas_hatshepsut",
		Icon = Icon_Build,
		ShortDisplayedName = "Hatshepsut",
	},
	{
		Name = "Installation",
		RequiredResearch = "CapitalShipDesign",
		RequiredSubSystems = "",
		Cost = 2500,
		Time = 75,
		DisplayedName = "Installation <c=0e0160>(75s)</c>",
		DisplayPriority = 13,
		Description = "Unlocks Installations: Karnak.",
		TargetType = Ship,
		TargetName = "vas_karnak",
		Icon = Icon_Build,
		ShortDisplayedName = "Installation",
	},
	{
		Name = "SuperCapitalShipDesign",
		RequiredResearch = "CapitalShipDesign & FS2",
		RequiredSubSystems = "",
		Cost = 10000,
		Time = 150,
		DisplayedName = "Super Capital Ship Design <c=0e0160>(150s)</c>",
		DisplayPriority = 5,
		Description = "Unlocks GTVA Colossus class juggernauts.",
		TargetType = Ship,
		TargetName = "vas_colossus",
		Icon = Icon_Build,
		ShortDisplayedName = "Super Capital Design",
	},
	{
		Name = "Colossus",
		RequiredResearch = "SuperCapitalShipDesign",
		RequiredSubSystems = "",
		Cost = 15000,
		Time = 200,
		DisplayedName = "GTVA Colossus <c=0e0160>(200s)</c>",
		DisplayPriority = 31,
		Description = "Unlocks the GTVA Colossus Juggernaut.",
		TargetType = Ship,
		TargetName = "vas_colossus",
		Icon = Icon_Build,
		ShortDisplayedName = "Colossus",
	},

	-- Platforms -------------
	{
		Name = "SentryGun",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Sentry Gun <c=0e0160>(50s)</c>",
		DisplayPriority = 17,
		Description = "Unlocks Sentry Guns: Edjo, Ankh.",
		TargetType = Ship,
		TargetName = "vas_edjo",
		Icon = Icon_Build,
		ShortDisplayedName = "Sentry Gun",
	},
	{
		Name = "SentryAndMineDeployer",
		RequiredResearch = "SentryGun",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Sentry And Mine Deployer <c=0e0160>(50s)</c>",
		DisplayPriority = 29,
		Description = "Unlocks Sentry and Mine Deployers: Vasudan Bes.",
		TargetType = Ship,
		TargetName = "vas_bes",
		Icon = Icon_Build,
		ShortDisplayedName = "Sentry And Mine Deployer",
	},

	-- Utility ---------------
	{
		Name = "AWACS",
		RequiredResearch = "CruiserDesign & FS2",
		RequiredSubSystems = "",
		Cost = 2500,
		Time = 50,
		DisplayedName = "AWACS <c=0e0160>(50s)</c>",
		DisplayPriority = 30,
		Description = "Unlocks AWACS vessels: Setekh.",
		TargetType = Ship,
		TargetName = "vas_setekh",
		Icon = Icon_Build,
		ShortDisplayedName = "AWACS",
	},

	{
		Name = "RepairSatis",
		RequiredResearch = "CruiserDesign & FS1",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Repair Satis <c=0e0160>(50s)</c>",
		DisplayPriority = 30,
		Description = "Unlocks Repair Frigate Satis.",
		TargetType = Ship,
		TargetName = "vas_satis",
		Icon = Icon_Build,
		ShortDisplayedName = "Repair Satis",
	},
	{
		Name = "RepairBast",
		RequiredResearch = "CruiserDesign & FS2",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Repair Bast <c=0e0160>(50s)</c>",
		DisplayPriority = 30,
		Description = "Unlocks Repair Frigate Bast.",
		TargetType = Ship,
		TargetName = "vas_bast",
		Icon = Icon_Build,
		ShortDisplayedName = "Repair Bast",
	},

	-- AI Only Nodes ---------
	{
		Name = "cpuplayers_defensive",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_aggressive",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_dynamic",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_norushtime5",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_norushtime10",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_norushtime15",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "AllShipBuildSpeed",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Capital",
		UpgradeName = "BUILDSPEED",
		UpgradeValue = 1.025,
		AIOnly = 1,
	},
	{
		Name = "AllShipBuildSpeedHard",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Capital",
		UpgradeName = "BUILDSPEED",
		UpgradeValue = 1.05,
		AIOnly = 1,
	},
	{
		Name = "AllShipBuildSpeedExpert",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Capital",
		UpgradeName = "BUILDSPEED",
		UpgradeValue = 1.075,
		AIOnly = 1,
	},
	{
		Name = "ResourceCollectionRateHard",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "vas_isis",
		UpgradeName = "ResourceCollectionRate",
		UpgradeValue = 1.04,
		AIOnly = 1,
	},
	{
		Name = "ResourceCollectionRateExpert",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "vas_isis",
		UpgradeName = "ResourceCollectionRate",
		UpgradeValue = 1.08,
		AIOnly = 1,
	},
	{
		Name = "HeavyGuns",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
}
