Icon_Speed = "data:ui/newui/research/icons/speed.mres"
Icon_Health = "data:ui/newui/research/icons/health.mres"
Icon_Tech = "data:ui/newui/research/icons/tech.mres"
Icon_Ability = "data:ui/newui/research/icons/ability.mres"
Icon_Build = "data:ui/newui/research/icons/build.mres"

Modifier = 0
Ability = 1
AllShips = 0
Family = 1
Ship = 2

research = {
	{
		Name = "FS1",
		RequiredResearch = "",
		RequiredSubSystems = "",
		--DoNotGrant = 1,
		Cost = 10,
		Time = 1,
		DisplayedName = "FreeSpace 1 Era",
		DisplayPriority = 0,
		Description = "Activates FreeSpace 1 ships and technology.",
		Icon = Icon_Tech,
		ShortDisplayedName = "FS1 Era",
	},
	{
		Name = "FS2",
		RequiredResearch = "",
		RequiredSubSystems = "",
		--DoNotGrant = 1,
		Cost = 10,
		Time = 1,
		DisplayedName = "FreeSpace 2 Era",
		DisplayPriority = 0,
		Description = "Activates FreeSpace 2 ships and technology.",
		Icon = Icon_Tech,
		ShortDisplayedName = "FS2 Era",
	},

	-- Fighters --------------
	{
		Name = "FighterDesign",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1200,
		Time = 40,
		DisplayedName = "Fighter Design <c=0e0160>(40s)</c>",
		DisplayPriority = 1,
		Description = "Fighter chassis and drives. Required for all Vasudan Fighter class research.",
		TargetType = Ship,
		TargetName = "vas_horus",
		Icon = Icon_Build,
		ShortDisplayedName = "Fighter Design <c=0e0160>(40s)</c>",
	},
	{
		Name = "Seth",
		RequiredResearch = "Anubis & FS1",
		RequiredSubSystems = "",
		Cost = 850,
		Time = 40,
		DisplayedName = "Seth <c=0e0160>(40s)</c>",
		DisplayPriority = 19,
		Description = "Unlocks the GVF Seth Assault Fighter.",
		TargetType = Ship,
		TargetName = "vas_seth",
		Icon = Icon_Build,
		ShortDisplayedName = "Seth <c=0e0160>(40s)</c>",
	},
	{
		Name = "Anubis",
		RequiredResearch = "FighterDesing & FS1",
		RequiredSubSystems = "",
		Cost = 700,
		Time = 40,
		DisplayedName = "Anubis <c=0e0160>(40s)</c>",
		DisplayPriority = 20,
		Description = "Unlocks the PVF Anubis Space Superiority Fighter.",
		TargetType = Ship,
		TargetName = "vas_anubis",
		Icon = Icon_Build,
		ShortDisplayedName = "Anubis <c=0e0160>(40s)</c>",
	},
	{
		Name = "Thoth",
		RequiredResearch = "Seth or (FighterDesign & FS2)",
		RequiredSubSystems = "",
		Cost = 1000,
		Time = 45,
		DisplayedName = "Thoth <c=0e0160>(45s)</c>",
		DisplayPriority = 22,
		Description = "Unlocks the GVF Thoth Superiority Fighter.",
		TargetType = Ship,
		TargetName = "vas_thoth",
		Icon = Icon_Build,
		ShortDisplayedName = "Thoth <c=0e0160>(45s)</c>",
	},
	{
		Name = "Ptah",
		RequiredResearch = "Serapis",
		RequiredSubSystems = "",
		Cost = 1200,
		Time = 50,
		DisplayedName = "Ptah <c=0e0160>(50s)</c>",
		DisplayPriority = 22,
		Description = "Unlocks the GVF Ptah Stealth Recon Fighter.",
		TargetType = Ship,
		TargetName = "vas_ptah",
		Icon = Icon_Build,
		ShortDisplayedName = "Ptah <c=0e0160>(50s)</c>",
	},
	{
		Name = "Serapis",
		RequiredResearch = "Thoth & FS2",
		RequiredSubSystems = "",
		Cost = 1200,
		Time = 50,
		DisplayedName = "Serapis <c=0e0160>(50s)</c>",
		DisplayPriority = 19,
		Description = "Unlocks the GVF Serapis Advanced Interceptor.",
		TargetType = Ship,
		TargetName = "vas_serapis",
		Icon = Icon_Build,
		ShortDisplayedName = "Serapis <c=0e0160>(50s)</c>",
	},
	{
		Name = "Tauret",
		RequiredResearch = "Serapis",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 60,
		DisplayedName = "Tauret <c=0e0160>(60s)</c>",
		DisplayPriority = 12,
		Description = "Unlocks the GVF Tauret Heavy Assault Fighter.",
		TargetType = Ship,
		TargetName = "vas_tauret",
		Icon = Icon_Build,
		ShortDisplayedName = "Tauret <c=0e0160>(60s)</c>",
	},

	-- Bombers ---------------
	{
		Name = "BomberDesign",
		RequiredResearch = "FighterDesign",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Bomber Design <c=0e0160>(50s)</c>",
		DisplayPriority = 2,
		Description = "Bomber chassis and drives. Required for all Vasudan Bomber class research.",
		TargetType = Ship,
		TargetName = "vas_osiris",
		Icon = Icon_Build,
		ShortDisplayedName = "Bomber Design <c=0e0160>(50s)</c>",
	},
	{
		Name = "Bakha",
		RequiredResearch = "BomberDesign & FS2",
		RequiredSubSystems = "",
		Cost = 1200,
		Time = 50,
		DisplayedName = "Bakha <c=0e0160>(50s)</c>",
		DisplayPriority = 15,
		Description = "Unlocks the GVB Bakha Strike Bomber.",
		TargetType = Ship,
		TargetName = "vas_bakha",
		Icon = Icon_Build,
		ShortDisplayedName = "Bakha <c=0e0160>(50s)</c>",
	},
	{
		Name = "Sehkmet",
		RequiredResearch = "Bakha & FS2",
		RequiredSubSystems = "",
		Cost = 1800,
		Time = 60,
		DisplayedName = "Sehkmet <c=0e0160>(60s)</c>",
		DisplayPriority = 26,
		Description = "Unlocks the GVB Sehkmet Heavy Bomber.",
		TargetType = Ship,
		TargetName = "vas_sehkmet",
		Icon = Icon_Build,
		ShortDisplayedName = "Sehkmet <c=0e0160>(60s)</c>",
	},
	{
		Name = "Amun",
		RequiredResearch = "BomberDesign & FS1",
		RequiredSubSystems = "",
		Cost = 1400,
		Time = 50,
		DisplayedName = "Amun <c=0e0160>(50s)</c>",
		DisplayPriority = 25,
		Description = "Unlocks the PVB Amun Heavy Bomber.",
		TargetType = Ship,
		TargetName = "vas_amun",
		Icon = Icon_Build,
		ShortDisplayedName = "Amun <c=0e0160>(50s)</c>",
	},

	-- Cruisers --------------
	{
		Name = "CruiserDesign",
		RequiredResearch = "BomberDesign",
		RequiredSubSystems = "",
		Cost = 4000,
		Time = 120,
		DisplayedName = "Cruiser Design <c=0e0160>(120s)</c>",
		DisplayPriority = 3,
		Description = "Cruiser chassis and drives. Required for all Vasudan Cruiser class research.",
		TargetType = Ship,
		TargetName = "vas_aten_fs1",
		Icon = Icon_Build,
		ShortDisplayedName = "Cruiser Design <c=0e0160>(120s)</c>",
	},
	{
		Name = "Mentu",
		RequiredResearch = "CruiserDesign & FS2",
		RequiredSubSystems = "",
		Cost = 2000,
		Time = 60,
		DisplayedName = "Mentu <c=0e0160>(60s)</c>",
		DisplayPriority = 21,
		Description = "Unlocks the GVC Mentu Advanced Cruiser.",
		TargetType = Ship,
		TargetName = "vas_mentu",
		Icon = Icon_Build,
		ShortDisplayedName = "Mentu <c=0e0160>(60s)</c>",
	},
	{
		Name = "ScienceVessel",
		RequiredResearch = "CruiserDesign",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Science Vessel <c=0e0160>(50s)</c>",
		DisplayPriority = 25,
		Description = "Unlocks Science Vessels: Imhotep.",
		TargetType = Ship,
		TargetName = "vas_imhotep",
		Icon = Icon_Build,
		ShortDisplayedName = "Science Vessel <c=0e0160>(50s)</c>",
	},

	-- Capital Ships ---------
	{
		Name = "CapitalShipDesign",
		RequiredResearch = "CruiserDesign",
		RequiredSubSystems = "",
		Cost = 8000,
		Time = 150,
		DisplayedName = "Capital Ship Design <c=0e0160>(150s)</c>",
		DisplayPriority = 4,
		Description = "Capital ship chassis and drives. Required for all Vasudan Capital class research.",
		TargetType = Ship,
		TargetName = "vas_typhon_fs1",
		Icon = Icon_Build,
		ShortDisplayedName = "Capital Ship Design <c=0e0160>(150s)</c>",
	},
	{
		Name = "Sobek",
		RequiredResearch = "CapitalShipDesign & FS2",
		RequiredSubSystems = "",
		Cost = 2000,
		Time = 60,
		DisplayedName = "Sobek <c=0e0160>(60s)</c>",
		DisplayPriority = 15,
		Description = "Unlocks the GVCv Sobek Corvette.",
		TargetType = Ship,
		TargetName = "vas_sobek",
		Icon = Icon_Build,
		ShortDisplayedName = "Sobek <c=0e0160>(60s)</c>",
	},
	{
		Name = "SobekArmor",
		RequiredResearch = "Sobek",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Sobek Armor <c=0e0160>(50s)</c>",
		DisplayPriority = 16,
		Description = "Increases health of GVCv Sobek by 12.5%.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "vas_sobek",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.125,
		Icon = Icon_Health,
		ShortDisplayedName = "Sobek Armor <c=0e0160>(50s)</c>",
	},
	{
		Name = "SobekSprint",
		RequiredResearch = "Sobek",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Sobek Sprint <c=0e0160>(50s)</c>",
		DisplayPriority = 17,
		Description = "Improves the top speed of GVCv Sobek by 25%.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "vas_sobek",
		UpgradeName = "MaxSpeed",
		UpgradeValue = 1.25,
		Icon = Icon_Speed,
		ShortDisplayedName = "Sobek Sprint <c=0e0160>(50s)</c>",
	},
	{
		Name = "Hatshepsut",
		RequiredResearch = "CapitalShipDesign & FS2",
		RequiredSubSystems = "",
		Cost = 3500,
		Time = 90,
		DisplayedName = "Hatshepsut <c=0e0160>(90s)</c>",
		DisplayPriority = 36,
		Description = "Unlocks the GVD Hatshepsut Destroyer.",
		TargetType = Ship,
		TargetName = "vas_hatshepsut",
		Icon = Icon_Build,
		ShortDisplayedName = "Hatshepsut <c=0e0160>(90s)</c>",
	},
	{
		Name = "Installation",
		RequiredResearch = "CapitalShipDesign",
		RequiredSubSystems = "",
		Cost = 2500,
		Time = 75,
		DisplayedName = "Installation <c=0e0160>(75s)</c>",
		DisplayPriority = 13,
		Description = "Unlocks Installations: Karnak.",
		TargetType = Ship,
		TargetName = "vas_karnak",
		Icon = Icon_Build,
		ShortDisplayedName = "Installation <c=0e0160>(75s)</c>",
	},
	{
		Name = "SuperCapitalShipDesign",
		RequiredResearch = "CapitalShipDesign & Installation",
		RequiredSubSystems = "",
		Cost = 8000,
		Time = 180,
		DisplayedName = "Super Capital Ship Design <c=0e0160>(180s)</c>",
		DisplayPriority = 5,
		Description = "Unlocks Super Capital Ships.",
		TargetType = Ship,
		TargetName = "vas_hatshepsut",
		Icon = Icon_Build,
		ShortDisplayedName = "Super Capital Ship Design <c=0e0160>(180s)</c>",
	},
	{
		Name = "Juggernaut",
		RequiredResearch = "Installation & FS2",
		RequiredSubSystems = "",
		Cost = 20000,
		Time = 240,
		DisplayedName = "Juggernaut <c=0e0160>(240s)</c>",
		DisplayPriority = 31,
		Description = "Unlocks the GTVA Colossus Juggernaut.",
		TargetType = Ship,
		TargetName = "vas_colossus",
		Icon = Icon_Build,
		ShortDisplayedName = "Juggernaut <c=0e0160>(240s)</c>",
	},

	-- Platforms -------------
	{
		Name = "SentryGun",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Sentry Gun <c=0e0160>(50s)</c>",
		DisplayPriority = 17,
		Description = "Unlocks Sentry Guns: Edjo, Ankh.",
		TargetType = Ship,
		TargetName = "vas_edjo",
		Icon = Icon_Build,
		ShortDisplayedName = "Sentry Gun <c=0e0160>(50s)</c>",
	},
	{
		Name = "SentryAndMineDeployer",
		RequiredResearch = "SentryGun",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Sentry And Mine Deployer <c=0e0160>(50s)</c>",
		DisplayPriority = 16,
		Description = "Unlocks Sentry and Mine Deployers: Bes, Ma'at.",
		TargetType = Ship,
		TargetName = "vas_maat",
		Icon = Icon_Build,
		ShortDisplayedName = "Sentry And Mine Deployer <c=0e0160>(50s)</c>",
	},
	{
		Name = "BeamSentry",
		RequiredResearch = "SentryAndMineDeployer & FS2",
		RequiredSubSystems = "",
		Cost = 3000,
		Time = 90,
		DisplayedName = "Beam Sentry <c=0e0160>(90s)</c>",
		DisplayPriority = 18,
		Description = "Unlocks Remote Beam Cannons: Mjolnir.",
		TargetType = Ship,
		TargetName = "ter_mjolnir",
		Icon = Icon_Build,
		ShortDisplayedName = "Beam Sentry <c=0e0160>(90s)</c>",
	},
	-- Utility ---------------
	{
		Name = "AWACS",
		RequiredResearch = "CruiserDesign & FS2",
		RequiredSubSystems = "",
		Cost = 2500,
		Time = 50,
		DisplayedName = "AWACS <c=0e0160>(50s)</c>",
		DisplayPriority = 30,
		Description = "Unlocks AWACS vessels: Setekh.",
		TargetType = Ship,
		TargetName = "vas_setekh",
		Icon = Icon_Build,
		ShortDisplayedName = "AWACS <c=0e0160>(50s)</c>",
	},

	{
		Name = "RepairSatis",
		RequiredResearch = "CruiserDesign & FS1",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Repair Satis <c=0e0160>(50s)</c>",
		DisplayPriority = 30,
		Description = "Unlocks Repair Frigate Satis.",
		TargetType = Ship,
		TargetName = "vas_satis",
		Icon = Icon_Build,
		ShortDisplayedName = "Repair Satis <c=0e0160>(50s)</c>",
	},
	{
		Name = "RepairBast",
		RequiredResearch = "CruiserDesign & FS2",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Repair Bast <c=0e0160>(50s)</c>",
		DisplayPriority = 30,
		Description = "Unlocks Repair Frigate Bast.",
		TargetType = Ship,
		TargetName = "vas_bast",
		Icon = Icon_Build,
		ShortDisplayedName = "Repair Bast <c=0e0160>(50s)</c>",
	},

	-- AI Only Nodes ---------
	{
		Name = "cpuplayers_defensive",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_aggressive",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_dynamic",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_norushtime5",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_norushtime10",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_norushtime15",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "AllShipBuildSpeed",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Capital",
		UpgradeName = "BUILDSPEED",
		UpgradeValue = 1.025,
		AIOnly = 1,
	},
	{
		Name = "AllShipBuildSpeedHard",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Capital",
		UpgradeName = "BUILDSPEED",
		UpgradeValue = 1.25,
		AIOnly = 1,
	},
	{
		Name = "AllShipBuildSpeedExpert",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Capital",
		UpgradeName = "BUILDSPEED",
		UpgradeValue = 1.5,
		AIOnly = 1,
	},
	{
		Name = "ResourceCollectionRateHard",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "vas_isis",
		UpgradeName = "ResourceCollectionRate",
		UpgradeValue = 1.15,
		AIOnly = 1,
	},
	{
		Name = "ResourceCollectionRateExpert",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "vas_isis",
		UpgradeName = "ResourceCollectionRate",
		UpgradeValue = 1.30,
		AIOnly = 1,
	},
	{
		Name = "HeavyGuns",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "AWACSLVL2",
		RequiredResearch = "AWACS",
		RequiredSubSystems = "",
		Cost = 2500,
		Time = 50,
		DisplayPriority = 1,
		Description = "Enhanced defensive Electronic Warfare (EW) suite for GTA Charybids AWACS. Friendly ships are are detected in 70% of normal range while in AWACS area.",
		TargetType = Ship,
		TargetName = "ter_charybdis",
		UpgradeType = Modifier,
		UpgradeName = "SensorDistortion",
		UpgradeValue = 0.7,
		Icon = Icon_Health,
		ShortDisplayedName = "AWACS Level II",
	},
	{
		Name = "AWACSLVL3",
		RequiredResearch = "AWACSLVL2",
		RequiredSubSystems = "",
		Cost = 2500,
		Time = 50,
		DisplayedName = "AWACS LVL3 - Offensive EW<c=0e0160>(50s)</c>",
		DisplayPriority = 1,
		Description = "Enhanced offensive Electronic Warfare (EW) suite for GTA Charybids AWACS. Enemy vessels have 30% reduced accuracy while in friendly AWACS range.",
		TargetType = Ship,
		TargetName = "ter_charybdis",
		UpgradeType = Ability,
		UpgradeName = "SensorPing",
		Icon = Icon_Ability,
		ShortDisplayedName = "AWACS Level III",
	},
}
