Icon_Speed = "data:ui/newui/research/icons/speed.mres"
Icon_Health = "data:ui/newui/research/icons/health.mres"
Icon_Tech = "data:ui/newui/research/icons/tech.mres"
Icon_Ability = "data:ui/newui/research/icons/ability.mres"
Icon_Build = "data:ui/newui/research/icons/build.mres"

Modifier = 0
Ability = 1
AllShips = 0
Family = 1
Ship = 2

research = {
	{
		Name = "FS1",
		RequiredResearch = "",
		RequiredSubSystems = "",
		--DoNotGrant = 1,
		Cost = 10,
		Time = 1,
		DisplayedName = "FreeSpace 1 Era",
		DisplayPriority = 0,
		Description = "Activates FreeSpace 1 ships and technology.",
		Icon = Icon_Tech,
		ShortDisplayedName = "FS1 Era",
	},
	{
		Name = "FS2",
		RequiredResearch = "",
		RequiredSubSystems = "",
		--DoNotGrant = 1,
		Cost = 10,
		Time = 1,
		DisplayedName = "FreeSpace 2 Era",
		DisplayPriority = 0,
		Description = "Activates FreeSpace 2 ships and technology.",
		Icon = Icon_Tech,
		ShortDisplayedName = "FS2 Era",
	},

	-- Fighters --------------
	{
		Name = "FighterDesign",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1200,
		Time = 40,
		DisplayedName = "Fighter Design <c=0e0160>(40s)</c>",
		DisplayPriority = 1,
		Description = "Fighter chassis and drives. Required for all Shivan Fighter class research.",
		Icon = Icon_Build,
		TargetType = Family,
		TargetName = "Fighter",
		ShortDisplayedName = "Fighter Design",
	},
	{
		Name = "Manticore",
		RequiredResearch = "FighterDesign",
		RequiredSubSystems = "",
		Cost = 850,
		Time = 40,
		DisplayedName = "SF Manticore <c=0e0160>(40s)</c>",
		DisplayPriority = 19,
		Description = "Unlocks the SF Manticore Interceptor.",
		TargetType = Ship,
		TargetName = "shi_manticore",
		Icon = Icon_Build,
		ShortDisplayedName = "Manticore",
	},
	{
		Name = "Dragon",
		RequiredResearch = "FighterDesign",
		RequiredSubSystems = "",
		Cost = 1200,
		Time = 50,
		DisplayedName = "SF Dragon <c=0e0160>(50s)</c>",
		DisplayPriority = 22,
		Description = "Unlocks the SF Dragon Superiority Fighter.",
		TargetType = Ship,
		TargetName = "shi_dragon",
		Icon = Icon_Build,
		ShortDisplayedName = "Dragon",
	},
	{
		Name = "Basilisk",
		RequiredResearch = "FighterDesign & FS1",
		RequiredSubSystems = "",
		Cost = 1200,
		Time = 50,
		DisplayedName = "SF Basilisk <c=0e0160>(50s)</c>",
		DisplayPriority = 22,
		Description = "Unlocks the SF Basilisk Assault Fighter.",
		TargetType = Ship,
		TargetName = "shi_basilisk",
		Icon = Icon_Build,
		ShortDisplayedName = "Basilisk",
	},
	{
		Name = "Aeshma",
		RequiredResearch = "FighterDesign & FS2",
		RequiredSubSystems = "",
		Cost = 1200,
		Time = 50,
		DisplayedName = "SF Aeshma <c=0e0160>(50s)</c>",
		DisplayPriority = 19,
		Description = "Unlocks the SF Aeshma Assault Fighter.",
		TargetType = Ship,
		TargetName = "shi_aeshma",
		Icon = Icon_Build,
		ShortDisplayedName = "Aeshma",
	},
	{
		Name = "Mara",
		RequiredResearch = "FighterDesign & FS2",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 60,
		DisplayedName = "SF Mara <c=0e0160>(60s)</c>",
		DisplayPriority = 12,
		Description = "Unlocks the SF Mara Advanced Superiority Fighter.",
		TargetType = Ship,
		TargetName = "shi_mara",
		Icon = Icon_Build,
		ShortDisplayedName = "Mara",
	},
	{
		Name = "Gorgon",
		RequiredResearch = "FighterDesign",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "SF Gorgon <c=0e0160>(50s)</c>",
		DisplayPriority = 19,
		Description = "Unlocks the SF Gorgon Advanced Assault Fighter.",
		TargetType = Ship,
		TargetName = "shi_gorgon",
		Icon = Icon_Build,
		ShortDisplayedName = "Gorgon",
	},

	-- Bombers ---------------
	{
		Name = "BomberDesign",
		RequiredResearch = "FighterDesign",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Bomber Design <c=0e0160>(50s)</c>",
		DisplayPriority = 2,
		Description = "Bomber chassis and drives. Required for all Shivan Bomber class research.",
		TargetType = Ship,
		TargetName = "shi_shaitan",
		Icon = Icon_Build,
		ShortDisplayedName = "Bomber Design",
	},
	{
		Name = "Shaitan",
		RequiredResearch = "BomberDesign & FS1",
		RequiredSubSystems = "",
		Cost = 1000,
		Time = 40,
		DisplayedName = "SB Shaitan <c=0e0160>(40s)</c>",
		DisplayPriority = 15,
		Description = "Unlocks the SB Shaitan Strike Bomber.",
		TargetType = Ship,
		TargetName = "shi_shaitan",
		Icon = Icon_Build,
		ShortDisplayedName = "Shaitan",
	},
	{
		Name = "Nahema",
		RequiredResearch = "BomberDesign & FS2",
		RequiredSubSystems = "",
		Cost = 1200,
		Time = 50,
		DisplayedName = "SB Nahema <c=0e0160>(50s)</c>",
		DisplayPriority = 15,
		Description = "Unlocks the SB Nahema Strike Bomber.",
		TargetType = Ship,
		TargetName = "shi_nahema",
		Icon = Icon_Build,
		ShortDisplayedName = "Nahema",
	},
	{
		Name = "Taurvi",
		RequiredResearch = "BomberDesign & FS2",
		RequiredSubSystems = "",
		Cost = 1400,
		Time = 50,
		DisplayedName = "SB Taurvi <c=0e0160>(50s)</c>",
		DisplayPriority = 15,
		Description = "Unlocks the SB Taurvi Medium Bomber.",
		TargetType = Ship,
		TargetName = "shi_taurvi",
		Icon = Icon_Build,
		ShortDisplayedName = "Taurvi",
	},
	{
		Name = "Nephilim",
		RequiredResearch = "BomberDesign",
		RequiredSubSystems = "",
		Cost = 1800,
		Time = 60,
		DisplayedName = "SB Nephilim <c=0e0160>(60s)</c>",
		DisplayPriority = 26,
		Description = "Unlocks the SB Nephilim Heavy Bomber.",
		TargetType = Ship,
		TargetName = "shi_nephilim",
		Icon = Icon_Build,
		ShortDisplayedName = "Nephilim",
	},
	{
		Name = "Seraphim",
		RequiredResearch = "BomberDesign & FS2",
		RequiredSubSystems = "",
		Cost = 2000,
		Time = 70,
		DisplayedName = "SB Seraphim <c=0e0160>(70s)</c>",
		DisplayPriority = 26,
		Description = "Unlocks the SB Seraphim Heavy Bomber.",
		TargetType = Ship,
		TargetName = "shi_seraphim",
		Icon = Icon_Build,
		ShortDisplayedName = "Seraphim",
	},

	-- Cruisers --------------
	{
		Name = "CruiserDesign",
		RequiredResearch = "BomberDesign",
		RequiredSubSystems = "",
		Cost = 8000,
		Time = 120,
		DisplayedName = "Cruiser Design <c=0e0160>(120s)</c>",
		DisplayPriority = 3,
		Description = "Cruiser chassis and drives. Required for all Shivan Cruiser class research.",
		TargetType = Ship,
		TargetName = "shi_cain",
		Icon = Icon_Build,
		ShortDisplayedName = "Cruiser Design",
	},
	{
		Name = "Cain",
		RequiredResearch = "CruiserDesign",
		RequiredSubSystems = "",
		Cost = 1000,
		Time = 50,
		DisplayedName = "SC Cain <c=0e0160>(50s)</c>",
		DisplayPriority = 18,
		Description = "Unlocks the SC Cain Strike Cruiser.",
		TargetType = Ship,
		TargetName = "shi_cain",
		Icon = Icon_Build,
		ShortDisplayedName = "Cain",
	},
	{
		Name = "Rakshasa",
		RequiredResearch = "CruiserDesign & FS2",
		RequiredSubSystems = "",
		Cost = 2000,
		Time = 60,
		DisplayedName = "SC Rakshasa <c=0e0160>(60s)</c>",
		DisplayPriority = 21,
		Description = "Unlocks the SC Rakshasa Advanced Cruiser.",
		TargetType = Ship,
		TargetName = "shi_rakshasa",
		Icon = Icon_Build,
		ShortDisplayedName = "Rakshasa",
	},
	{
		Name = "Lilith",
		RequiredResearch = "CruiserDesign",
		RequiredSubSystems = "",
		Cost = 2500,
		Time = 70,
		DisplayedName = "SC Lilith <c=0e0160>(70s)</c>",
		DisplayPriority = 22,
		Description = "Unlocks the SC Lilith Heavy Cruiser.",
		TargetType = Ship,
		TargetName = "shi_lilith",
		Icon = Icon_Build,
		ShortDisplayedName = "Lilith",
	},

	-- Capital Ships ---------
	{
		Name = "CapitalShipDesign",
		RequiredResearch = "CruiserDesign",
		RequiredSubSystems = "",
		Cost = 5000,
		Time = 180,
		DisplayedName = "Capital Ship Design <c=0e0160>(180s)</c>",
		DisplayPriority = 4,
		Description = "Capital ship chassis and drives. Required for all Shivan Capital class research.",
		TargetType = Ship,
		TargetName = "shi_demon",
		Icon = Icon_Build,
		ShortDisplayedName = "Capital Ship Design",
	},
	{
		Name = "Moloch",
		RequiredResearch = "CapitalShipDesign & FS2",
		RequiredSubSystems = "",
		Cost = 2000,
		Time = 60,
		DisplayedName = "SCv Moloch <c=0e0160>(60s)</c>",
		DisplayPriority = 13,
		Description = "Unlocks the SCv Moloch Corvette.",
		TargetType = Ship,
		TargetName = "shi_moloch",
		Icon = Icon_Build,
		ShortDisplayedName = "Moloch",
	},
	{
		Name = "MolochArmor",
		RequiredResearch = "Moloch",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Moloch Armor <c=0e0160>(50s)</c>",
		DisplayPriority = 16,
		Description = "Increases health of SCv Moloch by 12.5%.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "shi_moloch",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.125,
		Icon = Icon_Health,
		ShortDisplayedName = "Moloch Armor Upgrade",
	},
	{
		Name = "MolochSprint",
		RequiredResearch = "Moloch",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Moloch Sprint Drive <c=0e0160>(50s)</c>",
		DisplayPriority = 17,
		Description = "Improves the top speed of SCv Moloch by 25%.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "shi_moloch",
		UpgradeName = "MaxSpeed",
		UpgradeValue = 1.25,
		Icon = Icon_Speed,
		ShortDisplayedName = "Moloch Sprint Drive",
	},
	{
		Name = "Ravana",
		RequiredResearch = "CapitalShipDesign & FS2",
		RequiredSubSystems = "",
		Cost = 4500,
		Time = 100,
		DisplayedName = "SD Ravana <c=0e0160>(100s)</c>",
		DisplayPriority = 36,
		Description = "Unlocks the SD Ravana Destroyer.",
		TargetType = Ship,
		TargetName = "shi_ravana",
		Icon = Icon_Build,
		ShortDisplayedName = "Ravana",
	},
	{
		Name = "Lucifer",
		RequiredResearch = "SuperCapitalShipDesign",
		RequiredSubSystems = "",
		Cost = 10000,
		Time = 110,
		DisplayedName = "SD Lucifer <c=0e0160>(110s)</c>",
		DisplayPriority = 31,
		Description = "Unlocks the SD Lucifer Super Destroyer.",
		TargetType = Ship,
		TargetName = "shi_lucifer",
		Icon = Icon_Build,
		ShortDisplayedName = "Lucifer",
	},
	{
		Name = "SuperCapitalShipDesign",
		RequiredResearch = "CapitalShipDesign",
		RequiredSubSystems = "",
		Cost = 8000,
		Time = 150,
		DisplayedName = "Super Capital Ship Design <c=0e0160>(150s)</c>",
		DisplayPriority = 5,
		Description = "Unlocks SJ Sathanas class juggernauts.",
		TargetType = Ship,
		TargetName = "shi_sathanas",
		Icon = Icon_Build,
		ShortDisplayedName = "Super Capital Design",
	},
	{
		Name = "Sathanas",
		RequiredResearch = "SuperCapitalShipDesign & FS2",
		RequiredSubSystems = "",
		Cost = 12000,
		Time = 200,
		DisplayedName = "SJ Sathanas <c=0e0160>(200s)</c>",
		DisplayPriority = 31,
		Description = "Unlocks the SJ Sathanas Juggernaut.",
		TargetType = Ship,
		TargetName = "shi_sathanas",
		Icon = Icon_Build,
		ShortDisplayedName = "Sathanas",
	},

	-- Platforms -------------
	{
		Name = "SentryGun",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Sentry Gun <c=0e0160>(50s)</c>",
		DisplayPriority = 17,
		Description = "Unlocks Sentry Guns: Belial, Trident.",
		TargetType = Ship,
		TargetName = "shi_belial",
		Icon = Icon_Build,
		ShortDisplayedName = "Sentry Gun",
	},

	-- Utility ---------------
	{
		Name = "AdvancedSensors",
		RequiredResearch = "CruiserDesign",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Advanced Sensors <c=0e0160>(50s)</c>",
		DisplayPriority = 25,
		Description = "Unlocks Advanced Sensors: Shivan Comm Node (AWACS).",
		TargetType = Ship,
		TargetName = "shi_commnode",
		Icon = Icon_Build,
		ShortDisplayedName = "Advanced Sensors",
	},

	-- AI Only Nodes ---------
	{
		Name = "cpuplayers_defensive",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_aggressive",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_dynamic",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_norushtime5",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_norushtime10",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_norushtime15",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "AllShipBuildSpeed",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Capital",
		UpgradeName = "BUILDSPEED",
		UpgradeValue = 1.025,
		AIOnly = 1,
	},
	{
		Name = "AllShipBuildSpeedHard",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Capital",
		UpgradeName = "BUILDSPEED",
		UpgradeValue = 1.05,
		AIOnly = 1,
	},
	{
		Name = "AllShipBuildSpeedExpert",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Capital",
		UpgradeName = "BUILDSPEED",
		UpgradeValue = 1.075,
		AIOnly = 1,
	},
	{
		Name = "ResourceCollectionRateHard",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "shi_azrael",
		UpgradeName = "ResourceCollectionRate",
		UpgradeValue = 1.15,
		AIOnly = 1,
	},
	{
		Name = "ResourceCollectionRateExpert",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "shi_azrael",
		UpgradeName = "ResourceCollectionRate",
		UpgradeValue = 1.30,
		AIOnly = 1,
	},
	{
		Name = "HeavyGuns",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
}
