Icon_Speed = "data:ui/newui/research/icons/speed.mres"
Icon_Health = "data:ui/newui/research/icons/health.mres"
Icon_Tech = "data:ui/newui/research/icons/tech.mres"
Icon_Ability = "data:ui/newui/research/icons/ability.mres"
Icon_Build = "data:ui/newui/research/icons/build.mres"

Modifier = 0
Ability = 1
AllShips = 0
Family = 1
Ship = 2

research = {
	{
		Name = "FS1",
		RequiredResearch = "",
		RequiredSubSystems = "",
		--DoNotGrant = 1,
		Cost = 10,
		Time = 1,
		DisplayedName = "FreeSpace 1 Era",
		DisplayPriority = 0,
		Description = "Activates FreeSpace 1 ships and technology.",
		Icon = Icon_Tech,
		ShortDisplayedName = "FS1 Era",
	},
	{
		Name = "FS2",
		RequiredResearch = "",
		RequiredSubSystems = "",
		--DoNotGrant = 1,
		Cost = 10,
		Time = 1,
		DisplayedName = "FreeSpace 2 Era",
		DisplayPriority = 0,
		Description = "Activates FreeSpace 2 ships and technology.",
		Icon = Icon_Tech,
		ShortDisplayedName = "FS2 Era",
	},

	-- Fighters --------------
	{
		Name = "FighterDesign",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1200,
		Time = 40,
		DisplayedName = "Fighter Design <c=0e0160>(40s)</c>",
		DisplayPriority = 1,
		Description = "Fighter chassis and drives. Required for all Shivan Fighter class research.",
		Icon = Icon_Build,
		TargetType = Ship,
		TargetName = "shi_scorpion",
		ShortDisplayedName = "Fighter Design <c=0e0160>(40s)</c>",
	},
	{
		Name = "Manticore",
		RequiredResearch = "FighterDesign",
		RequiredSubSystems = "",
		Cost = 850,
		Time = 40,
		DisplayedName = "Manticore <c=0e0160>(40s)</c>",
		DisplayPriority = 2,
		Description = "Unlocks the SF Manticore Interceptor.",
		TargetType = Ship,
		TargetName = "shi_manticore",
		Icon = Icon_Build,
		ShortDisplayedName = "Manticore <c=0e0160>(40s)</c>",
	},
	{
		Name = "Dragon",
		RequiredResearch = "Manticore",
		RequiredSubSystems = "",
		Cost = 1200,
		Time = 50,
		DisplayedName = "Dragon <c=0e0160>(50s)</c>",
		DisplayPriority = 3,
		Description = "Unlocks the SF Dragon Superiority Fighter.",
		TargetType = Ship,
		TargetName = "shi_dragon",
		Icon = Icon_Build,
		ShortDisplayedName = "Dragon <c=0e0160>(50s)</c>",
	},
	{
		Name = "Basilisk",
		RequiredResearch = "Manticore",
		RequiredSubSystems = "",
		Cost = 1200,
		Time = 50,
		DisplayedName = "Basilisk <c=0e0160>(50s)</c>",
		DisplayPriority = 4,
		Description = "Unlocks the SF Basilisk Assault Fighter.",
		TargetType = Ship,
		TargetName = "shi_basilisk",
		Icon = Icon_Build,
		ShortDisplayedName = "Basilisk <c=0e0160>(50s)</c>",
	},
	{
		Name = "Gorgon",
		RequiredResearch = "Basilisk",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Gorgon <c=0e0160>(50s)</c>",
		DisplayPriority = 5,
		Description = "Unlocks the SF Gorgon Advanced Assault Fighter.",
		TargetType = Ship,
		TargetName = "shi_gorgon",
		Icon = Icon_Build,
		ShortDisplayedName = "Gorgon <c=0e0160>(50s)</c>",
	},
	{
		Name = "Mara",
		RequiredResearch = "Dragon & FS2",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 60,
		DisplayedName = "Mara <c=0e0160>(60s)</c>",
		DisplayPriority = 6,
		Description = "Unlocks the SF Mara Advanced Superiority Fighter.",
		TargetType = Ship,
		TargetName = "shi_mara",
		Icon = Icon_Build,
		ShortDisplayedName = "Mara <c=0e0160>(60s)</c>",
	},
	{
		Name = "Aeshma",
		RequiredResearch = "Gorgon & FS2",
		RequiredSubSystems = "",
		Cost = 1200,
		Time = 50,
		DisplayedName = "Aeshma <c=0e0160>(50s)</c>",
		DisplayPriority = 7,
		Description = "Unlocks the SF Aeshma Assault Fighter.",
		TargetType = Ship,
		TargetName = "shi_aeshma",
		Icon = Icon_Build,
		ShortDisplayedName = "Aeshma <c=0e0160>(50s)</c>",
	},

	-- Bombers ---------------
	{
		Name = "BomberDesign",
		RequiredResearch = "FighterDesign",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Bomber Design <c=0e0160>(50s)</c>",
		DisplayPriority = 1,
		Description = "Bomber chassis and drives. Required for all Shivan Bomber class research.",
		TargetType = Ship,
		TargetName = "shi_nephilim",
		Icon = Icon_Build,
		ShortDisplayedName = "Bomber Design <c=0e0160>(50s)</c>",
	},
	{
		Name = "Taurvi",
		RequiredResearch = "BomberDesign & FS2",
		RequiredSubSystems = "",
		Cost = 1400,
		Time = 50,
		DisplayedName = "Taurvi <c=0e0160>(50s)</c>",
		DisplayPriority = 2,
		Description = "Unlocks the SB Taurvi Medium Bomber.",
		TargetType = Ship,
		TargetName = "shi_taurvi",
		Icon = Icon_Build,
		ShortDisplayedName = "Taurvi <c=0e0160>(50s)</c>",
	},
	{
		Name = "Nephilim",
		RequiredResearch = "BomberDesign",
		RequiredSubSystems = "",
		Cost = 1800,
		Time = 60,
		DisplayedName = "Nephilim <c=0e0160>(60s)</c>",
		DisplayPriority = 3,
		Description = "Unlocks the SB Nephilim Heavy Bomber.",
		TargetType = Ship,
		TargetName = "shi_nephilim",
		Icon = Icon_Build,
		ShortDisplayedName = "Nephilim <c=0e0160>(60s)</c>",
	},
	{
		Name = "Seraphim",
		RequiredResearch = "Nephilim & FS2",
		RequiredSubSystems = "",
		Cost = 2000,
		Time = 70,
		DisplayedName = "Seraphim <c=0e0160>(70s)</c>",
		DisplayPriority = 4,
		Description = "Unlocks the SB Seraphim Heavy Bomber.",
		TargetType = Ship,
		TargetName = "shi_seraphim",
		Icon = Icon_Build,
		ShortDisplayedName = "Seraphim <c=0e0160>(70s)</c>",
	},

	-- Cruisers --------------
	{
		Name = "CruiserDesign",
		RequiredResearch = "BomberDesign",
		RequiredSubSystems = "",
		Cost = 4000,
		Time = 120,
		DisplayedName = "Cruiser Design <c=0e0160>(120s)</c>",
		DisplayPriority = 1,
		Description = "Cruiser chassis and drives. Required for all Shivan Cruiser class research.",
		TargetType = Ship,
		TargetName = "shi_cain",
		Icon = Icon_Build,
		ShortDisplayedName = "Cruiser Design <c=0e0160>(120s)</c>",
	},
	{
		Name = "Lilith",
		RequiredResearch = "CruiserDesign",
		RequiredSubSystems = "",
		Cost = 2500,
		Time = 70,
		DisplayedName = "SC Lilith <c=0e0160>(70s)</c>",
		DisplayPriority = 2,
		Description = "Unlocks the SC Lilith Heavy Cruiser.",
		TargetType = Ship,
		TargetName = "shi_lilith",
		Icon = Icon_Build,
		ShortDisplayedName = "Lilith",
	},
	{
		Name = "Rakshasa",
		RequiredResearch = "Lilith & FS2",
		RequiredSubSystems = "",
		Cost = 2000,
		Time = 60,
		DisplayedName = "Rakshasa <c=0e0160>(60s)</c>",
		DisplayPriority = 3,
		Description = "Unlocks the SC Rakshasa Advanced Cruiser.",
		TargetType = Ship,
		TargetName = "shi_rakshasa",
		Icon = Icon_Build,
		ShortDisplayedName = "Rakshasa <c=0e0160>(60s)</c>",
	},

	-- Capital Ships ---------
	{
		Name = "CapitalShipDesign",
		RequiredResearch = "CruiserDesign",
		RequiredSubSystems = "",
		Cost = 8000,
		Time = 150,
		DisplayedName = "Capital Ship Design <c=0e0160>(150s)</c>",
		DisplayPriority = 1,
		Description = "Capital ship chassis and drives. Required for all Shivan Capital class research.",
		TargetType = Ship,
		TargetName = "shi_demon",
		Icon = Icon_Build,
		ShortDisplayedName = "Capital Ship Design <c=0e0160>(150s)</c>",
	},
	{
		Name = "Moloch",
		RequiredResearch = "CapitalShipDesign & FS2",
		RequiredSubSystems = "",
		Cost = 2000,
		Time = 60,
		DisplayedName = "Moloch <c=0e0160>(60s)</c>",
		DisplayPriority = 2,
		Description = "Unlocks the SCv Moloch Corvette.",
		TargetType = Ship,
		TargetName = "shi_moloch",
		Icon = Icon_Build,
		ShortDisplayedName = "Moloch <c=0e0160>(60s)</c>",
	},
	{
		Name = "MolochArmor",
		RequiredResearch = "Moloch",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Moloch Armor <c=0e0160>(50s)</c>",
		DisplayPriority = 3,
		Description = "Increases health of SCv Moloch by 12.5%.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "shi_moloch",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.125,
		Icon = Icon_Health,
		ShortDisplayedName = "Moloch Armor <c=0e0160>(50s)</c>",
	},
	{
		Name = "MolochSprint",
		RequiredResearch = "Moloch",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Moloch Sprint <c=0e0160>(50s)</c>",
		DisplayPriority = 4,
		Description = "Improves the top speed of SCv Moloch by 25%.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "shi_moloch",
		UpgradeName = "MaxSpeed",
		UpgradeValue = 1.25,
		Icon = Icon_Speed,
		ShortDisplayedName = "Moloch Sprint <c=0e0160>(50s)</c>",
	},
	{
		Name = "Ravana",
		RequiredResearch = "CapitalShipDesign & FS2",
		RequiredSubSystems = "",
		Cost = 4500,
		Time = 100,
		DisplayedName = "Ravana <c=0e0160>(100s)</c>",
		DisplayPriority = 5,
		Description = "Unlocks the SD Ravana Destroyer.",
		TargetType = Ship,
		TargetName = "shi_ravana",
		Icon = Icon_Build,
		ShortDisplayedName = "Ravana <c=0e0160>(100s)</c>",
	},
	{
		Name = "SuperCapitalShipDesign",
		RequiredResearch = "Ravana | (FS1 & CapitalShipDesign)",
		RequiredSubSystems = "",
		Cost = 8000,
		Time = 180,
		DisplayedName = "Super Capital Ship Design <c=0e0160>(180s)</c>",
		DisplayPriority = 6,
		Description = "Unlocks the SD Lucifer Super Destroyer.",
		TargetType = Ship,
		TargetName = "shi_lucifer",
		Icon = Icon_Build,
		ShortDisplayedName = "Super Capital Ship Design <c=0e0160>(180s)</c>",
	},
	{
		Name = "Juggernaut",
		RequiredResearch = "SuperCapitalShipDesign & FS2",
		RequiredSubSystems = "",
		Cost = 12000,
		Time = 240,
		DisplayedName = "Juggernaut <c=0e0160>(240s)</c>",
		DisplayPriority = 7,
		Description = "Unlocks the SJ Sathanas Juggernaut.",
		TargetType = Ship,
		TargetName = "shi_sathanas",
		Icon = Icon_Build,
		ShortDisplayedName = "Juggernaut <c=0e0160>(240s)</c>",
	},

	-- Platforms -------------
	{
		Name = "SentryGun",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Sentry Gun <c=0e0160>(50s)</c>",
		DisplayPriority = 1,
		Description = "Unlocks Sentry Guns: Belial, Trident.",
		TargetType = Ship,
		TargetName = "shi_belial",
		Icon = Icon_Build,
		ShortDisplayedName = "Sentry Gun <c=0e0160>(50s)</c>",
	},
	{
		Name = "SentryAndMineDeployer",
		RequiredResearch = "SentryGun",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Sentry And Mine Deployer <c=0e0160>(50s)</c>",
		DisplayPriority = 2,
		Description = "Unlocks ST Mephisto.",
		TargetType = Ship,
		TargetName = "shi_mephisto",
		Icon = Icon_Build,
		ShortDisplayedName = "Sentry And Mine Deployer",
	},

	-- Utility ---------------
	{
		Name = "AWACS",
		RequiredResearch = "CruiserDesign",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "AWACS <c=0e0160>(50s)</c>",
		DisplayPriority = 1,
		Description = "Unlocks Shivan Comm Node (AWACS).",
		TargetType = Ship,
		TargetName = "shi_commnode",
		Icon = Icon_Build,
		ShortDisplayedName = "AWACS <c=0e0160>(50s)</c>",
	},
	{
		Name = "RepairFrigate",
		RequiredResearch = "CruiserDesign",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Repair Frigate <c=0e0160>(50s)</c>",
		DisplayPriority = 2,
		Description = "Unlocks ST Asmodeus.",
		TargetType = Ship,
		TargetName = "shi_asmodeus",
		Icon = Icon_Build,
		ShortDisplayedName = "Repair Frigate",
	},

	-- Subsystems
	{
		Name = "AWACSLVL2",
		RequiredResearch = "AWACS",
		RequiredSubSystems = "",
		Cost = 2500,
		Time = 50,
		DisplayPriority = 1,
		DisplayedName = "AWACS LVL2 - Defensive EW<c=0e0160>(50s)</c>",
		Description = "Enhanced defensive Electronic Warfare (EW) suite for GTA Charybids AWACS. Friendly ships are are detected in 70% of normal range while in AWACS area.",
		TargetType = Ship,
		TargetName = "shi_commnode",
		UpgradeType = Modifier,
		UpgradeName = "SensorDistortion",
		UpgradeValue = 0.7,
		Icon = Icon_Health,
		ShortDisplayedName = "AWACS Level II",
	},
	{
		Name = "AWACSLVL3",
		RequiredResearch = "AWACSLVL2",
		RequiredSubSystems = "",
		Cost = 2500,
		Time = 50,
		DisplayedName = "AWACS LVL3 - Offensive EW<c=0e0160>(50s)</c>",
		DisplayPriority = 2,
		Description = "Enhanced offensive Electronic Warfare (EW) suite for GTA Charybids AWACS. Enemy vessels have 30% reduced accuracy while in friendly AWACS range.",
		TargetType = Ship,
		TargetName = "shi_commnode",
		UpgradeType = Ability,
		UpgradeName = "SensorPing",
		Icon = Icon_Ability,
		ShortDisplayedName = "AWACS Level III",
	},

	-- AI Only Nodes ---------
	{
		Name = "cpuplayers_defensive",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_aggressive",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_dynamic",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_norushtime5",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_norushtime10",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_norushtime15",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "AllShipBuildSpeed",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Capital",
		UpgradeName = "BUILDSPEED",
		UpgradeValue = 1.025,
		AIOnly = 1,
	},
	{
		Name = "AllShipBuildSpeedHard",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Capital",
		UpgradeName = "BUILDSPEED",
		UpgradeValue = 1.25,
		AIOnly = 1,
	},
	{
		Name = "AllShipBuildSpeedExpert",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Capital",
		UpgradeName = "BUILDSPEED",
		UpgradeValue = 1.5,
		AIOnly = 1,
	},
	{
		Name = "ResourceCollectionRateHard",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "shi_azrael",
		UpgradeName = "ResourceCollectionRate",
		UpgradeValue = 1.15,
		AIOnly = 1,
	},
	{
		Name = "ResourceCollectionRateExpert",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "shi_azrael",
		UpgradeName = "ResourceCollectionRate",
		UpgradeValue = 1.30,
		AIOnly = 1,
	},
	{
		Name = "HeavyGuns",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
}
