--Type => SubSystem
--ThingToBuild => name of subsystem to build
--RequiredResearch => global research dependencies
--RequiredShipSubSystems => subsystems dependencies for local to the ship
--RequiredFleetSubSystems => Fleet wide subsystem dependencies
--DisplayPriority => Order in UI lists
--DisplayedName => Localized name for UI
--Description => Description for UI

Ship = 0
SubSystem = 1
build = {

	{
		Type = SubSystem,
		ThingToBuild = "ter_orion_nameplate_bastion",
		RequiredResearch = "DONOTSHOW",
		RequiredShipSubSystems = "",
		DisplayPriority = 12,
		DisplayedName = "GTD Orion",
		Description = "GTD Orion",
	},
	{
		Type = SubSystem,
		ThingToBuild = "ter_orion_nameplate_carthage",
		RequiredResearch = "DONOTSHOW",
		RequiredShipSubSystems = "",
		DisplayPriority = 121,
		DisplayedName = "GTD Orion",
		Description = "GTD Orion",
	},
	{
		Type = SubSystem,
		ThingToBuild = "ter_orion_nameplate_delacroix",
		RequiredResearch = "DONOTSHOW",
		RequiredShipSubSystems = "",
		DisplayPriority = 12,
		DisplayedName = "GTD Orion",
		Description = "GTD Orion",
	},
	{
		Type = SubSystem,
		ThingToBuild = "ter_orion_nameplate_intrepid",
		RequiredResearch = "DONOTSHOW",
		RequiredShipSubSystems = "",
		DisplayPriority = 12,
		DisplayedName = "GTD Orion",
		Description = "GTD Orion",
	},
	{
		Type = SubSystem,
		ThingToBuild = "ter_orion_nameplate_messana",
		RequiredResearch = "DONOTSHOW",
		RequiredShipSubSystems = "",
		DisplayPriority = 12,
		DisplayedName = "GTD Orion",
		Description = "GTD Orion",
	},
	{
		Type = SubSystem,
		ThingToBuild = "ter_orion_nameplate_minnow",
		RequiredResearch = "DONOTSHOW",
		RequiredShipSubSystems = "",
		DisplayPriority = 12,
		DisplayedName = "GTD Orion",
		Description = "GTD Orion",
	},
	{
		Type = SubSystem,
		ThingToBuild = "ter_orion_nameplate_nereid",
		RequiredResearch = "DONOTSHOW",
		RequiredShipSubSystems = "",
		DisplayPriority = 12,
		DisplayedName = "GTD Orion",
		Description = "GTD Orion",
	},
	{
		Type = SubSystem,
		ThingToBuild = "ter_orion_nameplate_orion",
		RequiredResearch = "DONOTSHOW",
		RequiredShipSubSystems = "",
		DisplayPriority = 12,
		DisplayedName = "GTD Orion",
		Description = "GTD Orion",
	},
	{
		Type = SubSystem,
		ThingToBuild = "ter_orion_nameplate_soyakaze",
		RequiredResearch = "DONOTSHOW",
		RequiredShipSubSystems = "",
		DisplayPriority = 12,
		DisplayedName = "GTD Orion",
		Description = "GTD Orion",
	},
	{
		Type = SubSystem,
		ThingToBuild = "ter_orion_nameplate_galatea",
		RequiredResearch = "DONOTSHOW",
		RequiredShipSubSystems = "",
		DisplayPriority = 12,
		DisplayedName = "GTD Orion",
		Description = "GTD Orion",
	},
	{
		Type = SubSystem,
		ThingToBuild = "ter_orion_nameplate_myrmidon",
		RequiredResearch = "DONOTSHOW",
		RequiredShipSubSystems = "",
		DisplayPriority = 12,
		DisplayedName = "GTD Orion",
		Description = "GTD Orion",
	},
	{
		Type = SubSystem,
		ThingToBuild = "ter_orion_nameplate_amadeus",
		RequiredResearch = "DONOTSHOW",
		RequiredShipSubSystems = "",
		DisplayPriority = 12,
		DisplayedName = "GTD Orion",
		Description = "GTD Orion",
	},
	{
		Type = SubSystem,
		ThingToBuild = "ter_orion_nameplate_eisenhower",
		RequiredResearch = "DONOTSHOW",
		RequiredShipSubSystems = "",
		DisplayPriority = 12,
		DisplayedName = "GTD Orion",
		Description = "GTD Orion",
	},
	{
		Type = SubSystem,
		ThingToBuild = "ter_orion_nameplate_goliath",
		RequiredResearch = "DONOTSHOW",
		RequiredShipSubSystems = "",
		DisplayPriority = 12,
		DisplayedName = "GTD Orion",
		Description = "GTD Orion",
	},
	{
		Type = SubSystem,
		ThingToBuild = "ter_hecate_nameplate_aquitaine",
		RequiredResearch = "DONOTSHOW",
		RequiredShipSubSystems = "",
		DisplayPriority = 12,
		DisplayedName = "GTD Orion",
		Description = "GTD Orion",
	},
	{
		Type = SubSystem,
		ThingToBuild = "ter_hecate_nameplate_hood",
		RequiredResearch = "DONOTSHOW",
		RequiredShipSubSystems = "",
		DisplayPriority = 12,
		DisplayedName = "GTD Orion",
		Description = "GTD Orion",
	},
	{
		Type = SubSystem,
		ThingToBuild = "ter_hecate_nameplate_meridian",
		RequiredResearch = "DONOTSHOW",
		RequiredShipSubSystems = "",
		DisplayPriority = 12,
		DisplayedName = "GTD Orion",
		Description = "GTD Orion",
	},
	{
		Type = SubSystem,
		ThingToBuild = "ter_hecate_nameplate_morgain",
		RequiredResearch = "DONOTSHOW",
		RequiredShipSubSystems = "",
		DisplayPriority = 12,
		DisplayedName = "GTD Orion",
		Description = "GTD Orion",
	},
	{
		Type = SubSystem,
		ThingToBuild = "ter_hecate_nameplate_phonecia",
		RequiredResearch = "DONOTSHOW",
		RequiredShipSubSystems = "",
		DisplayPriority = 12,
		DisplayedName = "GTD Orion",
		Description = "GTD Orion",
	},
	{
		Type = SubSystem,
		ThingToBuild = "ter_hecate_nameplate_requiem",
		RequiredResearch = "DONOTSHOW",
		RequiredShipSubSystems = "",
		DisplayPriority = 12,
		DisplayedName = "GTD Orion",
		Description = "GTD Orion",
	},
	{
		Type = SubSystem,
		ThingToBuild = "ter_hecate_nameplate_tempest",
		RequiredResearch = "DONOTSHOW",
		RequiredShipSubSystems = "",
		DisplayPriority = 12,
		DisplayedName = "GTD Orion",
		Description = "GTD Orion",
	},
	{
		Type = SubSystem,
		ThingToBuild = "ter_hecate_nameplate_warlock",
		RequiredResearch = "DONOTSHOW",
		RequiredShipSubSystems = "",
		DisplayPriority = 12,
		DisplayedName = "GTD Orion",
		Description = "GTD Orion",
	},

	{
		Type = Ship,
		ThingToBuild = "ter_loki",
		RequiredResearch = "FighterDesign",
		RequiredShipSubSystems = "",
		DisplayPriority = 20,
		DisplayedName = "GTF Loki - Recon <c=12AB06>29s</c>",
		Description =
		"<b>Description:</b> The GTF Loki is designated as a fighter, but it's more of a heavy reconnaissance craft. The Loki's micro-roughened hull and shielded exhaust chamber give it an extremely reduced profile to detection sensors. This makes it ideal for reconnaissance and infiltration missions that rely on stealth rather than firepower. Lacking the weaponry and armor to survive prolonged battles, the Loki can usually stay alive long enough for its high maneuverability and speed to discourage pursuers. Lokis are widely used by NTF forces. \n\n<b>Prerequisites:</b> Fighter Design. \n\n<b>Armaments:</b> 2x GTW Subach HL-7, 2x GTW-83 Lamprey, 1x GTM-19 Harpoon, 1x GTM-41 EMP Adv (Upgrade)",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_hercules",
		RequiredResearch = "Hercules",
		RequiredShipSubSystems = "",
		DisplayPriority = 13,
		DisplayedName = "GTF Hercules - Assault <c=12AB06>39s</c>",
		Description =
		"<b>Description:</b> The old workhorse of the Terran fleet, the Hercules is a beloved but aging design. It was the mainstay of the Terran forces during the Great War, but it is slowly being phased out of the modern fleet. As they are replaced by Herc IIs, Myrmidons, and other recent designs, Hercules fighters are increasingly relegated to training and guard duties far from the front lines. Pilots who've flown Hercs for years love the ship's heavy armor and firepower and have learned to compensate for its low speed and poor maneuverability. \n\n<b>Prerequisites:</b> Fighter Design, Hercules. \n\n<b>Armaments:</b> 4x GTW-5a Prometheus R, 2x GTW Subach HL-7, 2x GTM-4 Hornet, 2x GTM-MX6 Tempest.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_herculesmk2",
		RequiredResearch = "HerculesMk2 & FS2",
		RequiredShipSubSystems = "",
		DisplayPriority = 23,
		DisplayedName = "GTF Hercules Mk. II - Assault <c=12AB06>37s</c>",
		Description =
		"<b>Description:</b> The GTF Hercules Mark II is the next generation of Terran heavy assault fighter. Introduced during the Great War, the original Herc's balance of firepower and maneuverability made it the most versatile strike fighter in the fleet. Some military historians have claimed the Hercules won the Great War, citing its deployment in key battles near the end of the Shivan conflict. Implementing recent advances in fusion drive technology, the Mark II improves the assault fighter's speed and maneuverability without sacrificing loadout capacity. \n\n<b>Prerequisites:</b> Fighter Design, Hercules Mark II. \n\n<b>Armaments:</b> 2x GTW-5a Prometheus R, 2x GTW Subach HL-7, 2x GTM-4 Hornet (Tornado Upgrade), 2x GTM-MX6 Tempest.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_perseus",
		RequiredResearch = "Perseus & FS2",
		RequiredShipSubSystems = "",
		DisplayPriority = 21,
		DisplayedName = "GTF Perseus - Interceptor <c=12AB06>35s</c>",
		Description =
		"<b>Description:</b> The GTF Perseus is the newest fighter in the GTVA's arsenal. Slated to replace the aging Valkyrie as the Alliance's primary interceptor, the Perseus's high max speed and maneuverability make it ideal to hunt and destroy enemy bombers. Perseus fighters have been assigned to the 3rd Battle Group on a trial basis, with wide deployment expected after the OpEval period. Primary weapons include the Subach HL-7 and Prometheus cannon, with secondary loads of Harpoon and Hornet missiles. Preliminary results have shown the Perseus to be a superb fighter. \n\n<b>Prerequisites:</b> Fighter Design, Perseus. \n\n<b>Armaments:</b> 2x GTW-5 Prometheus S, 2x GTW Subach HL-7, 1x GTM-55 Trebuchet, 1x GTM-19 Harpoon.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_ulysses",
		RequiredResearch = "Ulysses & FS2",
		RequiredShipSubSystems = "",
		DisplayPriority = 12,
		DisplayedName = "GTF Ulysses - Superiority <c=12AB06>26s</c>",
		Description =
		"<b>Description:</b> Affectionately nicknamed The Bat by its pilots, the GTF Ulysses is a well-designed craft that has had a far longer useful life than its engineers ever imagined. Developed jointly by Terran and Vasudan contractors, the Ulysses was first deployed near the end of the Great War. Its excellent maneuverability and high top speed give it an agility that pilots love, but at a cost of thin armor and a small secondary weapon loadout. The Ulysses is a better choice for offensive missions than defensive ones. \n\n<b>Prerequisites:</b> Fighter Design, Ulysses. \n\n<b>Armaments:</b> 2x GTW Subach HL-7, 2x GTW ML-70 Morning Star, 1x GTM-19 Harpoon.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_ulysses_fs1",
		RequiredResearch = "Ulysses & FS1",
		RequiredShipSubSystems = "",
		DisplayPriority = 12,
		DisplayedName = "GTF Ulysses (FS1) - Superiority <c=12AB06>26s</c>",
		Description =
		"<b>Description:</b> Affectionately nicknamed The Bat by its pilots, the GTF Ulysses is a well-designed craft that has had a far longer useful life than its engineers ever imagined. Developed jointly by Terran and Vasudan contractors, the Ulysses was first deployed near the end of the Great War. Its excellent maneuverability and high top speed give it an agility that pilots love, but at a cost of thin armor and a small secondary weapon loadout. The Ulysses is a better choice for offensive missions than defensive ones. \n\n<b>Prerequisites:</b> Fighter Design, Ulysses. \n\n<b>Armaments:</b> 2x GTW ML-16 Laser, 2x GTW-15 Avenger, 1x GTM-19 Harpoon.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_myrmidon",
		RequiredResearch = "Myrmidon & FS2",
		RequiredShipSubSystems = "",
		DisplayPriority = 22,
		DisplayedName = "GTF Myrmidon - Adv. Superiority <c=12AB06>36s</c>",
		Description =
		"<b>Description:</b> RNI Systems' GTF Myrmidon replaces the Ulysses as the Alliance's primary space superiority fighter. The Myrmidon has received high marks for speed, maneuverability, armor, and loadout. An ultra-efficient hull configuration provides space for three secondary weapon systems, a first for Terran-Vasudan fighters. This versatility enables Myrmidon squadrons to fulfill a range of combat roles, from light assault to heavy reconnaissance. \n\n<b>Prerequisites:</b> Fighter Design, Myrmidon. \n\n<b>Armaments:</b> 4x GTW Subach HL-7, 2x GTW-5a Prometheus R, 2x GTM-MX64 Rockeye, 1x GTM-MX6 Tempest.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_ares",
		RequiredResearch = "Ares & FS2",
		RequiredShipSubSystems = "",
		DisplayPriority = 24,
		DisplayedName = "GTF Ares - Strategic Assault <c=12AB06>45s</c>",
		Description =
		"<b>Description:</b> The GTF Ares class of fighters is a radical upgrade of the Hercules II fighter. The power plant has been completely replaced with the newer, more powerful Nankam NA-27f model. Depleted uranium shielding has been added atop critical subsystems, making the Ares harder to incapacitate. Two primary weapon banks have been added, for greater firepower than the Herc II. This greater punch and protection come at a cost, however, as the Ares handles like a potato. \n\n<b>Prerequisites:</b> Fighter Design, Ares. \n\n<b>Armaments:</b> 2x GTW-66 Maxim, 4x Prometheus S, 2x GTM-55 Trebuchet, 2x GTM-4a Tornado.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_erinyes",
		RequiredResearch = "Erinyes & FS2",
		RequiredShipSubSystems = "",
		DisplayPriority = 25,
		DisplayedName = "GTF Erinyes - Heavy Assault <c=12AB06>45s</c>",
		Description =
		"<b>Description:</b> GTF Erinyes craft are fresh off the drawing boards of Triton Dynamics. Though fast and heavily armored, their main attraction is firepower. With eight primary banks and two secondary weapon bays, Erinyes are at the top of the combat craft food chain. Both sets of weapon banks have been designed to maximize compatibility with the greatest possible number of weapon system. Erinyes-class ships are being evenly distributed through the GTVA fleet, but only elite pilots are currently authorized to fly them. \n\n<b>Prerequisites:</b> Fighter Design, Erinyes. \n\n<b>Armaments:</b> 4x UD-8 Kayser, 4x GTW-19 Circe, 1x GTM-19 Harpoon, 1x GTM-4a Tornado.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_zeus",
		RequiredResearch = "Zeus",
		RequiredShipSubSystems = "",
		DisplayPriority = 31,
		DisplayedName = "GTB Zeus - Strike Bomber <c=12AB06>31s</c>",
		Description =
		"<b>Description:</b> The GTB Zeus is the fastest of all currently active GTVA bombers. It replaced the fleet's old Athena bombers as they were mothballed during the years following the Great War. Though slightly slower than the Athena, the Zeus's heavier armor and armament give it a much better battlezone survivability rate. Many of the Zeus wings in the GTVA fleet defected to the NTF during the initial stages of the rebellion. \n\n<b>Prerequisites:</b> Bomber Design, Anti-Cruiser Bombs. \n\n<b>Armaments:</b> 2x Subach HL-7, 2x GTW Akheton SDG, 1x GTM 43a Stiletto II (Upgrade), 1x GTM-12 Cyclops.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_artemis",
		RequiredResearch = "Artemis & FS2",
		RequiredShipSubSystems = "",
		DisplayPriority = 40,
		DisplayedName = "GTB Artemis - Medium Bomber <c=12AB06>37s</c>",
		Description =
		"<b>Description:</b> The GTB Artemis is the most agile bomber in the GTVA fleet, which makes it ideal for quick-hitting missions against warships and other slow targets. Of the same technological generation as the Boanerges class, the Artemis is less heavily armed and carries a lighter weapon payload, but it is significantly more maneuverable. While the Boanerges can inflict more damage, the Artemis can undertake (and return from) missions the slower Boanerges would have no hope of surviving. \n\n<b>Prerequisites:</b> Bomber Design, Anti-Cruiser Bombs. \n\n<b>Armaments:</b> 4x Subach HL-7 (Rapid Fire), 1x GTM-10 Pihrana (Upgrade), 1x GTM-12 Cyclops.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_artemisdh",
		RequiredResearch = "ArtemisDH & FS2",
		RequiredShipSubSystems = "",
		DisplayPriority = 41,
		DisplayedName = "GTB Artemis D.H. - Adv. Bomber <c=12AB06>42s</c>",
		Description =
		"<b>Description:</b> The Artemis D.H. is an experimental variant of the standard Artemis. The most notable change is the Artemis's factory-issued Han-Ronald engines have been replaced by the Nankam NA-27f powerplant found in GTF Ares fightercraft. The D.H. is faster and more maneuverable than the standard Artemis bomber, at no cost to armor or armament. During the OpEval period, Artemis D.H. bombers are being deployed in only select squadrons in different theatres of the war. \n\n<b>Prerequisites:</b> Bomber Design, Artemis D.H. Upgrade. \n\n<b>Armaments:</b> 4x UD-8 Kayser (Rapid Fire), 1x GTM-10 Pihrana, 1x GTM-12 Cyclops.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_medusa",
		RequiredResearch = "Medusa & FS2",
		RequiredShipSubSystems = "",
		DisplayPriority = 32,
		DisplayedName = "GTB Medusa - Medium Bomber <c=12AB06>35s</c>",
		Description =
		"<b>Description:</b> The GTB Medusa is the workhorse of the GTVA's bomber fleet. Its large bomb capacity enables it to take out cruiser-class warships, while its strong shielding ensures it can get close enough to deliver the punch. The first bomber to carry the potent Cyclops bomb, the Medusa is sure to be one of the highlights of a bomber pilot's career. \n\n<b>Prerequisites:</b> Bomber Design, Medusa. \n\n<b>Armaments:</b> 2x Prometheus R, 1x Prometheus R turret, 2x GTM-12 Cyclops.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_medusa_fs1",
		RequiredResearch = "Medusa & FS1",
		RequiredShipSubSystems = "",
		DisplayPriority = 32,
		DisplayedName = "GTB Medusa (FS1) - Medium Bomber <c=12AB06>35s</c>",
		Description =
		"<b>Description:</b> The GTB Medusa is the workhorse of the GTVA's bomber fleet. Its large bomb capacity enables it to take out cruiser-class warships, while its strong shielding ensures it can get close enough to deliver the punch. The first bomber to carry the potent Cyclops bomb, the Medusa is sure to be one of the highlights of a bomber pilot's career. \n\n<b>Prerequisites:</b> Bomber Design, Medusa. \n\n<b>Armaments:</b> 2x Prometheus R, 1x Prometheus R turret, 2x GTM-MX Tsunami.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_ursa",
		RequiredResearch = "Ursa & FS2",
		RequiredShipSubSystems = "",
		DisplayPriority = 33,
		DisplayedName = "GTB Ursa - Heavy Bomber <c=12AB06>45s</c>",
		Description =
		"<b>Description:</b> The GTB Ursa is the slowest bomber in the GTVA fleet. What it lacks in speed, however, it more than makes up with its massive payload. The Ursa was the first GTVA bomber designed specifically to destroy capital ships. With a rack of Helios bombs, in addition to a standard complement of Hornet missiles and Prometheus cannon, a squadron of Ursas can take out a destroyer. Ursas have the highest shielding of any bomber, along with a GTVI-designed hyper-dense hull. These help ensure that the Ursa gets close enough to deliver its payload and possibly even survive the escape. \n\n<b>Prerequisites:</b> Bomber Design, Ursa. \n\n<b>Armaments:</b> 5x Prometheus S, 1x Kayser turret, 1x GTM-13 Helios.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_ursa_fs1",
		RequiredResearch = "Ursa & FS1",
		RequiredShipSubSystems = "",
		DisplayPriority = 33,
		DisplayedName = "GTB Ursa (FS1) - Heavy Bomber <c=12AB06>45s</c>",
		Description =
		"<b>Description:</b> The GTB Ursa is the slowest bomber in the GTVA fleet. What it lacks in speed, however, it more than makes up with its massive payload. The Ursa was the first GTVA bomber designed specifically to destroy capital ships. With a rack of Helios bombs, in addition to a standard complement of Hornet missiles and Prometheus cannon, a squadron of Ursas can take out a destroyer. Ursas have the highest shielding of any bomber, along with a GTVI-designed hyper-dense hull. These help ensure that the Ursa gets close enough to deliver its payload and possibly even survive the escape. \n\n<b>Prerequisites:</b> Bomber Design, Ursa. \n\n<b>Armaments:</b> 5x Prometheus S, 1x Prometheus turret, 2x GTM-MX Tsunami.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_boanerges",
		RequiredResearch = "Boanerges & FS2",
		RequiredShipSubSystems = "",
		DisplayPriority = 42,
		DisplayedName = "GTB Boanerges - Heavy Bomber <c=12AB06>44s</c>",
		Description =
		"<b>Description:</b> The new GTB Boanerges has been assigned to elite bomber squadrons in the 3rd, 4th, and 5th Terran battle groups. The challenge of maintaining an aging fleet has motivated the GTVA to develop a new generation of ships able to withstand long-term abuse in the field. By maximizing shielding and payload (while offering enough maneuverability to make it a viable tactical unit), the Boanerges promises to remain in service for decades to come. One test pilot observed that the Boanerges handles better than any other bomber and has enough firepower to make it a formidable anti-capship weapon. \n\n<b>Prerequisites:</b> Bomber Design, Boanerges. \n\n<b>Armaments:</b> 2x GTW-66 Maxim, 1x GTM-13 Helios, 1x GTM-11 Infyrno (Upgrade).",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_fenris",
		RequiredResearch = "CruiserDesign & FS2",
		RequiredShipSubSystems = "",
		DisplayPriority = 50,
		DisplayedName = "GTC Fenris - Light Cruiser <c=12AB06>30s</c>",
		Description =
		"<b>Description:</b> The Fenris class is the aging stalwart among the Alliance's warships. Before the Great War, the Fenris was the GTA's only class of cruisers. During the war, Terran Command decided to build a second line of cruisers, the Leviathans, to free the Fenris from escort and guard duties. Fenris cruisers have fought in virtually every theatre of operation. These fast, versatile cruisers pack enough punch in their 260-meter-long hulls to go toe-to-toe with any enemy cruiser, and it's speed and maneuverability make it a good choice for strike missions. \n\n<b>Prerequisites:</b> Cruiser Design, Light Photon Beams. \n\n<b>Armaments:</b> 1x Slashing Beam, 1x Fusion Mortar, 2x Anti-Fighter Beam, 5x Turret.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_fenris_fs1",
		RequiredResearch = "CruiserDesign & FS1",
		RequiredShipSubSystems = "",
		DisplayPriority = 50,
		DisplayedName = "GTC Fenris (FS1) - Light Cruiser <c=12AB06>30s</c>",
		Description =
		"<b>Description:</b> The Fenris class is the aging stalwart among the Alliance's warships. Before the Great War, the Fenris was the GTA's only class of cruisers. During the war, Terran Command decided to build a second line of cruisers, the Leviathans, to free the Fenris from escort and guard duties. Fenris cruisers have fought in virtually every theatre of operation. These fast, versatile cruisers pack enough punch in their 260-meter-long hulls to go toe-to-toe with any enemy cruiser, and it's speed and maneuverability make it a good choice for strike missions. \n\n<b>Prerequisites:</b> Cruiser Design. \n\n<b>Armaments:</b> 1x Fusion Mortar, 7x Turret.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_leviathan",
		RequiredResearch = "HeavyCruiser & FS2",
		RequiredShipSubSystems = "",
		DisplayPriority = 51,
		DisplayedName = "GTC Leviathan - Heavy Cruiser <c=12AB06>43s</c>",
		Description =
		"<b>Description:</b> The Leviathan is much heavier armed and armored than the Fenris, but also much slower and less maneuverable. Leviathan cruisers are used to guard critical installations, such as permanent jump nodes, deep-space factories, and gas-mining operations, where firepower is king and speed is of little importance. They're also well-suited to escorting slow-moving freighters or transports. The Fenris is good for fast-moving operations, but when you need some muscle, call in a Leviathan. \n\n<b>Prerequisites:</b> Cruiser Design, GTC Leviathan. \n\n<b>Armaments:</b> 1x Light Beam, 1x Pihrana Turret, 4x Anti-Fighter Beam, 3x Turret.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_leviathan_fs1",
		RequiredResearch = "HeavyCruiser & FS1",
		RequiredShipSubSystems = "",
		DisplayPriority = 51,
		DisplayedName = "GTC Leviathan (FS1) - Heavy Cruiser <c=12AB06>43s</c>",
		Description =
		"<b>Description:</b> The Leviathan is much heavier armed and armored than the Fenris, but also much slower and less maneuverable. Leviathan cruisers are used to guard critical installations, such as permanent jump nodes, deep-space factories, and gas-mining operations, where firepower is king and speed is of little importance. They're also well-suited to escorting slow-moving freighters or transports. The Fenris is good for fast-moving operations, but when you need some muscle, call in a Leviathan. \n\n<b>Prerequisites:</b> Cruiser Design, GTC Leviathan. \n\n<b>Armaments:</b> 1x Huge Turret, 1x Pihrana Turret, 7x Turret.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_aeolus",
		RequiredResearch = "AdvancedCruiser & FS2",
		RequiredShipSubSystems = "",
		DisplayPriority = 52,
		DisplayedName = "GTC Aeolus - Adv. Cruiser <c=12AB06>47s</c>",
		Description =
		"<b>Description:</b> The GTC Aeolus is the first cruiser class ever produced by the RNI shipyards orbiting Laramis II. Only two dozen of these cruisers were put into service in GTVA fleets, with production ending in 2365. Allied Command assigns Aeolus-class ships primarily to guard slow-moving convoys against fighter and bomber wings, as these cruisers are severely out-gunned by most capital ships in service today. Their flak and AAA turrets serve as marvelous deterrents to smaller craft, however. \n\n<b>Prerequisites:</b> Cruiser Design, GTC Aeolus. \n\n<b>Armaments:</b> 2x Light Beam, 2x Anti-Fighter Beam, 6x Flak Turret, 2x Huge Turret.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_deimos",
		RequiredResearch = "Corvette & FS2",
		RequiredShipSubSystems = "",
		DisplayPriority = 70,
		DisplayedName = "GTCv Deimos - Corvette <c=12AB06>110s</c>",
		Description =
		"<b>Description:</b> Deimos-class corvettes, such as the GTCv Actium and the GTCv Lysander, are the newest addition to the Terran fleet. These sleek, ultra-modern warships are the products of a new era of ship design, maximizing maneuverability and firepower. Their hulls are strengthened with collapsed-core molybdenum sheathing for better protection against beam fire, and their Vasudan-designed reactor core provides more energy per ton than any other allied ship class. \n\n<b>Prerequisites:</b> Capital Ship Design, Corvette. \n\n<b>Armaments:</b> 4x Slashing Beam, 4x Anti-Fighter Beam, 6x Flak Turret, 2x Piranha Missile Launcher, 4x Huge Turret, 6x Turret.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_orion",
		RequiredResearch = "CapitalShipDesign & FS2",
		RequiredShipSubSystems = "",
		DisplayPriority = 80,
		DisplayedName = "GTD Orion - Destroyer <c=12AB06>215s</c>",
		Description =
		"<b>Description:</b> For over 30 years, the GTD Orion class was the largest ship in the Terran-Vasudan armada. Over two kilometers in length, bristling with dozens of death-dealing turrets, the Orion is as awesome in repose as it is in battle. All GTVA Orions have been retrofitted with the latest anti-warship beam weapons, as well as flak and AAA turrets for dealing with fighters and bombers. The Orion's cavernous hangar bays easily accommodate more than two dozen fighter or bomber wings. \n\n<b>Prerequisites:</b> Capital Ship Design, Heavy Photon Beams. \n\n<b>Armaments:</b> 3x Heavy Beam, 3x Slashing Beam, 3x Anti-Fighter Beam, 4x Huge Turret, 3x Turret.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_orion_fs1",
		RequiredResearch = "CapitalShipDesign & FS1",
		RequiredShipSubSystems = "",
		DisplayPriority = 80,
		DisplayedName = "GTD Orion (FS1) - Destroyer <c=12AB06>215s</c>",
		Description =
		"<b>Description:</b> For over 30 years, the GTD Orion class was the largest ship in the Terran-Vasudan armada. Over two kilometers in length, bristling with dozens of death-dealing turrets, the Orion is as awesome in repose as it is in battle. All GTVA Orions have been retrofitted with the latest anti-warship beam weapons, as well as flak and AAA turrets for dealing with fighters and bombers. The Orion's cavernous hangar bays easily accommodate more than two dozen fighter or bomber wings. \n\n<b>Prerequisites:</b> Capital Ship Design. \n\n<b>Armaments:</b> 4x Huge Turret, 20x Turret.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_hecate",
		RequiredResearch = "CapitalShipDesign & FS2",
		RequiredShipSubSystems = "",
		DisplayPriority = 81,
		DisplayedName = "GTD Hecate - Destroyer <c=12AB06>200s</c>",
		Description =
		"<b>Description:</b> The new GTD Hecate class of destroyers is replacing the Orion class as the flagship of Terran battle groups. More heavily armed than the Orion, the Hecate also carries over 150 combat spacecraft and a crew of 10,000. The GTD Aquitaine is a superb example of this new ship class, serving as the flagship of the Capella-based 3rd Fleet. \n\n<b>Prerequisites:</b> Capital Ship Design, Heavy Photon Beams. \n\n<b>Armaments:</b> 1x Heavy Beam, 4x Slashing Beam, 6x Anti-Fighter Beam, 4x Flak Turret, 6x Long Range Flak Turret, 6x Turret.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_hades",
		RequiredResearch = "SuperDestroyer",
		RequiredShipSubSystems = "",
		DisplayPriority = 82,
		DisplayedName = "GTD Hades - Super Destroyer <c=12AB06>280s</c>",
		Description =
		"<b>Description:</b> The GTD Hades was a fusion of Terran and Shivan military technologies. It was constructed by Galactic Terran Intelligence (GTI), a rogue branch of the GTA. After the defeat of the GTI and the destruction of the Hades, the GTA classified the details of this research at level Omega. There are rumors that the Alliance has attempted to reconstruct the Hades to learn more about the GTI's activities. These reports have yet to be confirmed by government sources. \n\n<b>Prerequisites:</b> Capital Ship Design, Super Destroyer. \n\n<b>Armaments:</b> 2x Super Heavy Beam, 2x Heavy Beam, 4x Piranha Missile Launcher, 5x Huge Turret, 7x Turret.",
	},

	{
		Type = Ship,
		ThingToBuild = "ter_colossus",
		RequiredResearch = "Juggernaut & FS2",
		RequiredShipSubSystems = "",
		DisplayPriority = 84,
		DisplayedName = "GTVA Colossus <c=12AB06>500s</c>",
		Description =
		"<b>Description:</b> The GTVA Colossus resulted from an endeavor unprecedented in Terran or Vasudan history. This 6-kilometer-long behemoth is the result of 20 years of joint effort from dozens of contractors of both races. The Colossus is the most powerful space-faring warship ever made, bristling with over 60 weapon turrets. It also houses 60 fighter and bomber wings and requires a crew of over 30,000. The firepower of the Colossus is greater than that of most GTVA battle groups. \n\n<b>Prerequisites:</b> Super Capital Ship Design, Juggernaut. \n\n<b>Armaments:</b> 6x Heavy Beams, 7x Slashing Beams, 10x Anti-Fighter Beams, 12x Flak Turret, 2x Piranha, 8x FighterKiller, 10x Huge Turret, 8x Turret.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_elysium",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 100,
		DisplayedName = "GTT Elysium - Collector <c=12AB06>25s</c>",
		Description =
		"<b>Description:</b> The GTT Elysium class of transports has been in service for over 40 years. Its mission hasn't changed from the time of the Great War - to transport civilian and military personnel from one star system to another. The Elysium is very poorly armed, with a single Subach HL-7 cannon, and also suffers from thin armor plating. Only desperate circumstances find Elysiums anywhere near the front lines. Assaults and dangerous transport missions handled almost exclusively by the much tougher GTT Argo class. \n\n<b>Prerequisites:</b> None. \n\n<b>Armaments:</b> None.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_zephyrus",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 103,
		DisplayedName = "GTG Zephyrus - Drop-off <c=12AB06>30s</c>",
		Description =
		"<b>Description:</b> When a fighter pilot sees a ship of the GTG Zephyrus class, one thought flashes through his or her mind: Thank God I don't have to fly that tub! The Zephyrus is a gas miner designed to harvest the gases of interstellar nebulae. It's the largest non-combatant ship in the GTVA fleet. The Zephyrus's thin armor, weak weaponry, and poor speed give it a very low survival rate in combat, so these ships stay well back from the front lines. Despite these weaknesses, the Zephyrus plays a critical role in the operation of the GTVA fleet. The deuterium gathered by Zephyrus ships powers the fleet's fusion drives. \n\n<b>Prerequisites:</b> None. \n\n<b>Armaments:</b> 2x Turret, 2x Subach HL-7, 1x Flak.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_argo",
		RequiredResearch = "RepairArgo",
		RequiredShipSubSystems = "",
		DisplayPriority = 101,
		DisplayedName = "GTT Argo - Repair <c=12AB06>37s</c>",
		Description =
		"<b>Description:</b> The GTT Argo has become the standard military transport vehicle for the Terran fleet. Argos sometimes carry new weapon and combat craft prototypes to and from testing grounds or to front-line deployment positions. Military VIPs occasionally commandeer Argos to travel from star system to star system in some semblance of comfort. Argos are most often used as assault transports, carrying squads of Marines through heavy flak to board enemy vessels that Command has decided to capture rather than destroy. \n\n<b>Prerequisites:</b> Repair Frigate. \n\n<b>Armaments:</b> 2x Flak, Capture ability (Upgrade)",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_poseidon",
		RequiredResearch = "SentryAndMineDeployer",
		RequiredShipSubSystems = "",
		DisplayPriority = 102,
		DisplayedName = "GTFr Poseidon - Sentry Builder <c=12AB06>25s</c>",
		Description =
		"<b>Description:</b> The GTFr Poseidon is the smaller of the two standard Terran military freighters. Though it carries only half as much cargo as the Triton, the Poseidon is more often chosen for dangerous missions. Its greater speed gives it better survivability on the front lines, as does the fact that it has four weapon turrets, compared to the Triton's two. When Allied Command sends supplies and munitions that have to get through, a Poseidon is usually chosen to transport them. \n\n<b>Prerequisites:</b> Sentry & Mine Deployer. \n\n<b>Armaments:</b> 4x Turret.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_alastor",
		RequiredResearch = "SentryGun",
		RequiredShipSubSystems = "",
		DisplayPriority = 120,
		DisplayedName = "GTSG Alastor - Sentry Gun <c=12AB06>7s</c>",
		Description =
		"<b>Description:</b> GTSG Alastor sentry gun platforms can be dropped by warships to cover a retreat, or they can be used to strengthen firepower around strategic locations. While Alastors alone cannot hold a position against more than a few fighters, complementing them with a warship and several wings of fighters presents an exemplary defense against all but the most determined foes. Two Bessmer-Kohn cannon turrets on opposing sides of the platform give the Alastor a full field of fire. The turrets are controlled by the latest neural-net cyber-AI to track multiple targets simultaneously. \n\n<b>Prerequisites:</b> Sentry Gun. \n\n<b>Armaments:</b> 2x Subach.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_mjolnir",
		RequiredResearch = "BeamSentry",
		RequiredShipSubSystems = "",
		DisplayPriority = 122,
		DisplayedName = "GTSG Mjolnir - Beam Sentry <c=12AB06>120s</c>",
		Description =
		"<b>Description:</b> The GTSG Mjolnir is the most advanced sentry gun device known. The Mjolnir mounts a single, powerful beam cannon and can do heavy damage to enemy warships before they come in range. Mjolnirs are also referred to as RBCs (remote beam cannons). They are used to help protect the most vital front-line Alliance installations. \n\n<b>Prerequisites:</b> Beam Sentry. \n\n<b>Armaments:</b> 1x Mjolnir Beam.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_pharos",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 109,
		DisplayedName = "GTNB Pharos - Sensor Bouy <c=12AB06>20s</c>",
		Description =
		"<b>Description:</b> Long range sensor device. Can be deployed to a specific location once after construction. \n\n<b>Prerequisites:</b> None. \n\n<b>Armaments:</b> None.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_charybdis",
		RequiredResearch = "AWACS & FS2",
		RequiredShipSubSystems = "",
		DisplayPriority = 108,
		DisplayedName = "GTA Charybdis - AWACS <c=12AB06>90s</c>",
		Description =
		"<b>Description:</b> Ships of the GTA Charybdis class have been packed with the latest tachyon-enabled AWACS equipment from GTVI labs. Each GTVA battle group has a squadron of Charybdis-class ships assigned to it. These ships double the range of the group's standard detection arrays. Charybdis ships' thin armor and weak defenses make them easy victims for enemy bombers. They have proven indispensable, however, in forays into the nebula beyond the Knossos portal. Charybdis-class ships are very vulnerable in this environment, as witnessed by the recent loss of the GTA Panopticon from the 3rd Battle Group. \n\n<b>Prerequisites:</b> AWACS. \n\n<b>Armaments:</b> 6x Turret.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_hygeia",
		RequiredResearch = "FighterDesign",
		RequiredShipSubSystems = "",
		DisplayPriority = 104,
		DisplayedName = "GTS Hygeia - Support Ship <c=12AB06>9s</c>",
		Description =
		"<b>Description:</b> The GTS Hygeia is the fleet's newest Terran support ship. It is fast and maneuverable, a necessity when trying to dock with fighters in the heat of battle. Triton Dynamics designed the Hygeia class with huge cargo bays for munitions storage, plus the latest magnetic-stasis delivery system for quickly re-supplying combat craft with missiles and bombs. The Hygeia's repair facilities are driven by neural-net AI, for ultra-fast system diagnostics and repair. The high number of warheads carried by the Hygeia makes it a dangerous ship to be near when it blows up. \n\n<b>Prerequisites:</b> Fighter Design. \n\n<b>Armaments:</b> None.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_apollo",
		RequiredResearch = "Apollo & FS1",
		RequiredShipSubSystems = "",
		DisplayPriority = 10,
		DisplayedName = "GTF Apollo - Space Superiority <c=12AB06>30s</c>",
		Description =
		"<b>Description:</b> The Apollo is the most common GTA fighter.  It is highly versatile and can perform multiple roles, including space superiority, interception and assault. \n\n<b>Prerequisites:</b> Fighter Design, Apollo. \n\n<b>Armaments:</b> 4x ML-16 Laser, 4x GTW-15 Avenger (Upgrade), 1x GTM-MX50, 1x GTM-2 Fury.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_valkyrie",
		RequiredResearch = "Valkyrie & FS1",
		RequiredShipSubSystems = "",
		DisplayPriority = 11,
		DisplayedName = "GTF Valkyrie - Interceptor <c=12AB06>30s</c>",
		Description =
		"<b>Description:</b> Using the old GTF Angel scout fighter as a template, the GTA created the Valkyrie interceptor fighter.  It has two additional engines, as well as an additional set of primary hardpoints.  This makes the Valkyrie the best bomber interceptor in the fleet.  Its speed is unmatched in the GTA, and its maneuverability is above average.  Its only drawbacks are a small secondary payload and a weak hull. \n\n<b>Prerequisites:</b> Fighter Design, Valkyrie. \n\n<b>Armaments:</b> 4x GTW-7 Banshee, 2x GTW-65 Railgun (Silent Threat Upgrade), 2x GTM Phoenix-V.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_athena",
		RequiredResearch = "BomberDesign",
		RequiredShipSubSystems = "",
		DisplayPriority = 30,
		DisplayedName = "GTB Athena - Light Bomber <c=12AB06>31s</c>",
		Description =
		"<b>Description:</b> The smallest bomber in the fleet, the Athena has oftentimes been mistaken for a fighter.  However, one should not be fooled by its small size.  The Athena can carry light bombs and most missiles.  It also has the ability to dogfight well.  Its strong shielding and hull make it the favored ''Lightning Bomber'' of the GTA. \n\n<b>Prerequisites:</b> Bomber Design \n\n<b>Armaments:</b> 2x GTW-15 Avenger, 2x GTW-41 Disruptor, 2x GTW-32 Flail (Upgrade), 2x GTM-9 Interceptor, 2x GTM-11 EM Pulse.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_chronos",
		RequiredResearch = "RepairChronos",
		RequiredShipSubSystems = "",
		DisplayPriority = 106,
		DisplayedName = "GTFr Chronos - Repair Ship <c=12AB06>37s</c>",
		Description =
		"<b>Description:</b> The Chronos is a freighter of civilian design. As the Terran Vasudan war dragged on, more and more of these vessels were commissioned by the GTA for use in military operations. These vessels are slow but strong. \n\n<b>Prerequisites:</b> Repair Frigate. \n\n<b>Armaments:</b> 1x Avenger Turret, Capture ability (Upgrade)",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_cerberus",
		RequiredResearch = "SentryGun",
		RequiredShipSubSystems = "",
		DisplayPriority = 121,
		DisplayedName = "GTSG Cerberus - Sentry Gun <c=12AB06>5s</c>",
		Description =
		"<b>Description:</b> The Cerberus is an advanced version of the Watchdog, with stronger weaponry and the ability to withstand more damage. \n\n<b>Prerequisites:</b> Sentry Gun. \n\n<b>Armaments:</b> 2x GTW-15 Avenger.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_centaur",
		RequiredResearch = "FighterDesign",
		RequiredShipSubSystems = "",
		DisplayPriority = 105,
		DisplayedName = "GTS Centuar - Support Ship <c=12AB06>9s</c>",
		Description =
		"<b>Description:</b> The Centaur support ship is designed to get in and out of battle as quick as possible. It is fast, and quite maneuverable, allowing it to dock with fighters in a minimum amount of time. Most notable about the Centaur, however, is its extremely large explosion radius. The amount of warheads carried on a support ship makes it very dangerous to be close to an exploding Centaur. \n\n<b>Prerequisites:</b> Fighter Design. \n\n<b>Armaments:</b> None.",
	},

	{
		Type = Ship,
		ThingToBuild = "ter_faustus",
		RequiredResearch = "ScienceVessel",
		RequiredShipSubSystems = "",
		DisplayPriority = 107,
		DisplayedName = "GTSC Faustus - Science Vessel <c=12AB06>35s</c>",
		Description =
		"<b>Description:</b> The Faustus Science vessel was, and still is, a civilian craft. However, in the 14 years since the Terran-Vasudan war began, more and more of these were commissioned by the GTA in order to pursue military research. However, its obvious value, poor fighting capabilities, and lack of speed make it a prime target for enemy ships; hence, you will rarely find many of these anywhere near the front lines of battle. \n\n<b>Prerequisites:</b> Science Vessel. \n\n<b>Armaments:</b> 6x Turret.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_arcadia",
		RequiredResearch = "Installation",
		RequiredShipSubSystems = "",
		DisplayPriority = 83,
		DisplayedName = "GTI Arcadia - Installation <c=12AB06>100s</c>",
		Description =
		"<b>Description:</b> The GTI Arcadia is a multi-purpose installation that has served the Terran fleet since the days of the Great War. Almost every major star system is host to at least one Arcadia, which is often used as a center for trade and communications. Home to scores of small ships, including repair vessels, fighters, and transports, an Arcadia installation is always a hub of intrasystem and interstellar traffic. An Arcadia is not an easy target for hostile forces, as it combines the firepower of over 20 weapon turrets with the ability to launch up to ten wings of fighters from its fighterbay. \n\n<b>Prerequisites:</b> Installation. \n\n<b>Armaments:</b> 19x Turret, 5x FighterKiller.",
	},
	{
		Type = Ship,
		ThingToBuild = "ter_pegasus",
		RequiredResearch = "Pegasus & FS2",
		RequiredShipSubSystems = "",
		DisplayPriority = 26,
		DisplayedName = "GTF Pegasus - Stealth Recon <c=12AB06>65s</c>",
		Description =
		"<b>Description:</b> The Pegasus is used almost exclusively for reconnaissance missions. It's the fastest, most maneuverable ship in the Terran arsenal. The craft's contours and hull materials were carefully designed to minimize its profile to detection sensors. It is woefully armored and packs only minimal weaponry, making it a death box in a firefight. Pegasus pilots are a special breed of daredevils who pride themselves on getting into and out of situations that would be the death of other pilots, all without firing a shot. \n\n<b>Prerequisites:</b> Fighter Design, Pegasus. \n\n<b>Armaments:</b> 2x Subach HL-7 (Rapid Fire), GTM-19 Harpoon, 1x GTM 43a Stiletto II (Upgrade).",
	},
}
