Icon_Speed = "data:ui/newui/research/icons/speed.mres"
Icon_Health = "data:ui/newui/research/icons/health.mres"
Icon_Tech = "data:ui/newui/research/icons/tech.mres"
Icon_Ability = "data:ui/newui/research/icons/ability.mres"
Icon_Build = "data:ui/newui/research/icons/build.mres"
Modifier = 0
Ability = 1
AllShips = 0
Family = 1
Ship = 2

research = {
	{
		Name = "FS1",
		RequiredResearch = "",
		RequiredSubSystems = "",
		--DoNotGrant = 1,
		Cost = 10,
		Time = 1,
		DisplayedName = "FreeSpace 1 Era",
		DisplayPriority = 0,
		Description = "Activates FreeSpace 1 ships and technology.",
		Icon = Icon_Tech,
		ShortDisplayedName = "FS1 Era",
	},
	{
		Name = "FS2",
		RequiredResearch = "",
		RequiredSubSystems = "",
		--DoNotGrant = 1,
		Cost = 10,
		Time = 1,
		DisplayedName = "FreeSpace 2 Era",
		DisplayPriority = 0,
		Description = "Activates FreeSpace 2 ships and technology.",
		Icon = Icon_Tech,
		ShortDisplayedName = "FS2 Era",
	},
	-- Era Switches (Hidden) ---



	-- Fighters --------------
	{
		Name = "FighterDesign",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1200,
		Time = 40,
		DisplayedName = "Fighter Design <c=0e0160>(40s)</c>",
		DisplayPriority = 1,
		Description = "Fighter chassis and drives. Required for all Fighter class research.",
		TargetType = Ship,
		TargetName = "ter_apollo",
		Icon = Icon_Build,
		ShortDisplayedName = "Fighter Design",
	},
	{
		Name = "Apollo",
		RequiredResearch = "FighterDesign & FS1",
		RequiredSubSystems = "",
		Cost = 850,
		Time = 40,
		DisplayedName = "GTF Apollo <c=0e0160>(40s)</c>",
		DisplayPriority = 19,
		Description = "Unlocks the GTF Apollo Interceptor.",
		TargetType = Ship,
		TargetName = "ter_apollo",
		Icon = Icon_Build,
		ShortDisplayedName = "Apollo",
	},
	{
		Name = "Valkyrie",
		RequiredResearch = "FighterDesign & FS1",
		RequiredSubSystems = "",
		Cost = 850,
		Time = 40,
		DisplayedName = "GTF Valkyrie <c=0e0160>(40s)</c>",
		DisplayPriority = 19,
		Description = "Unlocks the GTF Valkyrie Interceptor.",
		TargetType = Ship,
		TargetName = "ter_valkyrie",
		Icon = Icon_Build,
		ShortDisplayedName = "Valkyrie",
	},
	{
		Name = "Hercules",
		RequiredResearch = "FighterDesign",
		RequiredSubSystems = "",
		Cost = 1000,
		Time = 45,
		DisplayedName = "GTF Hercules <c=0e0160>(45s)</c>",
		DisplayPriority = 11,
		Description = "Unlocks the GTF Hercules Assault Fighter.",
		TargetType = Ship,
		TargetName = "ter_hercules",
		Icon = Icon_Build,
		ShortDisplayedName = "Hercules",
	},
	{
		Name = "Ulysses",
		RequiredResearch = "FighterDesign",
		RequiredSubSystems = "",
		Cost = 1000,
		Time = 45,
		DisplayedName = "GTF Ulysses <c=0e0160>(45s)</c>",
		DisplayPriority = 22,
		Description = "Unlocks the GTF Ulysses Space Superiority Fighter.",
		TargetType = Ship,
		TargetName = "ter_ulysses",
		Icon = Icon_Build,
		ShortDisplayedName = "Ulysses",
	},
	{
		Name = "Myrmidon",
		RequiredResearch = "FighterDesign & FS2",
		RequiredSubSystems = "",
		Cost = 1200,
		Time = 50,
		DisplayedName = "GTF Myrmidon <c=0e0160>(50s)</c>",
		DisplayPriority = 22,
		Description = "Unlocks the GTF Myrmidon Space Superiority Fighter.",
		TargetType = Ship,
		TargetName = "ter_myrmidon",
		Icon = Icon_Build,
		ShortDisplayedName = "Myrmidon",
	},
	{
		Name = "Perseus",
		RequiredResearch = "FighterDesign & FS2",
		RequiredSubSystems = "",
		Cost = 1200,
		Time = 50,
		DisplayedName = "GTF Perseus <c=0e0160>(50s)</c>",
		DisplayPriority = 19,
		Description = "Unlocks the GTF Perseus Interceptor.",
		TargetType = Ship,
		TargetName = "ter_perseus",
		Icon = Icon_Build,
		ShortDisplayedName = "Perseus",
	},
	{
		Name = "Pegasus",
		RequiredResearch = "Perseus & FS2",
		RequiredSubSystems = "",
		Cost = 1000,
		Time = 30,
		DisplayedName = "GTF Pegasus <c=0e0160>(30s)</c>",
		DisplayPriority = 23,
		Description = "Unlocks the GTF Pegasus Stealth Recon Fighter.",
		TargetType = Ship,
		TargetName = "ter_pegasus",
		Icon = Icon_Build,
		ShortDisplayedName = "Pegasus",
	},
	{
		Name = "HerculesMk2",
		RequiredResearch = "FighterDesign & FS2",
		RequiredSubSystems = "",
		Cost = 1200,
		Time = 50,
		DisplayedName = "GTF Hercules Mk. II <c=0e0160>(50s)</c>",
		DisplayPriority = 11,
		Description = "Unlocks the GTF Hercules Mk. II Assault Fighter.",
		TargetType = Ship,
		TargetName = "ter_herculesmk2",
		Icon = Icon_Build,
		ShortDisplayedName = "Hercules Mk. II",
	},
	{
		Name = "Ares",
		RequiredResearch = "HerculesMk2 & FS2",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "GTF Ares <c=0e0160>(50s)</c>",
		DisplayPriority = 12,
		Description = "Unlocks the GTF Ares Heavy Assault Fighter.",
		TargetType = Ship,
		TargetName = "ter_ares",
		Icon = Icon_Build,
		ShortDisplayedName = "Ares",
	},
	{
		Name = "Erinyes",
		RequiredResearch = "HerculesMk2 & FS2",
		RequiredSubSystems = "",
		Cost = 1800,
		Time = 60,
		DisplayedName = "GTF Erinyes <c=0e0160>(60s)</c>",
		DisplayPriority = 12,
		Description = "Unlocks the GTF Erinyes Heavy Assault Fighter.",
		TargetType = Ship,
		TargetName = "ter_erinyes",
		Icon = Icon_Build,
		ShortDisplayedName = "Erinyes",
	},

	-- Bombers ---------------
	{
		Name = "BomberDesign",
		RequiredResearch = "FighterDesign",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Bomber Design <c=0e0160>(50s)</c>",
		DisplayPriority = 2,
		Description = "Bomber chassis and drives. Required for all Bomber class research.",
		TargetType = Ship,
		TargetName = "ter_athena",
		Icon = Icon_Build,
		ShortDisplayedName = "Bomber Design",
	},
	{
		Name = "Zeus",
		RequiredResearch = "BomberDesign & FS2",
		RequiredSubSystems = "",
		Cost = 1000,
		Time = 40,
		DisplayedName = "GTB Zeus <c=0e0160>(40s)</c>",
		DisplayPriority = 15,
		Description = "Unlocks the GTB Zeus Medium Bomber.",
		TargetType = Ship,
		TargetName = "ter_zeus",
		Icon = Icon_Build,
		ShortDisplayedName = "Zeus",
	},
	{
		Name = "Artemis",
		RequiredResearch = "BomberDesign & FS2",
		RequiredSubSystems = "",
		Cost = 1200,
		Time = 50,
		DisplayedName = "GTB Artemis <c=0e0160>(50s)</c>",
		DisplayPriority = 15,
		Description = "Unlocks the GTB Artemis Medium Bomber.",
		TargetType = Ship,
		TargetName = "ter_artemis",
		Icon = Icon_Build,
		ShortDisplayedName = "Artemis",
	},
	{
		Name = "ArtemisDH",
		RequiredResearch = "Artemis",
		RequiredSubSystems = "",
		Cost = 1400,
		Time = 50,
		DisplayedName = "GTB Artemis D.H. <c=0e0160>(50s)</c>",
		DisplayPriority = 15,
		Description = "Unlocks the GTB Artemis D.H. Advanced Bomber.",
		TargetType = Ship,
		TargetName = "ter_artemisdh",
		Icon = Icon_Build,
		ShortDisplayedName = "Artemis D.H.",
	},
	{
		Name = "Medusa",
		RequiredResearch = "BomberDesign",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "GTB Medusa <c=0e0160>(50s)</c>",
		DisplayPriority = 26,
		Description = "Unlocks the GTB Medusa Heavy Bomber.",
		TargetType = Ship,
		TargetName = "ter_medusa",
		Icon = Icon_Build,
		ShortDisplayedName = "Medusa",
	},
	{
		Name = "Boanerges",
		RequiredResearch = "BomberDesign & FS2",
		RequiredSubSystems = "",
		Cost = 1800,
		Time = 60,
		DisplayedName = "GTB Boanerges <c=0e0160>(60s)</c>",
		DisplayPriority = 26,
		Description = "Unlocks the GTB Boanerges Heavy Bomber.",
		TargetType = Ship,
		TargetName = "ter_boanerges",
		Icon = Icon_Build,
		ShortDisplayedName = "Boanerges",
	},
	{
		Name = "Ursa",
		RequiredResearch = "BomberDesign",
		RequiredSubSystems = "",
		Cost = 2000,
		Time = 50,
		DisplayedName = "GTB Ursa <c=0e0160>(50s)</c>",
		DisplayPriority = 12,
		Description = "Unlocks the GTB Ursa Assault Bomber.",
		TargetType = Ship,
		TargetName = "ter_ursa",
		Icon = Icon_Build,
		ShortDisplayedName = "Ursa",
	},

	-- Frigates --------------
	{
		Name = "CruiserDesign",
		RequiredResearch = "BomberDesign",
		RequiredSubSystems = "",
		Cost = 4000,
		Time = 120,
		DisplayedName = "Cruiser Design <c=0e0160>(120s)</c>",
		DisplayPriority = 3,
		Description = "Cruiser chassis and drives. Required for all Terran Cruiser class research.",
		TargetType = Ship,
		TargetName = "ter_fenris_fs1",
		Icon = Icon_Build,
		ShortDisplayedName = "Cruiser Design",
	},
	{
		Name = "RepairArgo",
		RequiredResearch = "CruiserDesign & FS2",
		RequiredSubSystems = "",
		Cost = 1000,
		Time = 50,
		DisplayedName = "Repair Frigate <c=0e0160>(50s)</c>",
		DisplayPriority = 18,
		Description = "Unlocks Repair Frigates",
		TargetType = Ship,
		TargetName = "ter_argo",
		Icon = Icon_Build,
		ShortDisplayedName = "Repair Frigate",
	},
	{
		Name = "RepairChronos",
		RequiredResearch = "CruiserDesign & FS1",
		RequiredSubSystems = "",
		Cost = 1000,
		Time = 50,
		DisplayedName = "Repair Frigate <c=0e0160>(50s)</c>",
		DisplayPriority = 18,
		Description = "Unlocks Repair Frigates",
		TargetType = Ship,
		TargetName = "ter_chronos",
		Icon = Icon_Build,
		ShortDisplayedName = "Repair Frigate",
	},
	{
		Name = "CruiserHealthUpgrade",
		RequiredResearch = "CruiserDesign",
		RequiredSubSystems = "",
		Cost = 1000,
		Time = 50,
		DisplayedName = "Fenris Armor <c=0e0160>(50s)</c>",
		DisplayPriority = 41,
		Description =
		"Reinforced Armor plating for older Terran cruisers. Moderately increases health GTC Fenris class. Allows Production of GTC Leviathan class.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "ter_fenris",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.25,
		Icon = Icon_Health,
		ShortDisplayedName = "Fenris Armor",
	},
	{
		Name = "HeavyCruiser",
		RequiredResearch = "CruiserHealthUpgrade",
		RequiredSubSystems = "",
		Cost = 1000,
		Time = 50,
		DisplayedName = "GTC Leviathan <c=0e0160>(50s)</c>",
		DisplayPriority = 33,
		Description = "Unlocks Heavy Cruisers: Leviathan.",
		TargetType = Ship,
		TargetName = "ter_leviathan",
		Icon = Icon_Build,
		ShortDisplayedName = "Heavy Cruiser",
	},
	{
		Name = "AdvancedCruiser",
		RequiredResearch = "CruiserDesign & FS2",
		RequiredSubSystems = "",
		Cost = 2000,
		Time = 50,
		DisplayedName = "GTC Aeolus <c=0e0160>(50s)</c>",
		DisplayPriority = 21,
		Description = "Unlocks Advanced Cruisers: Aeolus.",
		TargetType = Ship,
		TargetName = "ter_aeolus",
		Icon = Icon_Build,
		ShortDisplayedName = "Advanced Cruiser",
	},

	-- Capital Ships ---------
	{
		Name = "CapitalShipDesign",
		RequiredResearch = "CruiserDesign",
		RequiredSubSystems = "",
		Cost = 8000,
		Time = 150,
		DisplayedName = "Capital Ship Design <c=0e0160>(150s)</c>",
		DisplayPriority = 4,
		Description = "Capital ship chassis and drives. Required for all Capital class research.",
		TargetType = Ship,
		TargetName = "ter_orion_fs1",
		Icon = Icon_Build,
		ShortDisplayedName = "Capital Ship Design",
	},
	{
		Name = "Deimos",
		RequiredResearch = "CapitalShipDesign & FS2",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Corvette <c=0e0160>(50s)</c>",
		DisplayPriority = 13,
		Description = "Unlocks Corvettes: Deimos.",
		TargetType = Ship,
		TargetName = "ter_deimos",
		Icon = Icon_Build,
		ShortDisplayedName = "Corvette",
	},
	{
		Name = "DeimosArmor",
		RequiredResearch = "Deimos",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Deimos Armor <c=0e0160>(50s)</c>",
		DisplayPriority = 16,
		Description = "Increases health of GTCv Deimos by 12.5%.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "ter_deimos",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.125,
		Icon = Icon_Health,
		ShortDisplayedName = "Deimos Armor Upgrade",
	},
	{
		Name = "DeimosSprint",
		RequiredResearch = "Deimos",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Deimos Sprint Drive <c=0e0160>(50s)</c>",
		DisplayPriority = 17,
		Description = "Improves the top speed of GTCv Deimos by 25%.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "ter_deimos",
		UpgradeName = "MaxSpeed",
		UpgradeValue = 1.25,
		Icon = Icon_Speed,
		ShortDisplayedName = "Deimos Sprint Drive",
	},
	{
		Name = "CommandCorvette",
		RequiredResearch = "Deimos & CapitalShipDesign",
		RequiredSubSystems = "",
		Cost = 2000,
		Time = 50,
		DisplayedName = "Command Corvette <c=0e0160>(50s)</c>",
		DisplayPriority = 16,
		Description = "Unlocks Command Corvettes: Iceni.",
		TargetType = Ship,
		TargetName = "ter_iceni",
		Icon = Icon_Build,
		ShortDisplayedName = "Command Corvette",
	},
	{
		Name = "Hecate",
		RequiredResearch = "CapitalShipDesign & FS2",
		RequiredSubSystems = "",
		Cost = 4500,
		Time = 90,
		DisplayedName = "GTD Hecate <c=0e0160>(90s)</c>",
		DisplayPriority = 31,
		Description = "Unlocks the GTD Hecate Destroyer.",
		TargetType = Ship,
		TargetName = "ter_hecate",
		Icon = Icon_Build,
		ShortDisplayedName = "Hecate",
	},
	{
		Name = "SuperDestroyer",
		RequiredResearch = "CapitalShipDesign",
		RequiredSubSystems = "",
		Cost = 8000,
		Time = 180,
		DisplayedName = "Super Destroyer <c=0e0160>(180s)</c>",
		DisplayPriority = 35,
		Description = "Unlocks Super Destroyers: Hades.",
		TargetType = Ship,
		TargetName = "ter_hades",
		Icon = Icon_Build,
		ShortDisplayedName = "Super Destroyer",
	},
	{
		Name = "Installation",
		RequiredResearch = "CapitalShipDesign",
		RequiredSubSystems = "",
		Cost = 2500,
		Time = 75,
		DisplayedName = "Installation <c=0e0160>(75s)</c>",
		DisplayPriority = 13,
		Description = "Unlocks Installations: Arcadia.",
		TargetType = Ship,
		TargetName = "ter_arcadia",
		Icon = Icon_Build,
		ShortDisplayedName = "Installation",
	},
	{
		Name = "Juggernaut",
		RequiredResearch = "SuperDestroyer & Installation & FS2",
		RequiredSubSystems = "",
		Cost = 12000,
		Time = 240,
		DisplayedName = "Juggernaut <c=0e0160>(240s)</c>",
		DisplayPriority = 31,
		Description = "Unlocks Juggernauts: Colossus.",
		TargetType = Ship,
		TargetName = "ter_colossus",
		Icon = Icon_Build,
		ShortDisplayedName = "Juggernaut",
	},

	-- Platforms -------------
	{
		Name = "SentryGun",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Sentry Gun <c=0e0160>(50s)</c>",
		DisplayPriority = 17,
		Description = "Unlocks Sentry Guns: Alastor, Cerberus.",
		TargetType = Ship,
		TargetName = "ter_alastor",
		Icon = Icon_Build,
		ShortDisplayedName = "Sentry Gun",
	},
	{
		Name = "SentryAndMineDeployer",
		RequiredResearch = "SentryGun",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Sentry And Mine Deployer <c=0e0160>(50s)</c>",
		DisplayPriority = 29,
		Description = "Unlocks Sentry and Mine Deployers: Poseidon.",
		TargetType = Ship,
		TargetName = "ter_poseidon",
		Icon = Icon_Build,
		ShortDisplayedName = "Sentry And Mine Deployer",
	},
	{
		Name = "BeamSentry",
		RequiredResearch = "SentryAndMineDeployer & FS2",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Beam Sentry <c=0e0160>(50s)</c>",
		DisplayPriority = 37,
		Description = "Unlocks Beam Sentries: Mjolnir.",
		TargetType = Ship,
		TargetName = "ter_mjolnir",
		Icon = Icon_Build,
		ShortDisplayedName = "Beam Sentry",
	},

	-- Utility ---------------
	{
		Name = "ScienceVessel",
		RequiredResearch = "CruiserDesign",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Science Vessel <c=0e0160>(50s)</c>",
		DisplayPriority = 25,
		Description = "Unlocks Science Vessels: Faustus.",
		TargetType = Ship,
		TargetName = "ter_faustus",
		Icon = Icon_Build,
		ShortDisplayedName = "Science Vessel",
	},
	{
		Name = "AWACS",
		RequiredResearch = "CruiserDesign & FS2",
		RequiredSubSystems = "",
		Cost = 2500,
		Time = 50,
		DisplayedName = "AWACS <c=0e0160>(50s)</c>",
		DisplayPriority = 30,
		Description = "Unlocks AWACS vessels: Charybdis.",
		TargetType = Ship,
		TargetName = "ter_charybdis",
		Icon = Icon_Build,
		ShortDisplayedName = "AWACS",
	},
	-- AI Only Nodes ---------
	{
		Name = "cpuplayers_defensive",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_aggressive",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_dynamic",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_norushtime5",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_norushtime10",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_norushtime15",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "AllShipBuildSpeedHard",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Capital",
		UpgradeName = "BUILDSPEED",
		UpgradeValue = 1.25,
		AIOnly = 1,
	},
	{
		Name = "AllShipBuildSpeedExpert",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Capital",
		UpgradeName = "BUILDSPEED",
		UpgradeValue = 1.5,
		AIOnly = 1,
	},
	{
		Name = "ResourceCollectionRateHard",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "ter_elysium",
		UpgradeName = "ResourceCollectionRate",
		UpgradeValue = 1.15,
		AIOnly = 1,
	},
	{
		Name = "ResourceCollectionRateExpert",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "ter_elysium",
		UpgradeName = "ResourceCollectionRate",
		UpgradeValue = 1.30,
		AIOnly = 1,
	},
}
