Icon_Speed = "data:ui/newui/research/icons/speed.mres"
Icon_Health = "data:ui/newui/research/icons/health.mres"
Icon_Tech = "data:ui/newui/research/icons/tech.mres"
Icon_Ability = "data:ui/newui/research/icons/ability.mres"
Icon_Build = "data:ui/newui/research/icons/build.mres"
Modifier = 0
Ability = 1
AllShips = 0
Family = 1
Ship = 2

research = {
	{
		Name = "FS1",
		RequiredResearch = "",
		RequiredSubSystems = "",
		--DoNotGrant = 1,
		Cost = 10,
		Time = 1,
		DisplayedName = "FreeSpace 1 Era",
		DisplayPriority = 0,
		Description = "Activates FreeSpace 1 ships and technology.",
		Icon = Icon_Tech,
		ShortDisplayedName = "FS1 Era",
	},
	{
		Name = "FS2",
		RequiredResearch = "",
		RequiredSubSystems = "",
		--DoNotGrant = 1,
		Cost = 10,
		Time = 1,
		DisplayedName = "FreeSpace 2 Era",
		DisplayPriority = 0,
		Description = "Activates FreeSpace 2 ships and technology.",
		Icon = Icon_Tech,
		ShortDisplayedName = "FS2 Era",
	},
	-- Era Switches (Hidden) ---

	-- Fighters --------------
	{
		Name = "FighterDesign",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 450,
		Time = 30,
		DisplayedName = "Fighter Design <c=0e0160>(30s)</c>",
		DisplayPriority = 1,
		Description = "Fighter chassis and drives. Required for all Fighter class research.",
		TargetType = Ship,
		TargetName = "ter_loki",
		Icon = Icon_Build,
		ShortDisplayedName = "Fighter Design <c=0e0160>(30s)</c>",
	},
	{
		Name = "Apollo",
		RequiredResearch = "FighterDesign & FS1",
		RequiredSubSystems = "",
		Cost = 675,
		Time = 40,
		DisplayedName = "Apollo <c=0e0160>(40s)</c>",
		DisplayPriority = 2,
		Description = "Unlocks the GTF Apollo Interceptor.",
		TargetType = Ship,
		TargetName = "ter_apollo",
		Icon = Icon_Build,
		ShortDisplayedName = "Apollo <c=0e0160>(40s)</c>",
	},
	{
		Name = "Valkyrie",
		RequiredResearch = "FighterDesign & Apollo",
		RequiredSubSystems = "",
		Cost = 675,
		Time = 40,
		DisplayedName = "Valkyrie <c=0e0160>(40s)</c>",
		DisplayPriority = 3,
		Description = "Unlocks the GTF Valkyrie Interceptor.",
		TargetType = Ship,
		TargetName = "ter_valkyrie",
		Icon = Icon_Build,
		ShortDisplayedName = "Valkyrie <c=0e0160>(40s)</c>",
	},
	{
		Name = "Hercules",
		RequiredResearch = "Valkyrie | (FighterDesign & FS2)",
		RequiredSubSystems = "",
		Cost = 1000,
		Time = 45,
		DisplayedName = "Hercules <c=0e0160>(45s)</c>",
		DisplayPriority = 4,
		Description = "Unlocks the GTF Hercules Assault Fighter.",
		TargetType = Ship,
		TargetName = "ter_hercules",
		Icon = Icon_Build,
		ShortDisplayedName = "Hercules <c=0e0160>(45s)</c>",
	},
	{
		Name = "Ulysses",
		RequiredResearch = "Hercules | (FighterDesign & FS2)",
		RequiredSubSystems = "",
		Cost = 1000,
		Time = 45,
		DisplayedName = "Ulysses <c=0e0160>(45s)</c>",
		DisplayPriority = 5,
		Description = "Unlocks the GTF Ulysses Space Superiority Fighter.",
		TargetType = Ship,
		TargetName = "ter_ulysses",
		Icon = Icon_Build,
		ShortDisplayedName = "Ulysses <c=0e0160>(45s)</c>",
	},
	{
		Name = "Myrmidon",
		RequiredResearch = "FighterDesign & FS2",
		RequiredSubSystems = "",
		Cost = 675,
		Time = 40,
		DisplayedName = "Myrmidon <c=0e0160>(40s)</c>",
		DisplayPriority = 6,
		Description = "Unlocks the GTF Myrmidon Space Superiority Fighter.",
		TargetType = Ship,
		TargetName = "ter_myrmidon",
		Icon = Icon_Build,
		ShortDisplayedName = "Myrmidon <c=0e0160>(40s)</c>",
	},
	{
		Name = "Perseus",
		RequiredResearch = "Myrmidon",
		RequiredSubSystems = "",
		Cost = 675,
		Time = 40,
		DisplayedName = "Perseus <c=0e0160>(40s)</c>",
		DisplayPriority = 7,
		Description = "Unlocks the GTF Perseus Interceptor.",
		TargetType = Ship,
		TargetName = "ter_perseus",
		Icon = Icon_Build,
		ShortDisplayedName = "Perseus <c=0e0160>(40s)</c>",
	},
	{
		Name = "HerculesMk2",
		RequiredResearch = "Perseus",
		RequiredSubSystems = "",
		Cost = 675,
		Time = 40,
		DisplayedName = "Hercules Mk2 <c=0e0160>(40s)</c>",
		DisplayPriority = 8,
		Description = "Unlocks the GTF Hercules Mk. II Assault Fighter.",
		TargetType = Ship,
		TargetName = "ter_herculesmk2",
		Icon = Icon_Build,
		ShortDisplayedName = "Hercules Mk2 <c=0e0160>(40s)</c>",
	},
	{
		Name = "Ares",
		RequiredResearch = "HerculesMk2",
		RequiredSubSystems = "",
		Cost = 825,
		Time = 45,
		DisplayedName = "Ares <c=0e0160>(45s)</c>",
		DisplayPriority = 9,
		Description = "Unlocks the GTF Ares Heavy Assault Fighter.",
		TargetType = Ship,
		TargetName = "ter_ares",
		Icon = Icon_Build,
		ShortDisplayedName = "Ares <c=0e0160>(45s)</c>",
	},
	{
		Name = "Erinyes",
		RequiredResearch = "Ares",
		RequiredSubSystems = "",
		Cost = 825,
		Time = 45,
		DisplayedName = "Erinyes <c=0e0160>(45s)</c>",
		DisplayPriority = 10,
		Description = "Unlocks the GTF Erinyes Heavy Assault Fighter.",
		TargetType = Ship,
		TargetName = "ter_erinyes",
		Icon = Icon_Build,
		ShortDisplayedName = "Erinyes <c=0e0160>(45s)</c>",
	},
	{
		Name = "Pegasus",
		RequiredResearch = "Erinyes",
		RequiredSubSystems = "",
		Cost = 450,
		Time = 30,
		DisplayedName = "Pegasus <c=0e0160>(30s)</c>",
		DisplayPriority = 11,
		Description = "Unlocks the GTF Pegasus Stealth Recon Fighter.",
		TargetType = Ship,
		TargetName = "ter_pegasus",
		Icon = Icon_Build,
		ShortDisplayedName = "Pegasus <c=0e0160>(30s)</c>",
	},

	-- Bombers ---------------
	{
		Name = "BomberDesign",
		RequiredResearch = "FighterDesign",
		RequiredSubSystems = "",
		Cost = 975,
		Time = 50,
		DisplayedName = "Bomber Design <c=0e0160>(50s)</c>",
		DisplayPriority = 1,
		Description = "Bomber chassis and drives. Required for all Bomber class research.",
		TargetType = Ship,
		TargetName = "ter_athena",
		Icon = Icon_Build,
		ShortDisplayedName = "Bomber Design <c=0e0160>(50s)</c>",
	},
	{
		Name = "Medusa",
		RequiredResearch = "BomberDesign",
		RequiredSubSystems = "",
		Cost = 975,
		Time = 50,
		DisplayedName = "Medusa <c=0e0160>(50s)</c>",
		DisplayPriority = 2,
		Description = "Unlocks the GTB Medusa Heavy Bomber.",
		TargetType = Ship,
		TargetName = "ter_medusa",
		Icon = Icon_Build,
		ShortDisplayedName = "Medusa <c=0e0160>(50s)</c>",
	},
	{
		Name = "Artemis",
		RequiredResearch = "Medusa & FS2",
		RequiredSubSystems = "",
		Cost = 975,
		Time = 50,
		DisplayedName = "Artemis <c=0e0160>(50s)</c>",
		DisplayPriority = 3,
		Description = "Unlocks the GTB Artemis Medium Bomber.",
		TargetType = Ship,
		TargetName = "ter_artemis",
		Icon = Icon_Build,
		ShortDisplayedName = "Artemis <c=0e0160>(50s)</c>",
	},
	{
		Name = "ArtemisDH",
		RequiredResearch = "Artemis",
		RequiredSubSystems = "",
		Cost = 975,
		Time = 50,
		DisplayedName = "ArtemisDH <c=0e0160>(50s)</c>",
		DisplayPriority = 4,
		Description = "Unlocks the GTB Artemis D.H. Advanced Bomber.",
		TargetType = Ship,
		TargetName = "ter_artemisdh",
		Icon = Icon_Build,
		ShortDisplayedName = "ArtemisDH <c=0e0160>(50s)</c>",
	},
	{
		Name = "Ursa",
		RequiredResearch = "Medusa",
		RequiredSubSystems = "",
		Cost = 1200,
		Time = 60,
		DisplayedName = "Ursa <c=0e0160>(60s)</c>",
		DisplayPriority = 5,
		Description = "Unlocks the GTB Ursa Assault Bomber.",
		TargetType = Ship,
		TargetName = "ter_ursa",
		Icon = Icon_Build,
		ShortDisplayedName = "Ursa <c=0e0160>(60s)</c>",
	},
	{
		Name = "Boanerges",
		RequiredResearch = "Ursa & FS2",
		RequiredSubSystems = "",
		Cost = 1200,
		Time = 60,
		DisplayedName = "Boanerges <c=0e0160>(60s)</c>",
		DisplayPriority = 6,
		Description = "Unlocks the GTB Boanerges Heavy Bomber.",
		TargetType = Ship,
		TargetName = "ter_boanerges",
		Icon = Icon_Build,
		ShortDisplayedName = "Boanerges <c=0e0160>(60s)</c>",
	},

	-- Cruisers --------------
	{
		Name = "CruiserDesign",
		RequiredResearch = "BomberDesign",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 60,
		DisplayedName = "Cruiser Design <c=0e0160>(60s)</c>",
		DisplayPriority = 1,
		Description = "Cruiser chassis and drives. Required for all Terran Cruiser class research.",
		TargetType = Ship,
		TargetName = "ter_fenris",
		Icon = Icon_Build,
		ShortDisplayedName = "Cruiser Design <c=0e0160>(60s)</c>",
	},
	{
		Name = "FenrisArmorUpgrade",
		RequiredResearch = "CruiserDesign",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Fenris Armor <c=0e0160>(50s)</c>",
		DisplayPriority = 2,
		Description = "Reinforced Armor plating for older Terran cruisers. Moderately increases health GTC Fenris class. Allows Production of GTC Leviathan class.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "ter_fenris",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.25,
		Icon = Icon_Health,
		ShortDisplayedName = "Fenris Armor",
	},
	{
		Name = "HeavyCruiser",
		RequiredResearch = "FenrisArmorUpgrade",
		RequiredSubSystems = "",
		Cost = 2250,
		Time = 80,
		DisplayedName = "Heavy Cruiser <c=0e0160>(80s)</c>",
		DisplayPriority = 3,
		Description = "Unlocks Heavy Cruisers: Leviathan.",
		TargetType = Ship,
		TargetName = "ter_leviathan",
		Icon = Icon_Build,
		ShortDisplayedName = "Heavy Cruiser <c=0e0160>(80s)</c>",
	},
	{
		Name = "Aeolus",
		RequiredResearch = "HeavyCruiser & FS2",
		RequiredSubSystems = "",
		Cost = 2250,
		Time = 80,
		DisplayedName = "Unlocks GTC Aeolus <c=0e0160>(80s)</c>",
		DisplayPriority = 4,
		Description = "Unlocks Aeolus class cruiser.",
		Icon = Icon_Build,
		TargetType = Ship,
		TargetName = "ter_aeolus",
		ShortDisplayedName = "Advanced Cruiser <c=0e0160>(80s)</c>",
	},

	-- Capital Ships ---------

	{
		Name = "CapitalShipDesign",
		RequiredResearch = "CruiserDesign",
		RequiredSubSystems = "",
		Cost = 7500,
		Time = 180,
		DisplayedName = "Capital Ship Design <c=0e0160>(180s)</c>",
		DisplayPriority = 1,
		Description = "Capital ship chassis and drives. Required for all Capital class research.",
		TargetType = Ship,
		TargetName = "ter_orion",
		Icon = Icon_Build,
		ShortDisplayedName = "Capital Ship Design <c=0e0160>(180s)</c>",
	},
	{
		Name = "Deimos",
		RequiredResearch = "CapitalShipDesign & FS2",
		RequiredSubSystems = "",
		Cost = 3750,
		Time = 120,
		DisplayedName = "Deimos <c=0e0160>(120s)</c>",
		DisplayPriority = 2,
		Description = "Unlocks Corvettes: Deimos.",
		TargetType = Ship,
		TargetName = "ter_deimos",
		Icon = Icon_Build,
		ShortDisplayedName = "Deimos <c=0e0160>(120s)</c>",
	},
	{
		Name = "DeimosArmor",
		RequiredResearch = "Deimos",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Deimos Armor <c=0e0160>(50s)</c>",
		DisplayPriority = 3,
		Description = "Increases health of GTCv Deimos by 12.5%.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "ter_deimos",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.125,
		Icon = Icon_Health,
		ShortDisplayedName = "Deimos Armor <c=0e0160>(50s)</c>",
	},
	{
		Name = "DeimosSprint",
		RequiredResearch = "Deimos",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Deimos Sprint <c=0e0160>(50s)</c>",
		DisplayPriority = 4,
		Description = "Improves the top speed of GTCv Deimos by 25%.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "ter_deimos",
		UpgradeName = "MaxSpeed",
		UpgradeValue = 1.25,
		Icon = Icon_Speed,
		ShortDisplayedName = "Deimos Sprint <c=0e0160>(50s)</c>",
	},
	{
		Name = "CommandCorvette",
		RequiredResearch = "Deimos & CapitalShipDesign",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Command Corvette <c=0e0160>(50s)</c>",
		DisplayPriority = 5,
		Description = "Unlocks Command Corvettes: Iceni.",
		TargetType = Ship,
		TargetName = "ter_iceni",
		Icon = Icon_Build,
		ShortDisplayedName = "Command Corvette <c=0e0160>(50s)</c>",
	},
	{
		Name = "Hecate",
		RequiredResearch = "CapitalShipDesign & FS2",
		RequiredSubSystems = "",
		Cost = 7500,
		Time = 180,
		DisplayedName = "Hecate <c=0e0160>(180s)</c>",
		DisplayPriority = 6,
		Description = "Unlocks the GTD Hecate Destroyer.",
		TargetType = Ship,
		TargetName = "ter_hecate",
		Icon = Icon_Build,
		ShortDisplayedName = "Hecate <c=0e0160>(180s)</c>",
	},
	{
		Name = "Installation",
		RequiredResearch = "CapitalShipDesign",
		RequiredSubSystems = "",
		Cost = 7500,
		Time = 180,
		DisplayedName = "Installation <c=0e0160>(180s)</c>",
		DisplayPriority = 7,
		Description = "Unlocks Installations: Arcadia.",
		TargetType = Ship,
		TargetName = "ter_arcadia",
		Icon = Icon_Build,
		ShortDisplayedName = "Installation <c=0e0160>(180s)</c>",
	},
	{
		Name = "SuperDestroyer",
		RequiredResearch = "CapitalShipDesign & Installation",
		RequiredSubSystems = "",
		Cost = 12000,
		Time = 240,
		DisplayedName = "SuperDestroyer <c=0e0160>(240s)</c>",
		DisplayPriority = 8,
		Description = "Unlocks Super Destroyers: Hades.",
		TargetType = Ship,
		TargetName = "ter_hades",
		Icon = Icon_Build,
		ShortDisplayedName = "SuperDestroyer <c=0e0160>(240s)</c>",
	},
	{
		Name = "Juggernaut",
		RequiredResearch = "SuperDestroyer & Installation & FS2",
		RequiredSubSystems = "",
		Cost = 22500,
		Time = 300,
		DisplayedName = "Juggernaut <c=0e0160>(300s)</c>",
		DisplayPriority = 9,
		Description = "Unlocks Juggernauts: Colossus.",
		TargetType = Ship,
		TargetName = "ter_colossus",
		Icon = Icon_Build,
		ShortDisplayedName = "Juggernaut <c=0e0160>(300s)</c>",
	},

	-- Platforms -------------
	{
		Name = "SentryGun",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 750,
		Time = 20,
		DisplayedName = "Sentry Gun <c=0e0160>(20s)</c>",
		DisplayPriority = 1,
		Description = "Unlocks Sentry Guns: Alastor, Cerberus.",
		TargetType = Ship,
		TargetName = "ter_alastor",
		Icon = Icon_Build,
		ShortDisplayedName = "Sentry Gun <c=0e0160>(20s)</c>",
	},
	{
		Name = "SentryAndMineDeployer",
		RequiredResearch = "SentryGun",
		RequiredSubSystems = "",
		Cost = 750,
		Time = 20,
		DisplayedName = "Sentry And Mine Deployer <c=0e0160>(20s)</c>",
		DisplayPriority = 2,
		Description = "Unlocks Sentry and Mine Deployers: Poseidon.",
		TargetType = Ship,
		TargetName = "ter_poseidon",
		Icon = Icon_Build,
		ShortDisplayedName = "Sentry And Mine Deployer <c=0e0160>(20s)</c>",
	},
	{
		Name = "BeamSentry",
		RequiredResearch = "SentryAndMineDeployer & FS2",
		RequiredSubSystems = "",
		Cost = 750,
		Time = 20,
		DisplayedName = "Beam Sentry <c=0e0160>(20s)</c>",
		DisplayPriority = 3,
		Description = "Unlocks Beam Sentries: Mjolnir.",
		TargetType = Ship,
		TargetName = "ter_mjolnir",
		Icon = Icon_Build,
		ShortDisplayedName = "Beam Sentry <c=0e0160>(20s)</c>",
	},

	-- Utility ---------------
	{
		Name = "ScienceVessel",
		RequiredResearch = "CruiserDesign & FS1",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "Science Vessel <c=0e0160>(50s)</c>",
		DisplayPriority = 1,
		Description = "Unlocks Science Vessels: Faustus.",
		TargetType = Ship,
		TargetName = "ter_faustus",
		Icon = Icon_Build,
		ShortDisplayedName = "Science Vessel <c=0e0160>(50s)</c>",
	},
	{
		Name = "AWACS",
		RequiredResearch = "CruiserDesign & FS2",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "AWACS <c=0e0160>(50s)</c>",
		DisplayPriority = 2,
		Description = "Advanced Warning and Control systems for GTA Charybids AWACS. Effectively doubles friendly sensor ranges in proximity to AWACS.",
		TargetType = Ship,
		TargetName = "ter_charybdis",
		Icon = Icon_Tech,
		ShortDisplayedName = "AWACS <c=0e0160>(50s)</c>",
	},
	{
		Name = "RepairChronos",
		RequiredResearch = "CruiserDesign & FS1",
		RequiredSubSystems = "",
		Cost = 675,
		Time = 40,
		DisplayedName = "Repair Chronos <c=0e0160>(40s)</c>",
		DisplayPriority = 3,
		Description = "Unlocks Repair Frigates",
		TargetType = Ship,
		TargetName = "ter_chronos",
		Icon = Icon_Build,
		ShortDisplayedName = "Repair Chronos <c=0e0160>(40s)</c>",
	},
	{
		Name = "RepairArgo",
		RequiredResearch = "CruiserDesign & FS2",
		RequiredSubSystems = "",
		Cost = 675,
		Time = 40,
		DisplayedName = "GTT Argo <c=0e0160>(40s)</c>",
		DisplayPriority = 4,
		Description = "Unlocks Repair Transport Argo",
		TargetType = Ship,
		TargetName = "ter_argo",
		Icon = Icon_Build,
		ShortDisplayedName = "GTT Argo <c=0e0160>(40s)</c>",
	},


	-- Subsystems
	{
		Name = "AWACSLVL2",
		RequiredResearch = "AWACS | ScienceVessel",
		RequiredSubSystems = "",
		Cost = 2500,
		Time = 50,
		DisplayPriority = 1,
		Description = "Enhanced defensive Electronic Warfare (EW) suite for AWACS Vessel. Friendly ships are are detected in 70% of normal range while in AWACS area.",
		TargetType = Ship,
		TargetName = "ter_charybdis",
		UpgradeType = Modifier,
		UpgradeName = "SensorDistortion",
		UpgradeValue = 0.7,
		Icon = Icon_Health,
		ShortDisplayedName = "AWACS Level II",
	},
	{
		Name = "AWACSLVL3",
		RequiredResearch = "AWACSLVL2",
		RequiredSubSystems = "",
		Cost = 1500,
		Time = 50,
		DisplayedName = "AWACS LVL3 - Offensive EW<c=0e0160>(50s)</c>",
		DisplayPriority = 2,
		Description = "Enhanced offensive Electronic Warfare (EW) suite for AWACS vessel. Enemy vessels have 30% reduced accuracy while in friendly AWACS range.",
		TargetType = Ship,
		TargetName = "ter_charybdis",
		UpgradeType = Ability,
		UpgradeName = "SensorPing",
		Icon = Icon_Ability,
		ShortDisplayedName = "AWACS Level III",
	},

	-- AI Only Nodes ---------
	{
		Name = "cpuplayers_defensive",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_aggressive",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_dynamic",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_norushtime5",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_norushtime10",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "cpuplayers_norushtime15",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		AIOnly = 1,
	},
	{
		Name = "AllShipBuildSpeedHard",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Capital",
		UpgradeName = "BUILDSPEED",
		UpgradeValue = 1.25,
		AIOnly = 1,
	},
	{
		Name = "AllShipBuildSpeedExpert",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Capital",
		UpgradeName = "BUILDSPEED",
		UpgradeValue = 1.5,
		AIOnly = 1,
	},
	{
		Name = "ResourceCollectionRateHard",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "ter_elysium",
		UpgradeName = "ResourceCollectionRate",
		UpgradeValue = 1.15,
		AIOnly = 1,
	},
	{
		Name = "ResourceCollectionRateExpert",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 1,
		Time = 1,
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "ter_elysium",
		UpgradeName = "ResourceCollectionRate",
		UpgradeValue = 1.30,
		AIOnly = 1,
	},
}
