NON_NEGOTIABLES = {
    "sections": [
        "Tactics and Multipliers",
        "Main Ship Data",
        "Formations",
        "Docking",
        "Death Tumble",
        "Swaying",
        "Families",
        "Special Flight Maneuvers",
        "Supply",
        "Ship Counter Rating",
        "Sensors",
        "Tactical Overlay Icon",
        "Overlays",
        "Non linear Scaling",
        "Rendering",
        "Selection",
        "Abilities",
        "Launching",
        "Alternative Hyperspace Gate",
        "Load Model",
        "Scuttle",
    ],
    "variables": [
        "sobDescription",
        "maxhealth",
        "sideArmourDamage",
        "rearArmourDamage",
        "buildBatch",
        "disableOnRaceChange",
    ],
    "functions": ["loadShipPatchList"],
    "addAbilityFunction": [],
}

TEMPLATE = {
    "Ship info": {
        "variables": {"displayedName": '"Deimos"', "sobDescription": "Corvette"},
        "functions": [],
    },
    "Health and Armour": {
        "variables": {
            "maxhealth": 'getShipNum(NewShipType, "maxhealth", 85000)',
            "regentime": "1074",
            "minRegenTime": "1074",
            "sideArmourDamage": 'getShipNum(NewShipType, "sideArmourDamage", 1.0)',
            "rearArmourDamage": 'getShipNum(NewShipType, "rearArmourDamage", 1.2)',
        },
        "functions": [],
    },
    "Tactics And Multipliers": {
        "variables": {"defaultROE": '"Defensive"', "defaultStance": '"Neutral"'},
        "functions": [
            {"name": "setTacticsMults", "args": ["ENGINEACCEL", "1.10", "0.90", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["THRUSTERACCEL", "1.10", "0.90", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["ROTATION", "0.95", "1.05", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["ROTATIONACCEL", "1.10", "0.90", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["FIRERATE", "0.98", "1.02", "1.0"]},
        ],
    },
    "Main Ship Data": {"variables": {"isTransferable": "1"}, "functions": []},
    "Movement": {
        "variables": {
            "mass": "500",
            "thrusterMaxSpeed": "120",
            "mainEngineMaxSpeed": "120",
            "rotationMaxSpeed": "9",
            "thrusterAccelTime": "6",
            "thrusterBrakeTime": "2",
            "mainEngineAccelTime": "6",
            "mainEngineBrakeTime": "2",
            "rotationAccelTime": "0.5",
            "rotationBrakeTime": "0.3",
        },
        "functions": [],
    },
    "Damage & Death": {
        "variables": {
            "collisionMultiplier": "1",
            "dustCloudDamageTime": "160",
            "nebulaDamageTime": "300",
            "battleScarCoverage": "3",
            "battleScarBudgetLow": "600",
            "battleScarBudgetNext": "900",
            "sobDieTime": "4.9",
            "sobSpecialDieTime": "1",
            "specialDeathSpeed": "40",
            "chanceOfSpecialDeath": "0",
            "deadSobFadeTime": "0.1",
        },
        "functions": [],
    },
    "Advanced Movement": {
        "variables": {
            "thrusterUsage": "1",
            "accelerationAngle": "30",
            "mirrorAngle": "0",
            "secondaryTurnAngle": "0",
            "maxBankingAmount": "20",
            "descendPitch": "10",
            "goalReachEpsilon": "25",
            "slideMoveRange": "350",
            "controllerType": '"Ship"',
            "relativeMoveFactor": "1",
        },
        "functions": [],
    },
    "Death Tumble": {
        "variables": {
            "tumbleStaticX": "10",
            "tumbleStaticY": "20",
            "tumbleStaticZ": "5",
            "tumbleDynamicX": "2",
            "tumbleDynamicY": "10",
            "tumbleDynamicZ": "5",
            "tumbleSpecialDynamicX": "2",
            "tumbleSpecialDynamicY": "10",
            "tumbleSpecialDynamicZ": "5",
        },
        "functions": [],
    },
    "Layout Boundary": {
        "variables": {
            "useLayoutBounds": "1",
            "layoutBoundX": "60",
            "layoutBoundY": "60",
            "layoutBoundZ": "230",
            "layoutCenterX": "0",
            "layoutCenterY": "0",
            "layoutCenterZ": "20",
        },
        "functions": [],
    },
    "Families": {
        "variables": {
            "MinimalFamilyToFindPathAround": '"MotherShip"',
            "BuildFamily": '"SuperCap_Ter"',
            "AttackFamily": '"SmallCapitalShip"',
            "DockFamily": '"SuperCap"',
            "AvoidanceFamily": '"Capital"',
            "DisplayFamily": '"Capital"',
            "AutoFormationFamily": '"CapShip"',
            "CollisionFamily": '"Big"',
            "ArmourFamily": 'getShipStr(NewShipType, "ArmourFamily", "HeavyArmour")',
        },
        "functions": [],
    },
    "Supply": {
        "variables": {},
        "functions": [
            {"name": "setSupplyValue", "args": ["Capital", "1.0"]},
            {"name": "setSupplyValue", "args": ["Deimos", "1.0"]},
        ],
    },
    "Ship Counter Rating": {
        "variables": {
            "fighterValue": "0",
            "corvetteValue": "0",
            "frigateValue": "40",
            "neutralValue": "10",
            "antiFighterValue": "0",
            "antiCorvetteValue": "0",
            "antiFrigateValue": "30",
            "totalValue": "50",
        },
        "functions": [],
    },
    "Construction": {
        "variables": {
            "buildCost": "2000",
            "buildTime": "165",
            "buildPriorityOrder": "20",
        },
        "functions": [],
    },
    "Sensors": {
        "variables": {
            "retaliationRange": "6000",
            "retaliationDistanceFromGoal": "160",
            "visualRange": "1000",
            "prmSensorRange": "6500",
            "secSensorRange": "7500",
            "detectionStrength": "1",
        },
        "functions": [],
    },
    "Tactical Overlay Icon": {
        "variables": {
            "TOIcon": '"Parallelogram"',
            "TOScale": "1",
            "TODistanceFade0": "11000",
            "TODistanceDisappear0": "9000",
            "TODistanceFade1": "5500",
            "TODistanceDisappear1": "5000",
            "TODistanceFade2": "12000",
            "TODistanceDisappear2": "35000",
            "TOGroupScale": "1",
            "TOGroupMergeSize": "0",
        },
        "functions": [],
    },
    "Overlays": {
        "variables": {
            "mouseOverMinFadeSize": "0.045",
            "mouseOverMaxFadeSize": "0.1",
            "healthBarStyle": "2",
            "SMRepresentation": '"Mesh"',
            "SMHighlightDistMin": "15000",
            "SMHighlightDistMax": "25000",
        },
        "functions": [],
    },
    "Non linear Scaling": {
        "variables": {
            "nlips": "0.00007",
            "nlipsRange": "6000",
            "nlipsFar": "0.000013",
            "nlipsFarRange": "10000",
        },
        "functions": [],
    },
    "Rendering": {
        "variables": {
            "meshRenderLimit": "18000",
            "dotRenderLimit": "10",
            "visibleInSecondary": "1",
            "goblinsStartFade": "2150",
            "goblinsOff": "2150",
            "minimumZoomFactor": "0.5",
        },
        "functions": [],
    },
    "Level of Detail": {
        "variables": {"minLOD": "0.25", "upLOD": "4500", "downLOD": "4150"},
        "functions": [],
    },
    "Selection": {
        "variables": {
            "selectionLimit": "150000",
            "preciseSelectionLimit": "5000",
            "preciseATILimit": "0",
            "selectionPriority": "75",
            "militaryUnit": "1",
        },
        "functions": [],
    },
    "Alternative Hyperspace Gate": {
        "variables": {
            "alternativeHyperspaceV": "subspace_gate_small",
            "alternativeHyperspaceA": "etg/misc/small_subspace",
            "alternativeHyperspaceTime": "7",
        },
        "functions": [],
    },
    "Abilities": {
        "variables": {},
        "functions": [
            {"name": "addAbility", "args": ["MoveCommand", "1", "0"]},
            {"name": "addAbility", "args": ["ParadeCommand", "1"]},
            {"name": "addAbility", "args": ['WaypointMove"']},
            {
                "name": "addAbility",
                "args": ["HyperSpaceCommand", "1", "1", "350", "1050", "0", "3"],
            },
            {
                "name": "addAbility",
                "args": [
                    "CanAttack",
                    "1",
                    "1",
                    "0",
                    "0",
                    "0.35",
                    "1.5",
                    "Munition, BigCapitalShip, SmallCapitalShip, Capturer, Mothership, Frigate, Corvette, Fighter, Utility",
                    "MoveToTargetAndShoot",
                    '{Fighter="MoveToTargetAndShoot"}',
                    '{Fighter_hw1="MoveToTargetAndShoot"}',
                    '{Corvette="MoveToTargetAndShoot"}',
                    '{Corvette_hw1="MoveToTargetAndShoot"}',
                    '{Munition="MoveToTargetAndShoot"}',
                    '{SubSystem="MoveToTargetAndShoot"}',
                ],
            },
            {"name": "addAbility", "args": ["GuardCommand", "1", "3000", "800"]},
            {
                "name": "addAbility",
                "args": ["HyperspaceViaGateCommand", "1", "3", "3.5", "0.3"],
            },
            {"name": "addAbility", "args": ["CanBeCaptured", "90", "0.5", 'CapCap"']},
            {"name": "addAbility", "args": ["CanBeRepaired", 'RepCap"']},
            
        ],
    },
    "Formations": {
        "variables": {"strikeGroupRadius": "200", "canSurround": "1"},
        "functions": [],
    },
    "Load Model": {
        "variables": {},
        "functions": [{"name": "LoadModel", "args": ["1"]}],
    },
    "HardPoints": {
        "variables": {},
        "functions": [],
    },
    "Weapons": {
        "variables": {},
        "functions": [],
    },
    "Shields": {
        "variables": {},
        "functions": [{"name": "addShield", "args": ["EMP", "1000", "20"]}],
    },
    "Engines": {
        "variables": {"trailLinger": "3"},
        "functions": [
            {
                "name": "setEngineBurn",
                "args": ["7", "0.5", "3", "80", "0", "0.7", "0.1", "280"],
            },
        ],
    },
    "Addendum": {
        "variables": {},
        "functions": [
            {
                "name": "loadShipPatchList",
                "args": [
                    "data:sound/sfx/ship/",
                    "0",
                    "",
                    "",
                    "1",
                    "TerranCapital",
                    "",
                ],
            }
        ],
    },
    "Latch Points": {
        "variables": {},
        "functions": [
            {
                "name": "loadLatchPointList",
                "args": [
                    "CapCap",
                    "CapturePoint0",
                    "CapturePoint1",
                    "CapturePoint2",
                    "CapturePoint3",
                ],
            },
            {
                "name": "loadLatchPointList",
                "args": [
                    "RepCap",
                    "RepairPoint0",
                    "RepairPoint1",
                    "RepairPoint2",
                    'RepairPoint3"',
                ],
            },
        ],
    },
    "Scuttle": {
        "variables": {
            "minFalloffDamageDist": "250",
            "maxFalloffDamageDist": "250*1.5",
            "maxFalloffScuttleDamageDist": "250*3",
            "explosiveScuttleDamageOnDeath": "2688",
            "maxFalloffForce": "500*10",
            "explosiveDamageOnDeath": "538",
            "radiusDamageEvadeMod": "1.1",
        },
        "functions": [],
    },
}
