NON_NEGOTIABLES = {
    "sections": [
        "Tactics and Multipliers",
        "Main Ship Data",
        "Docking",
        "Death Tumble",
        "Swaying",
        "Families",
        "Special Flight Maneuvers",
        "Supply",
        "Ship Counter Rating",
        "Sensors",
        "Tactical Overlay Icon",
        "Overlays",
        "Non linear Scaling",
        "Rendering",
        "Selection",
        "Abilities",
        "Launching",
        "Alternative Hyperspace Gate",
        "Load Model",
        "Scuttle",
    ],
    "variables": [
        "sobDescription",
        "maxhealth",
        "sideArmourDamage",
        "rearArmourDamage",
        "buildBatch",
        "disableOnRaceChange",
    ],
    "functions": ["loadShipPatchList"],
    "addAbilityFunction": [],
}

TEMPLATE = {
    "Ship info": {
        "variables": {"displayedName": '"$1542"', "sobDescription": '"Destroyer"'},
        "functions": [],
    },
    "Health and Armour": {
        "variables": {
            "maxhealth": 'getShipNum(NewShipType, "maxhealth", 80000)',
            "regentime": "2000",
            "minRegenTime": "2000",
            "sideArmourDamage": 'getShipNum(NewShipType, "sideArmourDamage", 1.0)',
            "rearArmourDamage": 'getShipNum(NewShipType, "rearArmourDamage", 1.0)',
        },
        "functions": [],
    },
    "Tactics And Multipliers": {
        "variables": {"defaultROE": '"Defensive"', "defaultStance": '"Neutral"'},
        "functions": [
            {"name": "setTacticsMults", "args": ["ENGINEACCEL", "1.10", "0.90", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["THRUSTERACCEL", "1.10", "0.90", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["ROTATION", "0.95", "1.05", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["ROTATIONACCEL", "1.10", "0.90", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["FIRERATE", "0.98", "1.02", "1.0"]},
        ],
    },
    "Main Ship Data": {"variables": {"isTransferable": "0"}, "functions": []},
    "Deprecated": {"variables": {"addedUnitCaps": "101"}, "functions": []},
    "Formations": {
        "variables": {
            "paradeData": '"your_parade_here"',
            "strikeGroupRadius": "150",
            "noCombatGrouping": "1",
            "canSurround": "1",
        },
        "functions": [],
    },
    "Movement": {
        "variables": {
            "mass": "1000",
            "thrusterMaxSpeed": "81",
            "mainEngineMaxSpeed": "81",
            "rotationMaxSpeed": "8",
            "thrusterAccelTime": "6",
            "thrusterBrakeTime": "2",
            "mainEngineAccelTime": "6",
            "mainEngineBrakeTime": "2",
            "rotationAccelTime": "0.5",
            "rotationBrakeTime": "0.3",
        },
        "functions": [],
    },
    "Damage & Death": {
        "variables": {
            "collisionMultiplier": "1",
            "dustCloudDamageTime": "200",
            "nebulaDamageTime": "300",
            "battleScarCoverage": "4",
            "battleScarBudgetLow": "800",
            "battleScarBudgetNext": "1200",
            "sobDieTime": "9.4",
            "sobSpecialDieTime": "4",
            "specialDeathSpeed": "40",
            "chanceOfSpecialDeath": "0",
            "deadSobFadeTime": "0.01",
        },
        "functions": [],
    },
    "Advanced Movement": {
        "variables": {
            "thrusterUsage": "1",
            "accelerationAngle": "30",
            "mirrorAngle": "0",
            "secondaryTurnAngle": "0",
            "maxBankingAmount": "10",
            "descendPitch": "10",
            "goalReachEpsilon": "25",
            "slideMoveRange": "350",
            "controllerType": '"Ship"',
            "relativeMoveFactor": "1",
        },
        "functions": [],
    },
    "Death Tumble": {
        "variables": {
            "tumbleStaticX": "2",
            "tumbleStaticY": "4",
            "tumbleStaticZ": "3",
            "tumbleDynamicX": "1",
            "tumbleDynamicY": "2",
            "tumbleDynamicZ": "2",
            "tumbleSpecialDynamicX": "1",
            "tumbleSpecialDynamicY": "2",
            "tumbleSpecialDynamicZ": "2",
        },
        "functions": [],
    },
    "Swaying": {
        "variables": {
            "swayUpdateTime": "10",
            "swayOffsetRandomX": "10",
            "swayOffsetRandomY": "10",
            "swayOffsetRandomZ": "10",
            "swayBobbingFactor": "0",
            "swayRotateFactor": "0",
        },
        "functions": [],
    },
    "Layout Boundary": {
        "variables": {
            "useLayoutBounds": "1",
            "layoutBoundX": "130",
            "layoutBoundY": "60",
            "layoutBoundZ": "350",
            "layoutCenterX": "-20",
            "layoutCenterY": "0",
            "layoutCenterZ": "50",
        },
        "functions": [],
    },
    "Families": {
        "variables": {
            "MinimalFamilyToFindPathAround": '"MotherShip"',
            "BuildFamily": '"SuperCap_Ter"',
            "AttackFamily": '"BigCapitalShip"',
            "DockFamily": '"Shipyard"',
            "AvoidanceFamily": '"SuperCap"',
            "DisplayFamily": '"Capital"',
            "AutoFormationFamily": '"CapShip"',
            "CollisionFamily": '"Big"',
            "ArmourFamily": 'getShipStr(NewShipType, "ArmourFamily", "HeavyArmour")',
        },
        "functions": [],
    },
    "Supply": {
        "variables": {},
        "functions": [
            {"name": "setSupplyValue", "args": ["Capital", "1.0"]},
            {"name": "setSupplyValue", "args": ["Destroyer", "1.0"]},
        ],
    },
    "Ship Counter Rating": {
        "variables": {
            "AttackPriorityMultiplier": "0.96",
            "fighterValue": "0",
            "corvetteValue": "0",
            "frigateValue": "10",
            "neutralValue": "5",
            "antiFighterValue": "5",
            "antiCorvetteValue": "0",
            "antiFrigateValue": "0",
            "totalValue": "15",
        },
        "functions": [],
    },
    "Construction": {
        "variables": {
            "buildCost": "2800",
            "buildTime": "65",
            "buildPriorityOrder": "30",
        },
        "functions": [],
    },
    "Sensors": {
        "variables": {
            "retaliationRange": "6500",
            "retaliationDistanceFromGoal": "160",
            "visualRange": "1000",
            "prmSensorRange": "5000",
            "secSensorRange": "6000",
            "detectionStrength": "1",
        },
        "functions": [],
    },
    "Tactical Overlay Icon": {
        "variables": {
            "TOIcon": '"Rectangle"',
            "TOScale": "1",
            "TODistanceFade0": "14000",
            "TODistanceDisappear0": "12000",
            "TODistanceFade1": "5500",
            "TODistanceDisappear1": "5000",
            "TODistanceFade2": "12000",
            "TODistanceDisappear2": "35000",
            "TOGroupScale": "1",
            "TOGroupMergeSize": "0",
        },
        "functions": [],
    },
    "Overlays": {
        "variables": {
            "mouseOverMinFadeSize": "0.085",
            "mouseOverMaxFadeSize": "0.15",
            "healthBarStyle": "2",
            "SMRepresentation": '"Mesh"',
            "SMHighlightDistMin": "20000",
            "SMHighlightDistMax": "25000",
            "hideNormalAttackUICooldown": "1",
        },
        "functions": [],
    },
    "Non linear Scaling": {
        "variables": {
            "nlips": "0",
            "nlipsRange": "10000",
            "nlipsFar": "0",
            "nlipsFarRange": "0",
        },
        "functions": [],
    },
    "Rendering": {
        "variables": {
            "meshRenderLimit": "21000",
            "dotRenderLimit": "10",
            "visibleInSecondary": "1",
            "goblinsStartFade": "3200",
            "goblinsOff": "3200",
            "minimumZoomFactor": "0.5",
        },
        "functions": [],
    },
    "Level of Detail": {
        "variables": {"upLOD": "6150", "downLOD": "6165"},
        "functions": [],
    },
    "Selection": {
        "variables": {
            "selectionLimit": "150000",
            "preciseSelectionLimit": "7500",
            "preciseATILimit": "0",
            "selectionPriority": "75",
            "militaryUnit": "0",
        },
        "functions": [],
    },
    "Abilities": {
        "variables": {},
        "functions": [
            {"name": "addAbility", "args": ["MoveCommand", "1", "0"]},
            {"name": "addAbility", "args": ["CanDock", "1", "0"]},
            {"name": "addAbility", "args": ['CanLaunch"']},
            {
                "name": "addAbility",
                "args": [
                    "ShipHold",
                    "1",
                    "1000",
                    "20",
                    "rallypoint",
                    "Fighter, Corvette, Utility",
                    "200",
                ],
            },
            {"name": "addAbility", "args": ["ParadeCommand", "1"]},
            {"name": "addAbility", "args": ['WaypointMove"']},
            {
                "name": "addAbility",
                "args": ["HyperSpaceCommand", "1", "1", "875", "1750", "0", "3"],
            },
            {
                "name": "addAbility",
                "args": [
                    "CanAttack",
                    "1",
                    "1",
                    "0",
                    "1",
                    "0.35",
                    "1.5",
                    "Capturer,Frigate,SmallCapitalShip,BigCapitalShip,Mothership,Utility,,,,,Corvette, Corvette_hw1,Fighter, Fighter_hw1",
                    "Broadside",
                    '{ Fighter = "MoveToTargetAndShoot" }',
                    '{ Fighter_hw1 = "MoveToTargetAndShoot" }',
                    '{ Corvette = "MoveToTargetAndShoot" }',
                    '{ Corvette_hw1 = "MoveToTargetAndShoot" }',
                    '{ Munition = "MoveToTargetAndShoot" }',
                ],
            },
            {"name": "addAbility", "args": ["GuardCommand", "1", "3000", "1000"]},
            {
                "name": "addAbility",
                "args": [
                    "CanBuildShips",
                    "1",
                    "Fighter_Ter, Bomber_Ter, Cruiser_Ter, SuperCap_Ter, Utility_Ter, Platform_Ter, Battlecruiser_Ter, Shipyard_Ter, Probe_Ter",
                    "Utility, Fighter, Bomber, Cruiser, Capital, Platform",
                ],
            },
            {
                "name": "addAbility",
                "args": ["CanBeCaptured", "180", "0.5", 'CapCap"'],
            },
            {"name": "addAbility", "args": ["CanBeRepaired", 'RepCap"']},
            {"name": "addAbility", "args": ["RetireAbility", "1", "1"]},
        ],
    },
    "Docking": {
        "variables": {
            "dockTimeBetweenTwoFormations": "1",
            "dockTimeBeforeStart": "2",
            "dockNrOfShipsInDockFormation": "1",
            "dockFormation": '"delta"',
            "queueFormation": '"dockline"',
            "dontDockWithOtherRaceShips": "1",
            "ignoreRaceWhenDocking": "0",
        },
        "functions": [],
    },
    "Launching": {
        "variables": {
            "launchTimeBetweenTwoFormations": "1",
            "launchTimeBeforeStart": "2",
            "launchNrOfShipsInDockFormation": "1",
            "launchFormation": '"delta"',
        },
        "functions": [],
    },
    "Custom Code": {
        "variables": {},
        "functions": [
        ],
    },
    "Load Model": {
        "variables": {},
        "functions": [{"name": "LoadModel", "args": ["1"]}],
    },
    "Weapons": {
        "variables": {},
        "functions": [
        ],
    },
    "Shields": {
        "variables": {},
        "functions": [{"name": "addShield", "args": ["EMP", "10000", "20"]}],
    },
    "HardPoints": {
        "variables": {},
        "functions": [
        ],
    },
    "Debris": {
        "variables": {},
        "functions": [
        ],
    },
    "Engines": {
        "variables": {"trailLinger": "6"},
        "functions": [
            {
                "name": "setEngineBurn",
                "args": ["9", "0.2", "0.5", "300", "1.02", "0.1", "0.25", "380"],
            },
            {
                "name": "setEngineGlow",
                "args": [
                    "1",
                    "1",
                    "1.02",
                    "20",
                    "300",
                    "50",
                    "1.5",
                    "0.47",
                ],
            },
        ],
    },
    "Addendum": {
        "variables": {},
        "functions": [
            {
                "name": "loadShipPatchList",
                "args": [
                    "data:sound/sfx/ship/",
                    "0",
                    "",
                    "",
                    "1",
                    "TerranCapital",
                    "",
                ],
            }
        ],
    },
    "Latch Points": {
        "variables": {},
        "functions": [
            {
                "name": "loadLatchPointList",
                "args": [
                    "CapCap",
                    "CapturePoint1",
                    "CapturePoint2",
                    "CapturePoint3",
                    'CapturePoint4"',
                    'CapturePoint5"',
                ],
            },
            {
                "name": "loadLatchPointList",
                "args": [
                    "RepCap",
                    "RepairPoint0",
                    "RepairPoint1",
                    "RepairPoint2",
                    "RepairPoint3",
                    'RepairPoint4"',
                    'RepairPoint5"',
                ],
            },
        ],
    },
    "Scuttle": {
        "variables": {
            "minFalloffDamageDist": "450",
            "maxFalloffDamageDist": "450*1.5",
            "maxFalloffScuttleDamageDist": "450*3",
            "explosiveScuttleDamageOnDeath": "1960",
            "maxFalloffForce": "500*10",
            "explosiveDamageOnDeath": "275",
            "radiusDamageEvadeMod": "1.1",
        },
        "functions": [],
    },
}
