NON_NEGOTIABLES = {
    "sections": [
        "Tactics and Multipliers",
        "Main Ship Data",
        "Docking",
        "Death Tumble",
        "Swaying",
        "Families",
        "Special Flight Maneuvers",
        "Supply",
        "Ship Counter Rating",
        "Sensors",
        "Tactical Overlay Icon",
        "Overlays",
        "Non linear Scaling",
        "Rendering",
        "Selection",
        "Launching",
        "Alternative Hyperspace Gate",
        "Load Model",
        "Scuttle",
    ],
    "variables": [
        "sobDescription",
        "sideArmourDamage",
        "rearArmourDamage",
        "buildBatch",
        "disableOnRaceChange",
    ],
    "functions": [],
    "addAbilityFunction": [
        "MoveCommand",
        "CanDock",
        "CanLaunch",
        "ParadeCommand",
        "WaypointMove",
        "CanAttack",
        "GuardCommand",
        "CanBuildShips",
        "CanBeCaptured",
        "CanBeRepaired",
    ],
}

TEMPLATE = {
    "Ship info": {
        "variables": {"displayedName": '"SD"', "sobDescription": '"Super Destroyer"'},
        "functions": [],
    },
    "Health and Armour": {
        "variables": {
            "maxhealth": 'getShipNum(NewShipType, "maxhealth", 192000)',
            "regentime": "2000",
            "minRegenTime": "2000",
            "sideArmourDamage": 'getShipNum(NewShipType, "sideArmourDamage", 1.0)',
            "rearArmourDamage": 'getShipNum(NewShipType, "rearArmourDamage", 1.0)',
        },
        "functions": [],
    },
    "Tactics And Multipliers": {
        "variables": {"defaultROE": '"Defensive"', "defaultStance": '"Neutral"'},
        "functions": [
            {"name": "setTacticsMults", "args": ["ENGINEACCEL", "1.10", "0.90", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["THRUSTERACCEL", "1.10", "0.90", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["ROTATION", "0.95", "1.05", "1.0"]},
            {
                "name": "setTacticsMults",
                "args": ["ROTATIONACCEL", "1.10", "0.90", "1.0"],
            },
            {"name": "setTacticsMults", "args": ["FIRERATE", "0.98", "1.02", "1.0"]},
        ],
    },
    "Main Ship Data": {"variables": {"isTransferable": "0"}, "functions": []},
    "Formations": {
        "variables": {
            "paradeData": '"your_parade_here"',
            "strikeGroupRadius": "200",
            "noCombatGrouping": "1",
            "canSurround": "1",
        },
        "functions": [],
    },
    "Movement": {
        "variables": {
            "mass": "1000",
            "thrusterMaxSpeed": "79",
            "mainEngineMaxSpeed": "79",
            "rotationMaxSpeed": "6",
            "thrusterAccelTime": "6",
            "thrusterBrakeTime": "2",
            "mainEngineAccelTime": "6",
            "mainEngineBrakeTime": "2",
            "rotationAccelTime": "0.7",
            "rotationBrakeTime": "0.4",
        },
        "functions": [],
    },
    "Damage & Death": {
        "variables": {
            "collisionMultiplier": "1",
            "dustCloudDamageTime": "280",
            "nebulaDamageTime": "800",
            "battleScarCoverage": "4",
            "battleScarBudgetLow": "800",
            "battleScarBudgetNext": "1200",
            "sobDieTime": "9.4",
            "sobSpecialDieTime": "1",
            "specialDeathSpeed": "40",
            "chanceOfSpecialDeath": "0",
            "deadSobFadeTime": "0.01",
        },
        "functions": [],
    },
    "Advanced Movement": {
        "variables": {
            "thrusterUsage": "1",
            "accelerationAngle": "30",
            "mirrorAngle": "0",
            "secondaryTurnAngle": "0",
            "maxBankingAmount": "10",
            "descendPitch": "5",
            "goalReachEpsilon": "25",
            "slideMoveRange": "350",
            "controllerType": '"Ship"',
            "relativeMoveFactor": "1",
        },
        "functions": [],
    },
    "Death Tumble": {
        "variables": {
            "tumbleStaticX": "2",
            "tumbleStaticY": "4",
            "tumbleStaticZ": "3",
            "tumbleDynamicX": "1",
            "tumbleDynamicY": "2",
            "tumbleDynamicZ": "2",
            "tumbleSpecialDynamicX": "1",
            "tumbleSpecialDynamicY": "2",
            "tumbleSpecialDynamicZ": "2",
        },
        "functions": [],
    },
    "Layout Boundary": {
        "variables": {
            "useLayoutBounds": "1",
            "layoutBoundX": "180",
            "layoutBoundY": "60",
            "layoutBoundZ": "470",
            "layoutCenterX": "-20",
            "layoutCenterY": "5",
            "layoutCenterZ": "0",
        },
        "functions": [],
    },
    "Families": {
        "variables": {
            "MinimalFamilyToFindPathAround": '"MotherShip"',
            "BuildFamily": '"SuperCap_Shi"',
            "AttackFamily": '"BigCapitalShip"',
            "DockFamily": '"Shipyard"',
            "AvoidanceFamily": '"BattleCruiser"',
            "DisplayFamily": '"Capital"',
            "AutoFormationFamily": '"CapShip"',
            "CollisionFamily": '"Big"',
            "ArmourFamily": 'getShipStr(NewShipType, "ArmourFamily", "HeavyArmour")',
        },
        "functions": [],
    },
    "Supply": {
        "variables": {},
        "functions": [
            {"name": "setSupplyValue", "args": ["Capital", "1.0"]},
            {"name": "setSupplyValue", "args": ["Lucifer", "1.0"]},
            {"name": "setSupplyValue", "args": ["LayoutBattleCruiser", "1.0"]},
        ],
    },
    "Ship Counter Rating": {
        "variables": {
            "AttackPriorityMultiplier": "0.94",
            "fighterValue": "0",
            "corvetteValue": "0",
            "frigateValue": "80",
            "neutralValue": "30",
            "antiFighterValue": "0",
            "antiCorvetteValue": "5",
            "antiFrigateValue": "60",
            "totalValue": "110",
        },
        "functions": [],
    },
    "Construction": {
        "variables": {
            "buildCost": "4000",
            "buildTime": "280",
            "buildPriorityOrder": "40",
        },
        "functions": [
            {"name": "setConcurrentBuildLimit", "args": ["0", "2"]},
        ],
    },
    "Sensors": {
        "variables": {
            "retaliationRange": "6500",
            "retaliationDistanceFromGoal": "160",
            "visualRange": "1000",
            "prmSensorRange": "7000",
            "secSensorRange": "8000",
            "detectionStrength": "1",
        },
        "functions": [],
    },
    "Tactical Overlay Icon": {
        "variables": {
            "TOIcon": '"Arrow"',
            "TOScale": "1",
            "TODistanceFade0": "14000",
            "TODistanceDisappear0": "12000",
            "TODistanceFade1": "8500",
            "TODistanceDisappear1": "7000",
            "TODistanceFade2": "12000",
            "TODistanceDisappear2": "35000",
            "TOGroupScale": "1",
            "TOGroupMergeSize": "0",
        },
        "functions": [],
    },
    "Overlays": {
        "variables": {
            "mouseOverMinFadeSize": "0.045",
            "mouseOverMaxFadeSize": "0.1",
            "healthBarStyle": "2",
            "SMRepresentation": '"Mesh"',
            "SMHighlightDistMin": "15000",
            "SMHighlightDistMax": "25000",
        },
        "functions": [],
    },
    "Non linear Scaling": {
        "variables": {
            "nlips": "0",
            "nlipsRange": "75000",
            "nlipsFar": "0",
            "nlipsFarRange": "0",
        },
        "functions": [],
    },
    "Rendering": {
        "variables": {
            "meshRenderLimit": "21000",
            "dotRenderLimit": "10",
            "visibleInSecondary": "1",
            "goblinsStartFade": "3200",
            "goblinsOff": "3200",
            "minimumZoomFactor": "0.5",
        },
        "functions": [],
    },
    "Level of Detail": {
        "variables": {"upLOD": "6150", "downLOD": "6165"},
        "functions": [],
    },
    "Selection": {
        "variables": {
            "selectionLimit": "150000",
            "preciseSelectionLimit": "7500",
            "preciseATILimit": "7000",
            "selectionPriority": "75",
            "militaryUnit": "1",
        },
        "functions": [],
    },
    "Alternative Hyperspace Gate": {
        "variables": {
            "alternativeHyperspaceV": "subspace_gate",
            "alternativeHyperspaceA": "etg/misc/large_subspace",
            "alternativeHyperspaceTime": "12",
        },
        "functions": [],
    },
    "Abilities": {
        "variables": {},
        "functions": [
            {"name": "addAbility", "args": ["MoveCommand", "1", "0"]},
            {"name": "addAbility", "args": ["CanDock", "1", "0"]},
            {"name": "addAbility", "args": ['CanLaunch"']},
            {
                "name": "addAbility",
                "args": [
                    "ShipHold",
                    "1",
                    "1000",
                    "20",
                    "rallypoint",
                    "Fighter, Utility",
                    "200",
                ],
            },
            {"name": "addAbility", "args": ["ParadeCommand", "1"]},
            {"name": "addAbility", "args": ['WaypointMove"']},
            {
                "name": "addAbility",
                "args": ["HyperSpaceCommand", "0", "2", "500", "1000", "0", "3"],
            },
            {
                "name": "addAbility",
                "args": [
                    "CanAttack",
                    "1",
                    "1",
                    "0",
                    "1",
                    "0.35",
                    "1.5",
                    "Capturer,Frigate,SmallCapitalShip,BigCapitalShip,Mothership,Utility,,,,,Corvette, Corvette_hw1,Fighter, Fighter_hw1",
                    "Frontal",
                    '{ Fighter = "MoveToTargetAndShoot" }',
                    '{ Fighter_hw1 = "MoveToTargetAndShoot" }',
                    '{ Corvette = "MoveToTargetAndShoot" }',
                    '{ Corvette_hw1 = "MoveToTargetAndShoot" }',
                    '{ Frigate = "Frontal" }',
                    '{ Munition = "MoveToTargetAndShoot" }',
                    '{ SubSystem = "MoveToTargetAndShoot" }',
                ],
            },
            {"name": "addAbility", "args": ["GuardCommand", "1", "3000", "1000"]},
            {
                "name": "addAbility",
                "args": [
                    "CanBuildShips",
                    "1",
                    "Fighter_Ter, Bomber_Ter, Cruiser_Ter, SuperCap_Ter, Utility_Ter, Platform_Ter, Battlecruiser_Ter, Shipyard_Ter, Probe_Ter",
                    "Utility, Fighter, Bomber, Cruiser, Capital, Platform",
                ],
            },
            {
                "name": "addAbility",
                "args": ["CanBeCaptured", "250", "0.5", 'CapCap"'],
            },
            {"name": "addAbility", "args": ["CanBeRepaired", 'RepCap"']},
        ],
    },
    "Docking": {
        "variables": {
            "dockTimeBetweenTwoFormations": "1",
            "dockTimeBeforeStart": "2",
            "dockNrOfShipsInDockFormation": "1",
            "dockFormation": '"delta"',
            "queueFormation": '"dockline"',
            "dontDockWithOtherRaceShips": "1",
            "ignoreRaceWhenDocking": "0",
        },
        "functions": [],
    },
    "Launching": {
        "variables": {
            "launchTimeBetweenTwoFormations": "1",
            "launchTimeBeforeStart": "2",
            "launchNrOfShipsInDockFormation": "1",
            "launchFormation": '"delta"',
        },
        "functions": [],
    },
    "Load Model": {
        "variables": {},
        "functions": [{"name": "LoadModel", "args": ["1"]}],
    },
    "HardPoints": {
        "variables": {},
        "functions": [
        ],
    },
    "Weapons": {
        "variables": {},
        "functions": [
        ],
    },
    "Shields": {
        "variables": {},
        "functions": [{"name": "addShield", "args": ["EMP", "10000", "20"]}],
    },
    "Engines": {
        "variables": {"trailLinger": "3"},
        "functions": [
            {
                "name": "setEngineBurn",
                "args": ["9", "0.2", "0.5", "300", "1.02", "0.1", "0.25", "380"],
            },
        ],
    },
    "Addendum": {
        "variables": {},
        "functions": [
            {
                "name": "loadShipPatchList",
                "args": ['data:sound/sfx/ship/', '0', '', '', '1', 'ShivanSuperCapital', '', '3', '', 'Root'],
            }
        ],
    },
    "Latch Points": {
        "variables": {},
        "functions": [
            {
                "name": "loadLatchPointList",
                "args": [
                    "CapCap",
                    "CapturePoint0",
                    "CapturePoint1",
                    "CapturePoint2",
                    'CapturePoint3"',
                    'CapturePoint4"',
                    'CapturePoint5"',
                ],
            },
            {
                "name": "loadLatchPointList",
                "args": [
                    "RepCap",
                    "RepairPoint0",
                    "RepairPoint1",
                    "RepairPoint2",
                    "RepairPoint3",
                    "RepairPoint4",
                    'RepairPoint5',
                ],
            },
        ],
    },
    "Scuttle": {
        "variables": {
            "minFalloffDamageDist": "425",
            "maxFalloffDamageDist": "425 * 1.5",
            "maxFalloffScuttleDamageDist": "575 * 3",
            "explosiveScuttleDamageOnDeath": "3725",
            "maxFalloffForce": "500 * 10",
            "explosiveDamageOnDeath": "745",
            "radiusDamageEvadeMod": "1.1",
        },
        "functions": [],
    },
}
