SHIP_DEFINITION = {
    "Ship Info": {
        "variables": {
            "displayedName": "",
            "sobDescription": "",
            "blobName": "",
            "blobNamePriority": 1,
        },
        "functions": [],
    },
    "Main Ship Data": {
        "variables": {"isTransferable": 0, "unavailableWhenCaptured": 0},
        "functions": [],
    },
    "Families": {
        "variables": {
            "MinimalFamilyToFindPathAround": "",
            "BuildFamily": "",
            "AttackFamily": "",
            "DockFamily": "",
            "AvoidanceFamily": "",
            "DisplayFamily": "",
            "AutoFormationFamily": "",
            "CollisionFamily": "",
            "ArmourFamily": "",
        },
        "functions": [],
    },
    "Supply": {
        "variables": {},
        "functions": [
            {
                "name": "SetSupplyValue",
                "args": ["Fighter", 5.0],
            },
            {
                "name": "SetSupplyValue",
                "args": ["LayoutFighter", 5.0],
            },
        ],
    },
    "Construction": {
        "variables": {
            "buildBatch": 'getShipNum(NewShipType,"buildBatch",4)',
            "buildCost": 0,
            "buildTime": 0,
            "buildPriorityOrder": 0,
        },
        "functions": [],
    },
    "Health and Armor": {
        "variables": {
            "maxhealth": 0,
            "regentime": 0,
            "minRegenTime": 0,
            "sideArmourDamage": 0,
            "rearArmourDamage": 0,
        },
        "functions": [],
    },
    "Shileds": {
        "variables": {},
        "functions": [{"name": "addShiled", "args": ["EMP", 220, 20]}],
    },
    "Sensors": {
        "variables": {
            "retaliationRange": 5500,
            "retaliationDistanceFromGoal": 160,
            "visualRange": 2000,
            "prmSensorRange": 0,
            "secSensorRange": 10000,
            "detectionStrength": 4,
        },
        "functions": [],
    },
    "Movement": {
        "variables": {
            "mass": 200,
            "thrusterMaxSpeed": 380,
            "thrusterAccelTime": 3,
            "thrusterBrakeTime": 1.5,
            "mainEngineMaxSpeed": 380,
            "mainEngineAccelTime": 3,
            "mainEngineBrakeTime": 1.5,
            "rotationMaxSpeed": 109,
            "rotationAccelTime": 0.6,
            "rotationBrakeTime": 0.3,
        },
        "functions": [],
    },
    "Advanced Movement": {
        "variables": {
            "controllerType": "Ship",
            "thrusterUsage": 0.5,
            "accelerationAngle": 170,
            "mirrorAngle": 30,
            "secondaryTurnAngle": 90,
            "maxBankingAmount": 85,
            "descendPitch": 0,
            "goalReachEpsilon": 5,
            "slideMoveRange": 0,
            "relativeMoveFactor": 6,
            "agileFlight": 1,
            "homingDistance": 1000,
            "homingDelay": 0.5,
            "useEngagementRanges": 1,
        },
        "functions": [
            {
                "name": "setSpeedvsAccuracyApplied",
                "args": [
                    100.0,
                    5.0,
                    120,
                    1.0,
                    250,
                    1.0,
                    388,
                    0.98,
                    535,
                    0.70,
                ],
            }
        ],
    },
    "Special Flight Maneuvers": {
        "variables": {
            "mirrorAboveManeuver": "ImmelMann_speedy, OneEightyDegRightTurn, OneEightyDegLeftTurn, ImmelMann_speedy, ImmelMann_speedy, ImmelMann_speedy",
            "mirrorBelowManeuver": "Split_S_speedy, OneEightyDegRightTurn, OneEightyDegLeftTurn, Split_S_speedy, Split_S_speedy, Split_S_speedy",
            "specialTurnLeftManeuver": "NinetyDegLeftTurn, None, None",
            "specialTurnRightManeuver": "NinetyDegRightTurn, None, None",
        },
        "functions": [],
    },
    "Swaying": {
        "variables": {
            "swayUpdateTime": 10,
            "swayOffsetRandomX": 10,
            "swayOffsetRandomY": 10,
            "swayOffsetRandomZ": 10,
            "swayBobbingFactor": 0,
            "swayRotateFactor": 0,
        },
        "functions": [],
    },
    "Tactics and Multipliers": {
        "variables": {
            "defaultStance": "Neutral",
            "defaultROE": "Defensive",
        },
        "functions": [
            {
                "name": "setTacticsMults",
                "args": [
                    "MAXSPEED",
                    0.85,
                    1.10,
                    1.0,
                ],
            },
            {
                "name": "setTacticsMults",
                "args": [
                    "ENGINEACCEL",
                    0.85,
                    1.0,
                    1.0,
                ],
            },
            {
                "name": "setTacticsMults",
                "args": [
                    "ENGINEBRAKE",
                    1.15,
                    1.0,
                    1.0,
                ],
            },
            {
                "name": "setTacticsMults",
                "args": [
                    "THRUSTER",
                    1.0,
                    1.0,
                    1.0,
                ],
            },
            {
                "name": "setTacticsMults",
                "args": [
                    "THRUSTERACCEL",
                    0.85,
                    1.0,
                    1.0,
                ],
            },
            {
                "name": "setTacticsMults",
                "args": [
                    "THRUSTERBRAKE",
                    1.0,
                    1.0,
                    1.0,
                ],
            },
            {
                "name": "setTacticsMults",
                "args": [
                    "ROTATION",
                    1.15,
                    1.05,
                    1.0,
                ],
            },
            {
                "name": "setTacticsMults",
                "args": [
                    "ROTATIONACCEL",
                    1.0,
                    1.0,
                    1.0,
                ],
            },
            {
                "name": "setTacticsMults",
                "args": [
                    "ROTATIONBRAKE",
                    1.15,
                    1.0,
                    1.0,
                ],
            },
            {
                "name": "setTacticsMults",
                "args": [
                    "WEAPONACCURACY",
                    1.05,
                    0.85,
                    1.0,
                ],
            },
            {
                "name": "setTacticsMults",
                "args": [
                    "WEAPONDAMAGE",
                    1.25,
                    0.75,
                    1.0,
                ],
            },
            {
                "name": "setTacticsMults",
                "args": [
                    "BULLETSPEED",
                    1.10,
                    0.90,
                    1.00,
                ],
            },
            {
                "name": "setTacticsMults",
                "args": [
                    "DAMAGEAPPLIED",
                    1.10,
                    0.90,
                    1.00,
                ],
            },
            {
                "name": "setTacticsMults",
                "args": [
                    "FIRERATE",
                    1.0,
                    1.25,
                    1.0,
                ],
            },
        ],
    },
    "Formations": {
        "variables": {
            "paradeData": "shi_build_parade",
            "formationSpacing": 40,
            "batchFormation": "Batch,delta",
            "canSurround": 1,
            "noCombatGrouping": 1,
            "canJoinStrikeGroup": 0,
            "strikeGroupRadius": 350,
            "strikeGroupSpeed": 5000,
            "SquadronSize": "getShipNum(NewShipType, SquadronSize, 4)",
        },
        "functions": [],
    },
    "Launching": {
        "variables": {
            "launchTimeBetweenTwoFormations": 0.5,
            "launchTimeBeforeStart": 0.5,
            "launchNrOfShipsInDockFormation": 1,
            "launchFormation": "n_delta",
        },
        "functions": [],
    },
    "Docking": {
        "variables": {
            "holdSlots": 4,
            "dockTimeBetweenTwoFormations": 0.5,
            "dockTimeBeforeStart": 0.5,
            "dockNrOfShipsInDockFormation": 1,
            "ignoreRaceWhenDocking": 0,
            "queueFormation": "n_delta",
            "dockFormation": "dockline",
            "dontDockWithOtherRaceShips": 1,
        },
        "functions": [],
    },
    "Ship Counter Rating": {
        "variables": {
            "AttackPriorityMultiplier": 0.96,
            "fighterValue": 8,
            "corvetteValue": 0,
            "frigateValue": 0,
            "neutralValue": 0,
            "antiFighterValue": 0,
            "antiCorvetteValue": 8,
            "antiFrigateValue": 0,
            "totalValue": 8,
        },
        "functions": [],
    },
    "Damage and Death": {
        "variables": {
            "dustCloudDamageTime": 160,
            "nebulaDamageTime": 80,
            "collisionMultiplier": 3,
            "normalCollisionDamageMultiplier": 2,
            "battleScarCoverage": 0,
            "battleScarBudgetLow": 0,
            "battleScarBudgetNext": 0,
            "sobDieTime": 0.1,
            "sobSpecialDieTime": 2,
            "specialDeathSpeed": 40,
            "chanceOfSpecialDeath": 0.25,
            "deadSobFadeTime": 0,
            "allowScuttle": 0,
        },
        "functions": [{"name": "setSpecialDieTime", "args": ["BIGROCK", 3]}],
    },
    "Death Tumble": {
        "variables": {
            "tumbleStaticX": 10,
            "tumbleStaticY": 20,
            "tumbleStaticZ": 5,
            "tumbleDynamicX": 2,
            "tumbleDynamicY": 10,
            "tumbleDynamicZ": 5,
            "tumbleSpecialDynamicX": 800,
            "tumbleSpecialDynamicY": 1000,
            "tumbleSpecialDynamicZ": 700,
        },
        "functions": [],
    },
    "Debris": {
        "variables": {},
        "functions": [
            {
                "name": "SpawnSalvageOnDeath",
                "args": [
                    "Slv_Chunk_Lrg03",
                    1,
                    0.40,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    50,
                    0,
                    0,
                    0,
                    200,
                    0,
                    0,
                    0,
                    50,
                    0,
                    0,
                    0,
                    50,
                ],
            }
        ],
    },
    "Layout Boundary": {
        "variables": {
            "useLayoutBounds": 1,
            "layoutBoundX": 200,
            "layoutBoundY": 1250,
            "layoutBoundZ": 280,
            "layoutCenterX": 0,
            "layoutCenterY": 0,
            "layoutCenterZ": 20,
        },
        "functions": [],
    },
    "Selection": {
        "variables": {
            "militaryUnit": 1,
            "selectionLimit": 150000,
            "preciseSelectionLimit": 14000,
            "preciseATILimit": 0,
            "selectionPriority": 75,
        },
        "functions": [],
    },
    "Tactical Overlay Icon": {
        "variables": {
            "TOIcon": "Triangle",
            "TOScale": 1,
            "TODistanceFade0": 7000,
            "TODistanceDisappear0": 5000,
            "TODistanceFade1": 2500,
            "TODistanceDisappear1": 2000,
            "TODistanceFade2": 12000,
            "TODistanceDisappear2": 35000,
            "TOGroupScale": 1.5,
            "TOGroupMergeSize": 0,
        },
        "functions": [],
    },
    "Overlays": {
        "variables": {
            "mouseOverMinFadeSize": 0.045,
            "mouseOverMaxFadeSize": 0.1,
            "healthBarStyle": 0,
            "SMRepresentation": "HardDot",
            "pixelSize": 2.5,
            "pixelColour": [0.69411, 0.545, 0.41176, 1.0],
            "SMFadeDistance": 150000,
            "SMFadeMinAlpha": 0.1,
            "SMPixelSize": 2.5,
            "SMHighlightDistMin": 20000,
            "SMHighlightDistMax": 25000,
            "hideNormalAttackUICooldown": 1,
            "canBlink": 1,
            "shipHoldActive": 1,
        },
        "functions": [],
    },
    "Rendering": {
        "variables": {
            "AlwaysInRenderList": 0,
            "meshRenderLimit": 10400000,
            "dotRenderLimit": 10,
            "visibleInSecondary": 1,
            "goblinsStartFade": 200,
            "goblinsOff": 200,
            "minimumZoomFactor": 0.75,
            "shadowType": 2,
        },
        "functions": [],
    },
    "Non linear Scaling": {
        "variables": {
            "nlips": 0.0002,
            "nlipsRange": 6000,
            "nlipsFar": 0.0001,
            "nlipsFarRange": 10000,
        },
        "functions": [],
    },
    "Level of Detail": {
        "variables": {
            "minLOD": 0.25,
            "upLOD": 500,
            "downLOD": 2515,
        },
        "functions": [],
    },
    "Alternative Hyperspace Gate": {
        "variables": {
            "alternativeHyperspaceV": "subspace_gate_small",
            "alternativeHyperspaceA": "etg/misc/small_subspace",
            "alternativeHyperspaceTime": 7,
        },
        "functions": [],
    },
    "Abilities": {
        "variables": {},
        "functions": [
            {"name": "addAbility", "args": ["CanLaunch"]},
            {"name": "addAbility", "args": ["CanDock", 1, 1]},
            {"name": "addAbility", "args": ["MoveCommand", 1, 0]},
            {
                "name": "addAbility",
                "args": [
                    "ShipHold",
                    1,
                    1000,
                    30,
                    "rallypoint",
                    "Fighter, Corvette, Utility",
                    50,
                ],
            },
            {"name": "addAbility", "args": ["ParadeCommand", 1]},
            {"name": "addAbility", "args": ["WaypointMove"]},
            {"name": "addAbility", "args": ["CaptureCommand", 1, 0]},
            {"name": "addAbility", "args": ["SalvageCommand", 1]},
            {
                "name": "addAbility",
                "args": ["HyperSpaceCommand", 0, 1, 700, 1400, 0, 0],
            },
            {
                "name": "addAbility",
                "args": [
                    "CanAttack",
                    1,
                    1,
                    0,
                    0,
                    0.35,
                    1.2,
                    "Munition, Mothership, BigCapitalShip, SmallCapitalShip, Capturer, Frigate",
                    "BroadSide",
                    '{ Fighter = "JustShoot" }',
                    '{ Fighter_hw1 = "JustShoot" }',
                    '{ Corvette = "JustShoot" }',
                    '{ Corvette_hw1 = "JustShoot" }',
                    '{ Munition = "MoveToTargetAndShoot" }',
                    '{ SubSystem = "MoveToTargetAndShoot" }',
                ],
            },
            {"name": "addAbility", "args": ["GuardCommand", 1, 3000, 1000]},
            {"name": "addAbility", "args": ["Harvest", 1, 300, 10, 300]},
            {
                "name": "addAbility",
                "args": [
                    "CanBuildShips",
                    1,
                    "Fighter_Shi, Bomber_Shi, Cruiser_Shi, SuperCap_Shi, Utility_Shi, Platform_Shi, Battlecruiser_Shi, Shipyard_Shi, Probe_Shi",
                    "Utility, Fighter, Bomber, Cruiser, Capital, Platform",
                ],
            },
            {
                "name": "addAbility",
                "args": ["FormHyperspaceGateCommand", 1, 1000, 500, 1000, 0],
            },
            {"name": "addAbility", "args": ["HyperspaceViaGateCommand", 1, 3, 7, 0.3]},
            {"name": "addAbility", "args": ["CanBeCaptured", 200, 0]},
            {"name": "addAbility", "args": ["CanBeSalvaged"]},
            {"name": "addAbility", "args": ["SensorPing", 1, 0, 15, 4]},
            {"name": "addAbility", "args": ["CanBeRepaired"]},
            {
                "name": "addAbility",
                "args": [
                    "RepairCommand",
                    1,
                    0,
                    100,
                    0,
                    "",
                    "{ Fighter = 0, }",
                    "{ Corvette = 0, }",
                    "{ Fighter_hw1 = 0, }",
                    "{ Corvette_hw1 = 0, }",
                ],
            },
            {
                "name": "CloakAbility",
                "args": [1, 2, 2000, 0, 1, 100, 0.6, 200],
            },
            {"name": "SpecialAttack", "args": [0, "EMP"]},
            {"name": "RetireAbility", "args": [1, 1]},
            {"name": "MinelayerAbility", "args": [1, 3.5]},
            {
                "name": "DefenseFieldAbility",
                "args": [
                    1,
                    0,
                    1200,
                    200,
                    200,
                    1,
                    0.6,
                    0,
                    "defensefield_sphere_spray",
                ],
            },
            {
                "name": "addAbility",
                "args": ["DefenseFieldShieldAbility", 0, 1200, 0, 0],
            },
            {"name": "addAbility", "args": ["HyperspaceInhibitorAbility", 0, 12000]},
            {
                "name": "addAbility",
                "args": ["CanBeSalvageCaptured", 0, 1, 0, 1, 1, "SalCap"],
            },
            {
                "name": "addAbility",
                "args": [
                    "CustomCommand",
                    1,
                    "Speed Burst",
                    1,
                    0,
                    38,
                    0,
                    1,
                    0.1,
                    0,
                    "data:scripts/custom_scripts/Afterburner.lua",
                    "Start_Afterburner",
                    "Do_Afterburner",
                    "Finish_Afterburner",
                    "ter_pegasus",
                    0.5,
                    3,
                    1,
                ],
            },
        ],
    },
    "Load Model": {"variables": {}, "functions": [{"name": "LoadModel", "args": [1]}]},
    "Weapons": {
        "variables": {},
        "functions": [
            {
                "name": "StartShipWeaponConfig",
                "args": ["beam_AARed", "Weapon_Turret04", ""],
            }
        ],
    },
    "HardPoints": {
        "variables": {},
        "functions": [
            {
                "name": "StartShipHardPointConfig",
                "args": [
                    "Shi_LRedSA1",
                    "Weapon_Turret01",
                    "Weapon",
                    "Innate",
                    "Damageable",
                    "shi_demonturret01",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ],
            }
        ],
    },
    "Latch Points": {
        "variables": {},
        "functions": [
            {
                "name": "loadLatchPointList",
                "args": ["SalCap", "SalvagePoint1", "SalvagePoint2"],
            }
        ],
    },
    "Addendum": {
        "variables": {},
        "functions": [
            {
                "name": "loadShipPatchList",
                "args": [
                    "data:sound/sfx/ship/",
                    0,
                    "",
                    "",
                    1,
                    "ShivanFighter",
                    "",
                    3,
                    "",
                    "Root",
                ],
            }
        ],
    },
    "Shaders": {
        "variables": {},
        "functions": [
            {"name": "addShaderProp", "args": ["SOB_surfGlow", 2, 2]},
            {"name": "setShaderChannels", "args": [0, 1.0, 1.0, 0.0, 0.0]},
        ],
    },
    "Engines": {
        "variables": {"trailLinger": 3},
        "functions": [
            {"name": "setEngineBurn", "args": [7, 0.5, 1, 15, 0, 0.7, 0.1, 28]},
            {
                "name": "setEngineGlow",
                "args": [1, 1, 1.02, 20, 300, 50, 1.5, {0.27, 0.47, 0.69, 0.25}],
            },
            {
                "name": "setEngineTrail",
                "args": [0, 4, "trail_ribbon.tga", 1, 2, 0.025, 3],
            },
        ],
    },
    "Custom Fields": {
        "variables": {},
        "functions": [
            {
                "name": "addCustomCode",
                "args": [
                    "data:scripts/custom_scripts/ABFix.lua",
                    "",
                    "",
                    "AfterburnerFix",
                    "",
                    "AfterburnerFix",
                    10,
                ],
            },
            {
                "name": "addCustomCode",
                "args": [
                    "data:scripts/custom_scripts/interceptor.lua",
                    "",
                    "",
                    "updateInterceptor",
                    "",
                    "ManticoreInterceptor",
                    1.25,
                ],
            },
        ],
    },
}
