fx = {
    style = "STYLE_BEAM",
    properties = {
        property_16 = {
            name = "LineDistance",
            type = "VARTYPE_FLOAT",
            value = 750000,
        },
        property_15 = {
            name = "WidthEpsilon",
            type = "VARTYPE_FLOAT",
            value = 0,
        },
        property_09 = {
            name = "Texture_U_Offset",
            type = "VARTYPE_ARRAY_TIMEFLOAT",
            value = {
                0,
                0,
                1,
                6,
            },
        },
        property_04 = {
            name = "SelfIlluminated",
            type = "VARTYPE_BOOL",
            value = 1,
        },
        property_03 = {
            name = "Texture",
            type = "VARTYPE_STRING",
            value = "DATA:ART/FX/BEAM/beam_green.tga",
        },
        property_06 = {
            name = "Length",
            type = "VARTYPE_ARRAY_TIMEFLOAT",
            value = {
                0,
                1,
                1,
                1,
            },
        },
        property_05 = {
            name = "Offset",
            type = "VARTYPE_ARRAY_TIMEVECTOR3",
            value = {
                entry_00 = {
                    0,
                    0,
                    0,
                    0,
                },
                entry_01 = {
                    1,
                    0,
                    0,
                    0,
                },
            },
        },
        property_08 = {
            name = "Segments",
            type = "VARTYPE_ARRAY_TIMEFLOAT",
            value = {
                0,
                1,
                1,
                10,
            },
        },
        property_07 = {
            name = "Noise",
            type = "VARTYPE_ARRAY_TIMEFLOAT",
            value = {
                0,
                0,
                1,
                0,
            },
        },
        property_02 = {
            name = "Blending",
            type = "VARTYPE_INT",
            value = 4,
        },
        property_01 = {
            name = "Loop",
            type = "VARTYPE_BOOL",
            value = 0,
        },
        property_13 = {
            name = "Arc",
            type = "VARTYPE_ARRAY_TIMEVECTOR3",
            value = {
                entry_00 = {
                    0,
                    0,
                    0,
                    0,
                },
                entry_01 = {
                    1,
                    0,
                    0,
                    0,
                },
            },
        },
        property_14 = {
            name = "LengthEpsilon",
            type = "VARTYPE_FLOAT",
            value = 0,
        },
        property_11 = {
            name = "Width",
            type = "VARTYPE_ARRAY_TIMEFLOAT",
            value = {
                0, --0 sec
                128,
                0.03,
                144,
                0.06,
                128,
                0.09,
                144,
                0.12,
                128,
                0.15,
                144,
                0.18,
                128,
                0.21,
                144,
                0.24,
                128,
                0.27,
                144,
                0.30,
                128,
                0.33,
                144,
                0.36,
                128,
                0.39,
                144,
                0.42,
                128,
                0.45,
                144,
                0.48,
                128,
                0.51,
                144,
                0.54,
                128,
                0.57,
                144,
                0.48,
                128,
                0.63,
                144,
                0.66,
                128,
                0.69,
                144,
                0.72,
                128,
                0.75,
                144,
                0.78,
                128,
                0.81,
                144,
                0.84,
                128,
                0.87,
                144,
                0.90,
                128,
                0.93,
                144,
                0.96,
                128,
                1, --2.1 sec
                64,
            },
        },
        property_12 = {
            name = "Colour",
            type = "VARTYPE_ARRAY_TIMECOLOUR",
            value = {
                entry_00 = {
                    0,
                    0,
                    0,
                    0,
                    1,
                },
                entry_01 = {
                    0.02537,
                    0.52830,
                    0.52830,
                    0.52830,
                    1,
                },
                entry_02 = {
                    0.85672,
                    0.52830,
                    0.52830,
                    0.52830,
                    1,
                },
                entry_03 = {
                    1,
                    0.51887,
                    0.51887,
                    0.51887,
                    1,
                },
            },
        },
        property_00 = {
            name = "Duration",
            type = "VARTYPE_FLOAT",
            value = 2,
        },
        property_10 = {
            name = "Texture_U_Repeat",
            type = "VARTYPE_ARRAY_TIMEFLOAT",
            value = {
                0,
                10,
                1,
                10,
            },
        },
    },
}
